

#define BT00_COORDS	x	167	\
			y	422

#define BT00_SIZE	size_x	58	\
			size_y	57


#define BT01_COORDS	x	33	\
			y	24

#define BT01_SIZE	size_x	71	\
			size_y	88


#define BT02_COORDS	x	728	\
			y	25

#define BT02_SIZE	size_x	36	\
			size_y	89


#define BT03_COORDS	x	17	\
			y	497

#define BT03_SIZE	size_x	66	\
			size_y	75


#define BT04_COORDS	x	670	\
			y	395

#define BT04_SIZE	size_x	100	\
			size_y	78


#define BT05_COORDS	x	716	\
			y	491

#define BT05_SIZE	size_x	61	\
			size_y	84


#define BT06_COORDS	x	86	\
			y	47

#define BT06_SIZE	size_x	75	\
			size_y	75


#define BT07_COORDS	x	174	\
			y	10

#define BT07_SIZE	size_x	92	\
			size_y	50


#define BT08_COORDS	x	287	\
			y	47

#define BT08_SIZE	size_x	70	\
			size_y	80


#define BT09_COORDS	x	36	\
			y	418

#define BT09_SIZE	size_x	91	\
			size_y	78


#define BT10_COORDS	x	135	\
			y	426

#define BT10_SIZE	size_x	60	\
			size_y	26


#define BT11_COORDS	x	211	\
			y	423

#define BT11_SIZE	size_x	32	\
			size_y	28


#define BT12_COORDS	x	267	\
			y	425

#define BT12_SIZE	size_x	59	\
			size_y	26


#define BT13_COORDS	x	911	\
			y	496

#define BT13_SIZE	size_x	64	\
			size_y	61


#define BT14_COORDS	x	1022	\
			y	495

#define BT14_SIZE	size_x	66	\
			size_y	64


#define BT15_COORDS	x	1132	\
			y	496

#define BT15_SIZE	size_x	46	\
			size_y	68
