

#define BT00_COORDS	x	99	\
			y	381

#define BT00_SIZE	size_x	58	\
			size_y	57


#define BT01_COORDS	x	20	\
			y	19

#define BT01_SIZE	size_x	69	\
			size_y	86


#define BT02_COORDS	x	728	\
			y	25

#define BT02_SIZE	size_x	36	\
			size_y	89


#define BT03_COORDS	x	14	\
			y	496

#define BT03_SIZE	size_x	69	\
			size_y	76


#define BT04_COORDS	x	712	\
			y	402

#define BT04_SIZE	size_x	66	\
			size_y	60


#define BT05_COORDS	x	716	\
			y	491

#define BT05_SIZE	size_x	61	\
			size_y	84


#define BT06_COORDS	x	79	\
			y	47

#define BT06_SIZE	size_x	81	\
			size_y	75


#define BT08_COORDS	x	287	\
			y	47

#define BT08_SIZE	size_x	70	\
			size_y	80


#define BT09_COORDS	x	69	\
			y	447

#define BT09_SIZE	size_x	67	\
			size_y	59


#define BT10_COORDS	x	140	\
			y	420

#define BT10_SIZE	size_x	52	\
			size_y	32


#define BT11_COORDS	x	207	\
			y	414

#define BT11_SIZE	size_x	44	\
			size_y	38


#define BT12_COORDS	x	265	\
			y	423

#define BT12_SIZE	size_x	55	\
			size_y	30


#define BT13_COORDS	x	911	\
			y	496

#define BT13_SIZE	size_x	64	\
			size_y	61


#define BT14_COORDS	x	1022	\
			y	495

#define BT14_SIZE	size_x	66	\
			size_y	64


#define BT15_COORDS	x	1132	\
			y	496

#define BT15_SIZE	size_x	46	\
			size_y	68
