

#define BT00_COORDS	x	22	\
			y	204

#define BT00_SIZE	size_x	54	\
			size_y	53


#define BT01_COORDS	x	24	\
			y	25

#define BT01_SIZE	size_x	61	\
			size_y	91


#define BT02_COORDS	x	728	\
			y	25

#define BT02_SIZE	size_x	36	\
			size_y	89


#define BT03_COORDS	x	17	\
			y	496

#define BT03_SIZE	size_x	66	\
			size_y	76


#define BT04_COORDS	x	688	\
			y	400

#define BT04_SIZE	size_x	86	\
			size_y	73


#define BT05_COORDS	x	714	\
			y	491

#define BT05_SIZE	size_x	63	\
			size_y	84


#define BT06_COORDS	x	86	\
			y	47

#define BT06_SIZE	size_x	75	\
			size_y	75


#define BT07_COORDS	x	174	\
			y	10

#define BT07_SIZE	size_x	92	\
			size_y	50


#define BT08_COORDS	x	287	\
			y	47

#define BT08_SIZE	size_x	70	\
			size_y	80


#define BT09_COORDS	x	60	\
			y	404

#define BT09_SIZE	size_x	59	\
			size_y	64


#define BT10_COORDS	x	134	\
			y	411

#define BT10_SIZE	size_x	60	\
			size_y	32


#define BT11_COORDS	x	204	\
			y	426

#define BT11_SIZE	size_x	52	\
			size_y	19


#define BT12_COORDS	x	266	\
			y	414

#define BT12_SIZE	size_x	61	\
			size_y	30


#define BT13_COORDS	x	911	\
			y	496

#define BT13_SIZE	size_x	64	\
			size_y	61


#define BT14_COORDS	x	1022	\
			y	495

#define BT14_SIZE	size_x	66	\
			size_y	64


#define BT15_COORDS	x	1132	\
			y	496

#define BT15_SIZE	size_x	46	\
			size_y	68
