

#define BUG00_COORDS	x	55	\
			y	402

#define BUG00_SIZE	size_x	56	\
			size_y	57


#define BUG01_COORDS	x	7	\
			y	474

#define BUG01_SIZE	size_x	56	\
			size_y	57


#define BUG02_COORDS	x	94	\
			y	496

#define BUG02_SIZE	size_x	50	\
			size_y	52


#define BUG03_COORDS	x	333	\
			y	541

#define BUG03_SIZE	size_x	52	\
			size_y	48


#define BUG04_COORDS	x	423	\
			y	532

#define BUG04_SIZE	size_x	48	\
			size_y	50


#define BUG05_COORDS	x	632	\
			y	501

#define BUG05_SIZE	size_x	57	\
			size_y	52


#define BUG06_COORDS	x	711	\
			y	490

#define BUG06_SIZE	size_x	55	\
			size_y	46


#define BUG07_COORDS	x	849	\
			y	489

#define BUG07_SIZE	size_x	53	\
			size_y	57


#define BUG08_COORDS	x	1154	 \
			y	538

#define BUG08_SIZE	size_x	51	\
			size_y	48


#define BUG09_COORDS	x	1374	 \
			y	481

#define BUG09_SIZE	size_x	48	\
			size_y	53


#define BUG10_COORDS	x	1447	 \
			y	478

#define BUG10_SIZE	size_x	57	\
			size_y	45
