
	#define iCHAT_LEVEL	-40
	#define iCHAT_SCALE	128


	ScaledTerrain { // Chat players block
		x	542
		y	257

		size_x	176
		size_y	206

//		  x	  545
//		  y	  260

//		  size_x  170
//		  size_y  200

		null_level	$iCHAT_LEVEL
		scale		$iCHAT_SCALE
	}

	ScaledTerrain { // Chat input
		x	82
		y	437

		size_x	456
		size_y	26

//		  x	  85
//		  y	  440

//		  size_x  450
//		  size_y  20

		null_level	$iCHAT_LEVEL
		scale		$iCHAT_SCALE
	}

	ScaledTerrain { // Chat button "ALL"
		x	542
		y	107

		size_x	176
		size_y	26

//		  x	  545
//		  y	  110

//		  size_x  170
//		  size_y  20

		null_level	$iCHAT_LEVEL
		scale		$iCHAT_SCALE
	}

	ScaledTerrain { // Chat button "GREEN"
		x	542
		y	137

		size_x	176
		size_y	26

//		  x	  545
//		  y	  140

//		  size_x  170
//		  size_y  20

		null_level	$iCHAT_LEVEL
		scale		$iCHAT_SCALE
	}

	ScaledTerrain { // Chat button "ORANGE"
		x	542
		y	167

		size_x	176
		size_y	26

//		  x	  545
//		  y	  170

//		  size_x  170
//		  size_y  20

		null_level	$iCHAT_LEVEL
		scale		$iCHAT_SCALE
	}

	ScaledTerrain { // Chat button "BLUE"
		x	542
		y	197

		size_x	176
		size_y	26

//		  x	  545
//		  y	  200

//		  size_x  170
//		  size_y  20

		null_level	$iCHAT_LEVEL
		scale		$iCHAT_SCALE
	}

	ScaledTerrain { // Chat button "YELLOW"
		x	542
		y	227

		size_x	176
		size_y	26

//		  x	  545
//		  y	  230

//		  size_x  170
//		  size_y  20

		null_level	$iCHAT_LEVEL
		scale		$iCHAT_SCALE
	}

	ScaledTerrain { // Chat history
		x	82
		y	107

		size_x	456
		size_y	326

//		  x	  85
//		  y	  110

//		  size_x  450
//		  size_y  320

		null_level	$iCHAT_LEVEL
		scale		$iCHAT_SCALE
	}

	ScaledTerrain { // Clear history
		x	{ 85 + 143 + 7 }
		y	77

		size_x	149
		size_y	26

//		  x	  { 85 + 143 + 10 }
//		  y	  80

//		  size_x  143
//		  size_y  20

		null_level	$iCHAT_LEVEL
		scale		$iCHAT_SCALE
	}

	ScaledTerrain { // Mute
		x	82
		y	77

		size_x	149
		size_y	26

		null_level	$iCHAT_LEVEL
		scale		$iCHAT_SCALE
	}


