
// ZeePa...

#define LSCREEN_ID		"LocScreen05"
#define LSCREEN_SHOP_ID 	"LocScreen05Shop"
#define LPALETTE_ID		"resource/iscreen/ldata/l5/escave.pal"
#define LBORDER_ID		"resource/iscreen/ldata/l5/border"
#define MATRIX_TERRAIN		5

#define AVI_OBJ_X		45
#define AVI_OBJ_Y		144

#define BT00_BMP		"resource/iscreen/ldata/l5/buttons/bt00.bmp"
#define BT01_BMP		"resource/iscreen/ldata/l5/buttons/bt01.bmp"
#define BT02_BMP		"resource/iscreen/ldata/l5/buttons/bt02.bmp"
#define BT03_BMP		"resource/iscreen/ldata/l5/buttons/bt03.bmp"
#define BT04_BMP		"resource/iscreen/ldata/l5/buttons/bt04.bmp"
#define BT05_BMP		"resource/iscreen/ldata/l5/buttons/bt05.bmp"
#define BT06_BMP		"resource/iscreen/ldata/l5/buttons/bt06.bmp"
#define BT07_BMP		"resource/iscreen/ldata/l5/buttons/bt07.bmp"
#define BT08_BMP		"resource/iscreen/ldata/l5/buttons/bt08.bmp"
#define BT09_BMP		"resource/iscreen/ldata/l5/buttons/bt09.bmp"
#define BT10_BMP		"resource/iscreen/ldata/l5/buttons/bt10.bmp"
#define BT11_BMP		"resource/iscreen/ldata/l5/buttons/bt11.bmp"
#define BT12_BMP		"resource/iscreen/ldata/l5/buttons/bt12.bmp"
#define BT13_BMP		"resource/iscreen/ldata/l5/buttons/bt13.bmp"
#define BT14_BMP		"resource/iscreen/ldata/l5/buttons/bt14.bmp"
#define BT15_BMP		"resource/iscreen/ldata/l5/buttons/bt15.bmp"

#define BT04_BMP_NULL	$BUTTON_BMP_NULL
#define BT04_NULL	200

#define BT10_SCALE	64
#define BT10_SMOOTH	2
#define BT10_BMP_NULL	0
#define BT10_NULL	128

#define BT12_SCALE	64
#define BT12_SMOOTH	2
#define BT12_BMP_NULL	0
#define BT12_NULL	128

#include "iscreen/scripts/btn05.inc"
#include "iscreen/scripts/pnl00.inc"
#include "iscreen/scripts/pnl06.inc"
#include "iscreen/scripts/pnl05.inc"

#include "iscreen/scripts/escave/escave00.inc"
#include "iscreen/scripts/escave/bt00.inc"
#include "iscreen/scripts/escave/bt01.inc"
#include "iscreen/scripts/escave/bt02.inc"
#include "iscreen/scripts/escave/bt03.inc"
#include "iscreen/scripts/escave/bt04.inc"
#include "iscreen/scripts/escave/bt05.inc"
#include "iscreen/scripts/escave/escave01.inc"

#include "iscreen/scripts/escave/escave02.inc"
#include "iscreen/scripts/escave/bt06.inc"
#include "iscreen/scripts/escave/bt07.inc"
#include "iscreen/scripts/escave/bt08.inc"
#include "iscreen/scripts/escave/bt09.inc"
#include "iscreen/scripts/escave/bt10.inc"
#include "iscreen/scripts/escave/bt11.inc"
#include "iscreen/scripts/escave/bt12.inc"
#include "iscreen/scripts/escave/bt13.inc"
#include "iscreen/scripts/escave/bt14.inc"
#include "iscreen/scripts/escave/bt15.inc"
#include "iscreen/scripts/escave/escave03.inc"

