
// Spobs...

#define LSCREEN_ID		"LocScreen07"
#define LPALETTE_ID		"resource/iscreen/ldata/l7/escave.pal"

#define BT01_BMP		"resource/iscreen/ldata/l7/buttons/bt01.bmp"
#define BT02_BMP		"resource/iscreen/ldata/l7/buttons/bt02.bmp"
#define BT03_BMP		"resource/iscreen/ldata/l7/buttons/bt03.bmp"
#define BT05_BMP		"resource/iscreen/ldata/l7/buttons/bt04.bmp"

#include "iscreen/scripts/btn07.inc"
#include "iscreen/scripts/pnl00.inc"
#include "iscreen/scripts/pnl07.inc"

#include "iscreen/scripts/escave/escave00.inc"
#include "iscreen/scripts/escave/bt01.inc"

#define BT02_NULL		175
#include "iscreen/scripts/escave/bt02.inc"
#define BT02_NULL		150
#include "iscreen/scripts/escave/escave01.inc"

