
// MainMenu...
#define EXIT_X1 		426
#define EXIT_Y1 		380

//426
#define EXIT_X2 		426
#define EXIT_Y2 		380

// Graphics options...
#define KEEP_STR_X1		90
#define KEEP_TRG_X1		600

#define KEEP_STR_X2		85
#define KEEP_TRG_X2		614

#define DESTR_TRG_X1		600
#define DESTR_TRG_X2		615

#define Graphics_screen_CleanUpObj_PosX1 550
#define Graphics_screen_InUseObj_PosX1	 90

#define Graphics_screen_CleanUpObj_PosX2 566
#define Graphics_screen_InUseObj_PosX2	 36

// LAN Servers...
#define UP_LIST_X1		150
#define UP_LIST_Y1		400

#define UP_LIST_X2		30
#define UP_LIST_Y2		400

#define UPDATE_LIST_X1		300
#define UPDATE_LIST_Y1		400

#define UPDATE_LIST_X2		320
#define UPDATE_LIST_Y2		400

#define DN_LIST_X1		580
#define DN_LIST_Y1		400

#define DN_LIST_X2		660
#define DN_LIST_Y2		400

#define SLIST_BACK_X1		40
#define SLIST_BACK_Y1		20

#define SLIST_BACK_X2		320
#define SLIST_BACK_Y2		450

// ------------ Screen: "Controls screen" ENG ------------

#define Controls_screen_More_Option_PosX1	532
#define Controls_screen_More_Option_PosY1	395

#define Controls_screen_Back_Option_PosX1	90
#define Controls_screen_Back_Option_PosY1	395

#define Controls_screen_Defaults_Option_PosX1	219
#define Controls_screen_Defaults_Option_PosY1	443

// ------------ Screen: "Controls screen" LOC ------------

#define Controls_screen_More_Option_PosX2	425
#define Controls_screen_More_Option_PosY2	400

#define Controls_screen_Back_Option_PosX2	188
#define Controls_screen_Back_Option_PosY2	400

#define Controls_screen_Defaults_Option_PosX2	98
#define Controls_screen_Defaults_Option_PosY2	452

// ------------ Screen: "Sound screen" ENG ------------

#define Sound_screen_BackSndTrig_PosX1	530
#define Sound_screen_BackSndStr_PosX1	110
#define Sound_screen_MechSndTrig_PosX1	530
#define Sound_screen_MechSndStr_PosX1	170
#define Sound_screen_PanningTrig_PosX1	530
#define Sound_screen_PanningStr_PosX1	130
#define Sound_screen_MusScrlObj_PosX1	430
#define Sound_screen_MusicStr2_PosX1	160
#define Sound_screen_SndScrlObj_PosX1	430
#define Sound_screen_SoundStr2_PosX1	160
#define Sound_screen_MusicTrig_PosX1	530
#define Sound_screen_MusicStr_PosX1	220
#define Sound_screen_SoundTrig_PosX1	530
#define Sound_screen_SoundStr_PosX1	130

// ------------ Screen: "Sound screen" LOC ------------

#define Sound_screen_BackSndTrig_PosX2	510
#define Sound_screen_BackSndStr_PosX2	146
#define Sound_screen_MechSndTrig_PosX2	510
#define Sound_screen_MechSndStr_PosX2	108
#define Sound_screen_PanningTrig_PosX2	510
#define Sound_screen_PanningStr_PosX2	122
#define Sound_screen_MusScrlObj_PosX2	432
#define Sound_screen_MusicStr2_PosX2	106
#define Sound_screen_SndScrlObj_PosX2	432
#define Sound_screen_SoundStr2_PosX2	122
#define Sound_screen_MusicTrig_PosX2	510
#define Sound_screen_MusicStr_PosX2	213
#define Sound_screen_SoundTrig_PosX2	510
#define Sound_screen_SoundStr_PosX2	115

// ------------ Screen: "Server screen" ENG ------------

#define Server_screen_Back_Option_PosX1 20
#define Server_screen_Back_Option_PosY1 20

// ------------ Screen: "Server screen" LOC ------------

#define Server_screen_Back_Option_PosX2 330
#define Server_screen_Back_Option_PosY2 393

// ------------ Screen: "Identification screen" ENG ------------

#define Identification_screen_Back_Option_PosX1 20
#define Identification_screen_Back_Option_PosY1 20

// ------------ Screen: "Identification screen" LOC ------------

#define Identification_screen_Back_Option_PosX2 330
#define Identification_screen_Back_Option_PosY2 400

// ------------ Screen: "Select Game" ENG ------------

#define Select_Game_Back_Option_PosX1	20
#define Select_Game_Back_Option_PosY1	20

// ------------ Screen: "Select Game" LOC ------------

#define Select_Game_Back_Option_PosX2	330
#define Select_Game_Back_Option_PosY2	411

// ------------ Screen: "Game Params 0" ENG ------------

#define Game_Params_0_AccessTrig_PosX1		 380
#define Game_Params_0_AccessStr_PosX1		 245
#define Game_Params_0_TeamTrig_PosX1		 445
#define Game_Params_0_TeamStr_PosX1		 260
#define Game_Params_0_EscaveTrig_PosX1		 405
#define Game_Params_0_BirthTrig_PosX1		 405
#define Game_Params_0_BirthStr_PosX1		 245
#define Game_Params_0_EscaveMinStr_PosX1	 500
#define Game_Params_0_EscaveTimeStr_PosX1	 210
#define Game_Params_0_TimeTrig_PosX1		 450
#define Game_Params_0_ArtefactsTrig_PosX1	 480
#define Game_Params_0_ArtefactsStr_PosX1	 240
#define Game_Params_0_BeebosNumberStr_PosX1	 391
#define Game_Params_0_BeebosStr_PosX1		 520
#define Game_Params_0_CashStr_PosX1		 180
#define Game_Params_0_Ok_Option_PosX1		 249
#define Game_Params_0_Back_Option_PosX1 	 367
#define Game_Params_0_MaxKillsNumberStr_PosX1	 440
#define Game_Params_0_MaxKillsStr_PosX1 	 280
#define Game_Params_0_MaxTimeNumberStr_PosX1	 380
#define Game_Params_0_MaxTimeMinStr_PosX1	 470
#define Game_Params_0_MaxTimeStr_PosX1		 270

// ------------ Screen: "Game Params 0" LOC ------------

#define Game_Params_0_MaxKillsNumberStr_PosX2	 509
#define Game_Params_0_MaxKillsStr_PosX2  246
#define Game_Params_0_MaxTimeNumberStr_PosX2	 391
#define Game_Params_0_MaxTimeMinStr_PosX2	 480
#define Game_Params_0_MaxTimeStr_PosX2	 272
#define Game_Params_0_AccessTrig_PosX2	 400
#define Game_Params_0_AccessStr_PosX2	 263
#define Game_Params_0_TeamTrig_PosX2	 499
#define Game_Params_0_TeamStr_PosX2	 244
#define Game_Params_0_EscaveTrig_PosX2	 418
#define Game_Params_0_BirthTrig_PosX2	 418
#define Game_Params_0_BirthStr_PosX2	 235
#define Game_Params_0_EscaveMinStr_PosX2 571
#define Game_Params_0_EscaveTimeStr_PosX2	 188
#define Game_Params_0_TimeTrig_PosX2	 535
#define Game_Params_0_ArtefactsTrig_PosX2	 591
#define Game_Params_0_ArtefactsStr_PosX2 168
#define Game_Params_0_BeebosNumberStr_PosX2	 481
#define Game_Params_0_BeebosStr_PosX2	 595
#define Game_Params_0_CashStr_PosX2	 190
#define Game_Params_0_Ok_Option_PosX2	 245
#define Game_Params_0_Back_Option_PosX2  423

// ------------ Screen: "Game Params 1" ENG ------------

#define Game_Params_1_OneTimeNum_PosX1		 510
#define Game_Params_1_OneTimeStr_PosX1		 220
#define Game_Params_1_ItemsNumber2_PosX1	 550
#define Game_Params_1_ItemsNumber1_PosX1	 350
#define Game_Params_1_ItemStrTrig2_PosX1	 410
#define Game_Params_1_ItemStrTrig1_PosX1	 210
#define Game_Params_1_TeamTrig_PosX1		 445
#define Game_Params_1_TeamStr_PosX1		 260
#define Game_Params_1_WorldTrig_PosX1		 405
#define Game_Params_1_WorldStr_PosX1		 300

// ------------ Screen: "Game Params 1" LOC ------------

#define Game_Params_1_OneTimeNum_PosX2	 552
#define Game_Params_1_OneTimeStr_PosX2	 227
#define Game_Params_1_ItemsNumber2_PosX2 560
#define Game_Params_1_ItemsNumber1_PosX2 360
#define Game_Params_1_ItemStrTrig2_PosX2 420
#define Game_Params_1_ItemStrTrig1_PosX2 220
#define Game_Params_1_TeamTrig_PosX2	 513
#define Game_Params_1_TeamStr_PosX2	 251
#define Game_Params_1_WorldTrig_PosX2	 401
#define Game_Params_1_WorldStr_PosX2	 301

// ------------ Screen: "Server Info screen" ENG ------------

#define Server_Info_screen_Chat_Option_PosX1	110
#define Server_Info_screen_Game_Option_PosX1	616

// ------------ Screen: "Server Info screen" LOC ------------

#define Server_Info_screen_Chat_Option_PosX2	110
#define Server_Info_screen_Game_Option_PosX2	616

// ------------ Screen: "Chat screen" ENG ------------

#define Chat_screen_Game_Option_PosX1	 504
#define Chat_screen_Game_Option_PosY1	 553
#define Chat_screen_Server_Option_PosX1  104
#define Chat_screen_Server_Option_PosY1  556

// ------------ Screen: "Chat screen" LOC ------------

#define Chat_screen_Game_Option_PosX2	 489
#define Chat_screen_Game_Option_PosY2	 550
#define Chat_screen_Server_Option_PosX2  147
#define Chat_screen_Server_Option_PosY2  549

// ------------ Screen: "INet Host screen" ENG ------------

#define INet_Host_screen_ProxyPortNumStr_PosX1	 300
#define INet_Host_screen_ProxyPortStr_PosX1	 181
#define INet_Host_screen_ProxyServerNameStr_PosX1	 300
#define INet_Host_screen_ProxyServerStr_PosX1	 160
#define INet_Host_screen_ProxyTrg_PosX1  470
#define INet_Host_screen_ProxyStr_PosX1  242
#define INet_Host_screen_Ok_Option_PosX1 294
#define INet_Host_screen_Back_Option_PosX1	 400
#define INet_Host_screen_IP_Str_PosX1	270
#define INet_Host_screen_IP_Addr_PosX1	420

// ------------ Screen: "INet Host screen" LOC ------------

#define INet_Host_screen_ProxyPortNumStr_PosX2	 300
#define INet_Host_screen_ProxyPortStr_PosX2	 181
#define INet_Host_screen_ProxyServerNameStr_PosX2	 300
#define INet_Host_screen_ProxyServerStr_PosX2	 160
#define INet_Host_screen_ProxyTrg_PosX2  490
#define INet_Host_screen_ProxyStr_PosX2  241
#define INet_Host_screen_Ok_Option_PosX2 234
#define INet_Host_screen_Back_Option_PosX2	 420
#define INet_Host_screen_IP_Str_PosX2	270
#define INet_Host_screen_IP_Addr_PosX2	420

// ------------ Screen: "Port screen" ENG ------------

#define Port_screen_Default_Option_PosX1 210
#define Port_screen_Default_Option_PosY1 290
#define Port_screen_PortStr_PosX1	 502
#define Port_screen_PortStr_PosY1	 189
#define Port_screen_Back_Option_PosX1	 460
#define Port_screen_Back_Option_PosY1	 290
#define Port_screen_TitleStr_PosX1	 200
#define Port_screen_TitleStr_PosY1	 188

// ------------ Screen: "Port screen" LOC ------------

#define Port_screen_Default_Option_PosX2 91
#define Port_screen_Default_Option_PosY2 290
#define Port_screen_PortStr_PosX2	 520
#define Port_screen_PortStr_PosY2	 188
#define Port_screen_Back_Option_PosX2	 519
#define Port_screen_Back_Option_PosY2	 290
#define Port_screen_TitleStr_PosX2	 183
#define Port_screen_TitleStr_PosY2	 188

// ------------ Screen: "HallOfFame screen" ENG ------------

#define HallOfFame_screen_Back_Option_PosX1	 461
#define HallOfFame_screen_Back_Option_PosY1	 539

// ------------ Screen: "HallOfFame screen" LOC ------------

#define HallOfFame_screen_Back_Option_PosX2	 461
#define HallOfFame_screen_Back_Option_PosY2	 539

// ------------ Screen: "iSearch server screen" ENG ------------

#define iSearch_server_screen_Down_Option_PosX1  660
#define iSearch_server_screen_Down_Option_PosY1  400
#define iSearch_server_screen_Up_Option_PosX1	 30
#define iSearch_server_screen_Up_Option_PosY1	 400
#define iSearch_server_screen_Back_Option_PosX1  344
#define iSearch_server_screen_Back_Option_PosY1  451

// ------------ Screen: "iSearch server screen" LOC ------------

#define iSearch_server_screen_Back_Option_PosX2  344
#define iSearch_server_screen_Back_Option_PosY2  451
#define iSearch_server_screen_Down_Option_PosX2  617
#define iSearch_server_screen_Down_Option_PosY2  400
#define iSearch_server_screen_Up_Option_PosX2	 55
#define iSearch_server_screen_Up_Option_PosY2	 400


// ------------ Screen: "Search server screen" ENG ------------

#define Search_server_screen_Down_Option_PosX1	 660
#define Search_server_screen_Down_Option_PosY1	 400
#define Search_server_screen_Up_Option_PosX1	 30
#define Search_server_screen_Up_Option_PosY1	 400

// ------------ Screen: "Search server screen" LOC ------------

#define Search_server_screen_Down_Option_PosX2	 611
#define Search_server_screen_Down_Option_PosY2	 400
#define Search_server_screen_Up_Option_PosX2	 74
#define Search_server_screen_Up_Option_PosY2	 400


