
#define KEEP_STR_X	$KEEP_STR_X1
#define KEEP_TRG_X	$KEEP_TRG_X1

#define Graphics_screen_CleanUpObj_PosX 	$Graphics_screen_CleanUpObj_PosX1
#define Graphics_screen_InUseObj_PosX		$Graphics_screen_InUseObj_PosX1

#define EXIT_X		$EXIT_X1
#define EXIT_Y		$EXIT_Y1

#define DESTR_TRG_X	$DESTR_TRG_X1

#define UP_LIST_X	$UP_LIST_X1
#define UP_LIST_Y	$UP_LIST_Y1

#define UPDATE_LIST_X	$UPDATE_LIST_X1
#define UPDATE_LIST_Y	$UPDATE_LIST_Y1

#define DN_LIST_X	$DN_LIST_X1
#define DN_LIST_Y	$DN_LIST_Y1

#define SLIST_BACK_X	$SLIST_BACK_X1
#define SLIST_BACK_Y	$SLIST_BACK_Y1


// ------------ Screen: "Controls screen" ------------

#define Controls_screen_More_Option_PosX	$Controls_screen_More_Option_PosX1
#define Controls_screen_More_Option_PosY	$Controls_screen_More_Option_PosY1

#define Controls_screen_Back_Option_PosX	$Controls_screen_Back_Option_PosX1
#define Controls_screen_Back_Option_PosY	$Controls_screen_Back_Option_PosY1

#define Controls_screen_Defaults_Option_PosX	$Controls_screen_Defaults_Option_PosX1
#define Controls_screen_Defaults_Option_PosY	$Controls_screen_Defaults_Option_PosY1

// ------------ Screen: "Sound screen" ------------

#define Sound_screen_BackSndTrig_PosX	$Sound_screen_BackSndTrig_PosX1
#define Sound_screen_BackSndStr_PosX	$Sound_screen_BackSndStr_PosX1
#define Sound_screen_MechSndTrig_PosX	$Sound_screen_MechSndTrig_PosX1
#define Sound_screen_MechSndStr_PosX	$Sound_screen_MechSndStr_PosX1
#define Sound_screen_PanningTrig_PosX	$Sound_screen_PanningTrig_PosX1
#define Sound_screen_PanningStr_PosX	$Sound_screen_PanningStr_PosX1
#define Sound_screen_MusScrlObj_PosX	$Sound_screen_MusScrlObj_PosX1
#define Sound_screen_MusicStr2_PosX	$Sound_screen_MusicStr2_PosX1
#define Sound_screen_SndScrlObj_PosX	$Sound_screen_SndScrlObj_PosX1
#define Sound_screen_SoundStr2_PosX	$Sound_screen_SoundStr2_PosX1
#define Sound_screen_MusicTrig_PosX	$Sound_screen_MusicTrig_PosX1
#define Sound_screen_MusicStr_PosX	$Sound_screen_MusicStr_PosX1
#define Sound_screen_SoundTrig_PosX	$Sound_screen_SoundTrig_PosX1
#define Sound_screen_SoundStr_PosX	$Sound_screen_SoundStr_PosX1

// ------------ Screen: "Server screen" ------------

#define Server_screen_Back_Option_PosX		$Server_screen_Back_Option_PosX1
#define Server_screen_Back_Option_PosY		$Server_screen_Back_Option_PosY1

// ------------ Screen: "Identification screen" ------------

#define Identification_screen_Back_Option_PosX		$Identification_screen_Back_Option_PosX1
#define Identification_screen_Back_Option_PosY		$Identification_screen_Back_Option_PosY1

// ------------ Screen: "Select Game" ------------

#define Select_Game_Back_Option_PosX		$Select_Game_Back_Option_PosX1
#define Select_Game_Back_Option_PosY		$Select_Game_Back_Option_PosY1

// ------------ Screen: "Game Params 0" ------------

#define Game_Params_0_AccessTrig_PosX		$Game_Params_0_AccessTrig_PosX1
#define Game_Params_0_AccessStr_PosX		$Game_Params_0_AccessStr_PosX1
#define Game_Params_0_TeamTrig_PosX		$Game_Params_0_TeamTrig_PosX1
#define Game_Params_0_TeamStr_PosX		$Game_Params_0_TeamStr_PosX1
#define Game_Params_0_EscaveTrig_PosX		$Game_Params_0_EscaveTrig_PosX1
#define Game_Params_0_BirthTrig_PosX		$Game_Params_0_BirthTrig_PosX1
#define Game_Params_0_BirthStr_PosX		$Game_Params_0_BirthStr_PosX1
#define Game_Params_0_EscaveMinStr_PosX 	$Game_Params_0_EscaveMinStr_PosX1
#define Game_Params_0_EscaveTimeStr_PosX	$Game_Params_0_EscaveTimeStr_PosX1
#define Game_Params_0_TimeTrig_PosX		$Game_Params_0_TimeTrig_PosX1
#define Game_Params_0_ArtefactsTrig_PosX	$Game_Params_0_ArtefactsTrig_PosX1
#define Game_Params_0_ArtefactsStr_PosX 	$Game_Params_0_ArtefactsStr_PosX1
#define Game_Params_0_BeebosNumberStr_PosX	$Game_Params_0_BeebosNumberStr_PosX1
#define Game_Params_0_BeebosStr_PosX		$Game_Params_0_BeebosStr_PosX1
#define Game_Params_0_CashStr_PosX		$Game_Params_0_CashStr_PosX1
#define Game_Params_0_Ok_Option_PosX		$Game_Params_0_Ok_Option_PosX1
#define Game_Params_0_Back_Option_PosX		$Game_Params_0_Back_Option_PosX1
#define Game_Params_0_MaxTimeStr_PosX		$Game_Params_0_MaxTimeStr_PosX1
#define Game_Params_0_MaxTimeMinStr_PosX	$Game_Params_0_MaxTimeMinStr_PosX1
#define Game_Params_0_MaxTimeNumberStr_PosX	$Game_Params_0_MaxTimeNumberStr_PosX1
#define Game_Params_0_MaxKillsStr_PosX		$Game_Params_0_MaxKillsStr_PosX1
#define Game_Params_0_MaxKillsNumberStr_PosX	$Game_Params_0_MaxKillsNumberStr_PosX1

// ------------ Screen: "Game Params 1" ------------

#define Game_Params_1_OneTimeNum_PosX		$Game_Params_1_OneTimeNum_PosX1
#define Game_Params_1_OneTimeStr_PosX		$Game_Params_1_OneTimeStr_PosX1
#define Game_Params_1_ItemsNumber2_PosX 	$Game_Params_1_ItemsNumber2_PosX1
#define Game_Params_1_ItemsNumber1_PosX 	$Game_Params_1_ItemsNumber1_PosX1
#define Game_Params_1_ItemStrTrig2_PosX 	$Game_Params_1_ItemStrTrig2_PosX1
#define Game_Params_1_ItemStrTrig1_PosX 	$Game_Params_1_ItemStrTrig1_PosX1
#define Game_Params_1_TeamTrig_PosX		$Game_Params_1_TeamTrig_PosX1
#define Game_Params_1_TeamStr_PosX		$Game_Params_1_TeamStr_PosX1
#define Game_Params_1_WorldTrig_PosX		$Game_Params_1_WorldTrig_PosX1
#define Game_Params_1_WorldStr_PosX		$Game_Params_1_WorldStr_PosX1

// ------------ Screen: "Server Info screen" ------------

#define Server_Info_screen_Game_Option_PosX	$Server_Info_screen_Game_Option_PosX1
#define Server_Info_screen_Chat_Option_PosX	$Server_Info_screen_Chat_Option_PosX1

// ------------ Screen: "Chat screen" ------------

#define Chat_screen_Game_Option_PosX	$Chat_screen_Game_Option_PosX1
#define Chat_screen_Game_Option_PosY	$Chat_screen_Game_Option_PosY1
#define Chat_screen_Server_Option_PosX	$Chat_screen_Server_Option_PosX1
#define Chat_screen_Server_Option_PosY	$Chat_screen_Server_Option_PosY1

// ------------ Screen: "INet Host screen" ------------

#define INet_Host_screen_ProxyPortNumStr_PosX	$INet_Host_screen_ProxyPortNumStr_PosX1
#define INet_Host_screen_ProxyPortStr_PosX	$INet_Host_screen_ProxyPortStr_PosX1
#define INet_Host_screen_ProxyServerNameStr_PosX	$INet_Host_screen_ProxyServerNameStr_PosX1
#define INet_Host_screen_ProxyServerStr_PosX	$INet_Host_screen_ProxyServerStr_PosX1
#define INet_Host_screen_ProxyTrg_PosX	$INet_Host_screen_ProxyTrg_PosX1
#define INet_Host_screen_ProxyStr_PosX	$INet_Host_screen_ProxyStr_PosX1
#define INet_Host_screen_Ok_Option_PosX $INet_Host_screen_Ok_Option_PosX1
#define INet_Host_screen_Back_Option_PosX	$INet_Host_screen_Back_Option_PosX1
#define INet_Host_screen_IP_Str_PosX		$INet_Host_screen_IP_Str_PosX1
#define INet_Host_screen_IP_Addr_PosX		$INet_Host_screen_IP_Addr_PosX1

// ------------ Screen: "Port screen" ------------

#define Port_screen_TitleStr_PosX		$Port_screen_TitleStr_PosX1
#define Port_screen_TitleStr_PosY		$Port_screen_TitleStr_PosY1

#define Port_screen_PortStr_PosX		$Port_screen_PortStr_PosX1
#define Port_screen_PortStr_PosY		$Port_screen_PortStr_PosY1

#define Port_screen_Back_Option_PosX		$Port_screen_Back_Option_PosX1
#define Port_screen_Back_Option_PosY		$Port_screen_Back_Option_PosY1

#define Port_screen_Default_Option_PosX 	$Port_screen_Default_Option_PosX1
#define Port_screen_Default_Option_PosY 	$Port_screen_Default_Option_PosY1

// ------------ Screen: "HallOfFame screen" ------------

#define HallOfFame_screen_Back_Option_PosX	$HallOfFame_screen_Back_Option_PosX1
#define HallOfFame_screen_Back_Option_PosY	$HallOfFame_screen_Back_Option_PosY1

// ------------ Screen: "iSearch server screen" ------------

#define iSearch_server_screen_Back_Option_PosX		$iSearch_server_screen_Back_Option_PosX1
#define iSearch_server_screen_Back_Option_PosY		$iSearch_server_screen_Back_Option_PosY1
#define iSearch_server_screen_Down_Option_PosX		$iSearch_server_screen_Down_Option_PosX1
#define iSearch_server_screen_Down_Option_PosY		$iSearch_server_screen_Down_Option_PosY1
#define iSearch_server_screen_Up_Option_PosX		$iSearch_server_screen_Up_Option_PosX1
#define iSearch_server_screen_Up_Option_PosY		$iSearch_server_screen_Up_Option_PosY1

// ------------ Screen: "Search server screen" ------------

#define Search_server_screen_Down_Option_PosX	$Search_server_screen_Down_Option_PosX1
#define Search_server_screen_Down_Option_PosY	$Search_server_screen_Down_Option_PosY1
#define Search_server_screen_Up_Option_PosX	$Search_server_screen_Up_Option_PosX1
#define Search_server_screen_Up_Option_PosY	$Search_server_screen_Up_Option_PosY1

