
#define KEEP_STR_X	$KEEP_STR_X2
#define KEEP_TRG_X	$KEEP_TRG_X2

#define Graphics_screen_CleanUpObj_PosX 	$Graphics_screen_CleanUpObj_PosX2
#define Graphics_screen_InUseObj_PosX		$Graphics_screen_InUseObj_PosX2

#define EXIT_X		$EXIT_X2
#define EXIT_Y		$EXIT_Y2

#define DESTR_TRG_X	$DESTR_TRG_X2

#define UP_LIST_X	$UP_LIST_X2
#define UP_LIST_Y	$UP_LIST_Y2

#define UPDATE_LIST_X	$UPDATE_LIST_X2
#define UPDATE_LIST_Y	$UPDATE_LIST_Y2

#define DN_LIST_X	$DN_LIST_X2
#define DN_LIST_Y	$DN_LIST_Y2

#define SLIST_BACK_X	$SLIST_BACK_X2
#define SLIST_BACK_Y	$SLIST_BACK_Y2


// ------------ Screen: "Controls screen" ------------

#define Controls_screen_More_Option_PosX	$Controls_screen_More_Option_PosX2
#define Controls_screen_More_Option_PosY	$Controls_screen_More_Option_PosY2

#define Controls_screen_Back_Option_PosX	$Controls_screen_Back_Option_PosX2
#define Controls_screen_Back_Option_PosY	$Controls_screen_Back_Option_PosY2

#define Controls_screen_Defaults_Option_PosX	$Controls_screen_Defaults_Option_PosX2
#define Controls_screen_Defaults_Option_PosY	$Controls_screen_Defaults_Option_PosY2

// ------------ Screen: "Sound screen" ------------

#define Sound_screen_BackSndTrig_PosX	$Sound_screen_BackSndTrig_PosX2
#define Sound_screen_BackSndStr_PosX	$Sound_screen_BackSndStr_PosX2
#define Sound_screen_MechSndTrig_PosX	$Sound_screen_MechSndTrig_PosX2
#define Sound_screen_MechSndStr_PosX	$Sound_screen_MechSndStr_PosX2
#define Sound_screen_PanningTrig_PosX	$Sound_screen_PanningTrig_PosX2
#define Sound_screen_PanningStr_PosX	$Sound_screen_PanningStr_PosX2
#define Sound_screen_MusScrlObj_PosX	$Sound_screen_MusScrlObj_PosX2
#define Sound_screen_MusicStr2_PosX	$Sound_screen_MusicStr2_PosX2
#define Sound_screen_SndScrlObj_PosX	$Sound_screen_SndScrlObj_PosX2
#define Sound_screen_SoundStr2_PosX	$Sound_screen_SoundStr2_PosX2
#define Sound_screen_MusicTrig_PosX	$Sound_screen_MusicTrig_PosX2
#define Sound_screen_MusicStr_PosX	$Sound_screen_MusicStr_PosX2
#define Sound_screen_SoundTrig_PosX	$Sound_screen_SoundTrig_PosX2
#define Sound_screen_SoundStr_PosX	$Sound_screen_SoundStr_PosX2

// ------------ Screen: "Server screen" ------------

#define Server_screen_Back_Option_PosX		$Server_screen_Back_Option_PosX2
#define Server_screen_Back_Option_PosY		$Server_screen_Back_Option_PosY2

// ------------ Screen: "Identification screen" ------------

#define Identification_screen_Back_Option_PosX		$Identification_screen_Back_Option_PosX2
#define Identification_screen_Back_Option_PosY		$Identification_screen_Back_Option_PosY2

// ------------ Screen: "Select Game" ------------

#define Select_Game_Back_Option_PosX		$Select_Game_Back_Option_PosX2
#define Select_Game_Back_Option_PosY		$Select_Game_Back_Option_PosY2

// ------------ Screen: "Game Params 0" ------------

#define Game_Params_0_AccessTrig_PosX		$Game_Params_0_AccessTrig_PosX2
#define Game_Params_0_AccessStr_PosX		$Game_Params_0_AccessStr_PosX2
#define Game_Params_0_TeamTrig_PosX		$Game_Params_0_TeamTrig_PosX2
#define Game_Params_0_TeamStr_PosX		$Game_Params_0_TeamStr_PosX2
#define Game_Params_0_EscaveTrig_PosX		$Game_Params_0_EscaveTrig_PosX2
#define Game_Params_0_BirthTrig_PosX		$Game_Params_0_BirthTrig_PosX2
#define Game_Params_0_BirthStr_PosX		$Game_Params_0_BirthStr_PosX2
#define Game_Params_0_EscaveMinStr_PosX 	$Game_Params_0_EscaveMinStr_PosX2
#define Game_Params_0_EscaveTimeStr_PosX	$Game_Params_0_EscaveTimeStr_PosX2
#define Game_Params_0_TimeTrig_PosX		$Game_Params_0_TimeTrig_PosX2
#define Game_Params_0_ArtefactsTrig_PosX	$Game_Params_0_ArtefactsTrig_PosX2
#define Game_Params_0_ArtefactsStr_PosX 	$Game_Params_0_ArtefactsStr_PosX2
#define Game_Params_0_BeebosNumberStr_PosX	$Game_Params_0_BeebosNumberStr_PosX2
#define Game_Params_0_BeebosStr_PosX		$Game_Params_0_BeebosStr_PosX2
#define Game_Params_0_CashStr_PosX		$Game_Params_0_CashStr_PosX2
#define Game_Params_0_Ok_Option_PosX		$Game_Params_0_Ok_Option_PosX2
#define Game_Params_0_Back_Option_PosX		$Game_Params_0_Back_Option_PosX2
#define Game_Params_0_MaxTimeStr_PosX		$Game_Params_0_MaxTimeStr_PosX2
#define Game_Params_0_MaxTimeMinStr_PosX	$Game_Params_0_MaxTimeMinStr_PosX2
#define Game_Params_0_MaxTimeNumberStr_PosX	$Game_Params_0_MaxTimeNumberStr_PosX2
#define Game_Params_0_MaxKillsStr_PosX		$Game_Params_0_MaxKillsStr_PosX2
#define Game_Params_0_MaxKillsNumberStr_PosX	$Game_Params_0_MaxKillsNumberStr_PosX2

// ------------ Screen: "Game Params 1" ------------

#define Game_Params_1_OneTimeNum_PosX		$Game_Params_1_OneTimeNum_PosX2
#define Game_Params_1_OneTimeStr_PosX		$Game_Params_1_OneTimeStr_PosX2
#define Game_Params_1_ItemsNumber2_PosX 	$Game_Params_1_ItemsNumber2_PosX2
#define Game_Params_1_ItemsNumber1_PosX 	$Game_Params_1_ItemsNumber1_PosX2
#define Game_Params_1_ItemStrTrig2_PosX 	$Game_Params_1_ItemStrTrig2_PosX2
#define Game_Params_1_ItemStrTrig1_PosX 	$Game_Params_1_ItemStrTrig1_PosX2
#define Game_Params_1_TeamTrig_PosX		$Game_Params_1_TeamTrig_PosX2
#define Game_Params_1_TeamStr_PosX		$Game_Params_1_TeamStr_PosX2
#define Game_Params_1_WorldTrig_PosX		$Game_Params_1_WorldTrig_PosX2
#define Game_Params_1_WorldStr_PosX		$Game_Params_1_WorldStr_PosX2

// ------------ Screen: "Server Info screen" ------------

#define Server_Info_screen_Game_Option_PosX	$Server_Info_screen_Game_Option_PosX2
#define Server_Info_screen_Chat_Option_PosX	$Server_Info_screen_Chat_Option_PosX2

// ------------ Screen: "Chat screen" ------------

#define Chat_screen_Game_Option_PosX	$Chat_screen_Game_Option_PosX2
#define Chat_screen_Game_Option_PosY	$Chat_screen_Game_Option_PosY2
#define Chat_screen_Server_Option_PosX	$Chat_screen_Server_Option_PosX2
#define Chat_screen_Server_Option_PosY	$Chat_screen_Server_Option_PosY2

// ------------ Screen: "INet Host screen" ------------

#define INet_Host_screen_ProxyPortNumStr_PosX	$INet_Host_screen_ProxyPortNumStr_PosX2
#define INet_Host_screen_ProxyPortStr_PosX	$INet_Host_screen_ProxyPortStr_PosX2
#define INet_Host_screen_ProxyServerNameStr_PosX	$INet_Host_screen_ProxyServerNameStr_PosX2
#define INet_Host_screen_ProxyServerStr_PosX	$INet_Host_screen_ProxyServerStr_PosX2
#define INet_Host_screen_ProxyTrg_PosX	$INet_Host_screen_ProxyTrg_PosX2
#define INet_Host_screen_ProxyStr_PosX	$INet_Host_screen_ProxyStr_PosX2
#define INet_Host_screen_Ok_Option_PosX $INet_Host_screen_Ok_Option_PosX2
#define INet_Host_screen_Back_Option_PosX	$INet_Host_screen_Back_Option_PosX2
#define INet_Host_screen_IP_Str_PosX		$INet_Host_screen_IP_Str_PosX2
#define INet_Host_screen_IP_Addr_PosX		$INet_Host_screen_IP_Addr_PosX2

// ------------ Screen: "Port screen" ------------

#define Port_screen_TitleStr_PosX		$Port_screen_TitleStr_PosX2
#define Port_screen_TitleStr_PosY		$Port_screen_TitleStr_PosY2

#define Port_screen_PortStr_PosX		$Port_screen_PortStr_PosX2
#define Port_screen_PortStr_PosY		$Port_screen_PortStr_PosY2

#define Port_screen_Back_Option_PosX		$Port_screen_Back_Option_PosX2
#define Port_screen_Back_Option_PosY		$Port_screen_Back_Option_PosY2

#define Port_screen_Default_Option_PosX 	$Port_screen_Default_Option_PosX2
#define Port_screen_Default_Option_PosY 	$Port_screen_Default_Option_PosY2

// ------------ Screen: "HallOfFame screen" ------------

#define HallOfFame_screen_Back_Option_PosX	$HallOfFame_screen_Back_Option_PosX2
#define HallOfFame_screen_Back_Option_PosY	$HallOfFame_screen_Back_Option_PosY2

// ------------ Screen: "iSearch server screen" ------------

#define iSearch_server_screen_Back_Option_PosX		$iSearch_server_screen_Back_Option_PosX2
#define iSearch_server_screen_Back_Option_PosY		$iSearch_server_screen_Back_Option_PosY2
#define iSearch_server_screen_Down_Option_PosX		$iSearch_server_screen_Down_Option_PosX2
#define iSearch_server_screen_Down_Option_PosY		$iSearch_server_screen_Down_Option_PosY2
#define iSearch_server_screen_Up_Option_PosX		$iSearch_server_screen_Up_Option_PosX2
#define iSearch_server_screen_Up_Option_PosY		$iSearch_server_screen_Up_Option_PosY2

// ------------ Screen: "Search server screen" ------------

#define Search_server_screen_Down_Option_PosX	$Search_server_screen_Down_Option_PosX2
#define Search_server_screen_Down_Option_PosY	$Search_server_screen_Down_Option_PosY2
#define Search_server_screen_Up_Option_PosX	$Search_server_screen_Up_Option_PosX2
#define Search_server_screen_Up_Option_PosY	$Search_server_screen_Up_Option_PosY2

