

#define PANELANSW_COORDS	x	101	\
			y	10

#define PANELANSW_SIZE	size_x	580	\
			size_y	100


#define PANELCREDITS_COORDS	x	476	\
			y	16

#define PANELCREDITS_SIZE	size_x	230	\
			size_y	40


#define PANELINFO_COORDS	x	466	\
			y	475

#define PANELINFO_SIZE	size_x	261	\
			size_y	89


#define PANELITEMS_COORDS	x	60	\
			y	145

#define PANELITEMS_SIZE size_x	340	\
			size_y	255


#define PANELPRICE_COORDS	x	119	\
			y	451

#define PANELPRICE_SIZE size_x	223	\
			size_y	138


#define PANELQ_COORDS	x	146	\
			y	510

#define PANELQ_SIZE	size_x	509	\
			size_y	58


#define PANELTM_COORDS	x	682	\
			y	123

#define PANELTM_SIZE	size_x	104	\
			size_y	74

