

#define PANELANSW_COORDS	x	119	\
			y	4

#define PANELANSW_SIZE	size_x	580	\
			size_y	100


#define PANELQ_COORDS	x	121	\
			y	517

#define PANELQ_SIZE	size_x	545	\
			size_y	55


#define PANELTM_COORDS	x	674	\
			y	132

#define PANELTM_SIZE	size_x	104	\
			size_y	74

/*
#define PANELPRICE_COORDS	x	143	\
			y	479

#define PANELPRICE_SIZE size_x	184	\
			size_y	101
*/

#define PANELPRICE_COORDS	x	142	\
			y	476

#define PANELPRICE_SIZE size_x	191	\
			size_y	117

