
#define iSTR_LOAD_GAME		$iSTR_LOAD_GAME1
#define iSTR_MULTIPLAYER	$iSTR_MULTIPLAYER1
#define iSTR_NEW_GAME		$iSTR_NEW_GAME1
#define iSTR_OPTIONS		$iSTR_OPTIONS1
#define iSTR_CREDITS		$iSTR_CREDITS1
#define iSTR_EXIT		$iSTR_EXIT1
#define iSTR_Credits		$iSTR_Credits1
#define iSTR_CreditsSubA		$iSTR_CreditsSubA1
#define iSTR_CreditsSubBA		$iSTR_CreditsSubBA1
#define iSTR_CreditsSubBB		$iSTR_CreditsSubBB1
#define iSTR_CreditsSubCA		$iSTR_CreditsSubCA1
#define iSTR_CreditsSubCB		$iSTR_CreditsSubCB1
#define iSTR_MAIN_MENU		$iSTR_MAIN_MENU1
#define iSTR_HALL_OF_FAME	$iSTR_HALL_OF_FAME1

#define iSTR_Options		$iSTR_Options1
#define iSTR_GRAPHICS		$iSTR_GRAPHICS1
#define iSTR_SOUND		$iSTR_SOUND1
#define iSTR_CONTROLS		$iSTR_CONTROLS1

#define iSTR_Graphics_Options	$iSTR_Graphics_Options1
#define iSTR_DETAIL		$iSTR_DETAIL1
#define iSTR_MEM16MB		$iSTR_MEM16MB1
#define iSTR_MEM32MB		$iSTR_MEM32MB1
#define iSTR_TIPS		$iSTR_TIPS1

#define iSTR_ON 			$iSTR_ON1
#define iSTR_OFF			$iSTR_OFF1
#define iSTR_ENABLED 			$iSTR_ENABLED1
#define iSTR_DISABLED			$iSTR_DISABLED1
#define iSTR_BACK			$iSTR_BACK1
#define iSTR_SCREEN			$iSTR_SCREEN1
#define iSTR_800x600			$iSTR_800x6001
#define iSTR_640x480			$iSTR_640x4801
#define iSTR_DEFORMABLE_LANDSCAPE	$iSTR_DEFORMABLE_LANDSCAPE1
#define iSTR_KEEP_ALL_TERRAIN_CHANGES	$iSTR_KEEP_ALL_TERRAIN_CHANGES1
#define iSTR_FULL_SCREEN	$iSTR_FULL_SCREEN1
#define iSTR_DISK_SPACE_IN_USE		$iSTR_DISK_SPACE_IN_USE1
#define iSTR_CLEAN_UP			$iSTR_CLEAN_UP1

#define iSTR_Sound_Options		$iSTR_Sound_Options1
#define iSTR_SOUND_EFFECTS		$iSTR_SOUND_EFFECTS1
#define iSTR_MUSIC			$iSTR_MUSIC1
#define iSTR_SOUND_VOLUME		$iSTR_SOUND_VOLUME1
#define iSTR_MUSIC_VOLUME		$iSTR_MUSIC_VOLUME1
#define iSTR_EFFECTS_PANNING		$iSTR_EFFECTS_PANNING1
#define iSTR_ENGINE_NOISE		$iSTR_ENGINE_NOISE1
#define iSTR_BACKGROUND_SOUND		$iSTR_BACKGROUND_SOUND1

#define iSTR_Multiplayer		$iSTR_Multiplayer1
#define iSTR_JOIN_SERVER		$iSTR_JOIN_SERVER1
#define iSTR_CREATE_SERVER		$iSTR_CREATE_SERVER1
#define iSTR_PLAYER_SETUP		$iSTR_PLAYER_SETUP1
#define iSTR_Join_Server		$iSTR_Join_Server1

#define iSTR_LAN			$iSTR_LAN1
#define iSTR_INTERNET			$iSTR_INTERNET1
#define iSTR_SERVER_PORT		$iSTR_SERVER_PORT1
#define iSTR_Default			$iSTR_Default1
#define iSTR_Server_Port		$iSTR_Server_Port1
#define iSTR_CANT_CREATE		$iSTR_CANT_CREATE1

#define iSTR_LAN_Servers		$iSTR_LAN_Servers1
#define iSTR_UP 			$iSTR_UP1
#define iSTR_DOWN			$iSTR_DOWN1
#define iSTR_Update_List		$iSTR_Update_List1

#define iSTR_Searching_Servers		$iSTR_Searching_Servers1
#define iSTR_Please_wait		$iSTR_Please_wait1

#define iSTR_Player_Settings		$iSTR_Player_Settings1
#define iSTR_NAME			$iSTR_NAME01
#define iSTR_COLOR			$iSTR_COLOR1
#define iSTR_YELLOW			$iSTR_YELLOW1
#define iSTR_ORANGE			$iSTR_ORANGE1
#define iSTR_BLUE			$iSTR_BLUE1
#define iSTR_GREEN			$iSTR_GREEN1
#define iSTR_RED			$iSTR_RED1
#define iSTR_WHITE			$iSTR_WHITE1
#define iSTR_GRAY			$iSTR_GRAY1
#define iSTR_BLACK			$iSTR_BLACK1
#define iSTR_CAMOUFLAGE			$iSTR_CAMOUFLAGE1
#define iSTR_PATROL			$iSTR_PATROL1

#define iSTR_Connection_failed		$iSTR_Connection_failed1

#define iSTR_OK 			$iSTR_OK1
#define iSTR_CANCEL			$iSTR_CANCEL1

#define iSTR_MORE			$iSTR_MORE1
#define iSTR_Customize_keyboard 	$iSTR_Customize_keyboard1
#define iSTR_RESTORE_ALL		$iSTR_RESTORE_ALL1

#define iSTR_SELECT_GAME		$iSTR_SELECT_GAME1
#define iSTR_Nascency			$iSTR_Nascency1
#define iSTR_Any_World			$iSTR_Any_World1
#define iSTR_Fostral			$iSTR_Fostral1
#define iSTR_Glorx			$iSTR_Glorx1
#define iSTR_Necross			$iSTR_Necross1
#define iSTR_Team_Mode			$iSTR_Team_Mode1
#define iSTR_Access			$iSTR_Access1
#define iSTR_All_Worlds 		$iSTR_All_Worlds1
#define iSTR_One_World			$iSTR_One_World1
#define iSTR_World			$iSTR_World1
#define iSTR_MaxKills			$iSTR_MaxKills1
#define iSTR_MaxTime			$iSTR_MaxTime1

#define iSTR_Nymbos			$iSTR_Nymbos1
#define iSTR_Heroin			$iSTR_Heroin1
#define iSTR_Toxick			$iSTR_Toxick1
#define iSTR_Phlegma			$iSTR_Phlegma1
#define iSTR_Shrub			$iSTR_Shrub1
#define iSTR_Poponka			$iSTR_Poponka1
#define iSTR_One_at_a_time		$iSTR_One_at_a_time1
#define iSTR_Checkpoints_Number 	$iSTR_Checkpoints_Number1

#define iSTR_Unique_Mechos		$iSTR_Unique_Mechos1
#define iSTR_Last_Moggy 		$iSTR_Last_Moggy1
#define iSTR_Queen_Frog 		$iSTR_Queen_Frog1
#define iSTR_Sandoll			$iSTR_Sandoll1
#define iSTR_Lawn_Mower 		$iSTR_Lawn_Mower1
#define iSTR_Wormaster			$iSTR_Wormaster1

#define iSTR_IDENTIFICATION		$iSTR_IDENTIFICATION1
#define iSTR_PASSWORD			$iSTR_PASSWORD1
#define iSTR_DISCONNECT 		$iSTR_DISCONNECT1
#define iSTR_Server_Configuration	$iSTR_Server_Configuration1
#define iSTR_NAME2			$iSTR_NAME21
#define iSTR_GAME			$iSTR_GAME1

#define iSTR_THE_SERVER_HAS_ALREADY	$iSTR_THE_SERVER_HAS_ALREADY1
#define iSTR_BEEN_CONFIGURED_BY 	$iSTR_BEEN_CONFIGURED_BY1
#define iSTR_ANOTHER_PLAYER		$iSTR_ANOTHER_PLAYER1
#define iSTR_Server_Info		$iSTR_Server_Info1
#define iSTR_CHAT			$iSTR_CHAT1
#define iSTR_START			$iSTR_START1

#define iSTR_Chat_Room			$iSTR_Chat_Room1
#define iSTR_SERVER_INFO		$iSTR_SERVER_INFO1

#define iSTR_HOST_NAME			$iSTR_HOST_NAME1
#define iSTR_CurIP			$iSTR_CurIP1
#define iSTR_Internet_Servers		$iSTR_Internet_Servers1

#define iSTR_Game_Results		$iSTR_Game_Results1
#define iSTR_GAME_PARAMETERS		$iSTR_GAME_PARAMETERS1

#define iSTR_Initial_Cash		$iSTR_Initial_Cash1
#define iSTR_beebos			$iSTR_beebos1
#define iSTR_Artefacts_Using		$iSTR_Artefacts_Using1

#define iSTR_YES			$iSTR_YES1
#define iSTR_NO 			$iSTR_NO1

#define iSTR_In_Escave_Time		$iSTR_In_Escave_Time1
#define iSTR_min			$iSTR_min1

#define iSTR_ACHTUNG			$iSTR_ACHTUNG1
#define iSTR_VANGERS_APPROACHING	$iSTR_VANGERS_APPROACHING1

#define iSTR_Genesis			$iSTR_Genesis1
#define iSTR_Prehistory 		$iSTR_Prehistory1
#define iSTR_Present			$iSTR_Present1

#define iSTR_Turn_wheels_left		$iSTR_Turn_wheels_left1
#define iSTR_Turn_wheels_right		$iSTR_Turn_wheels_right1
#define iSTR_Move_forward		$iSTR_Move_forward1
#define iSTR_Move_backward		$iSTR_Move_backward1
#define iSTR_Acceleration		$iSTR_Acceleration1
#define iSTR_Auto_acceleration		$iSTR_Auto_acceleration1
#define iSTR_Handbrake			$iSTR_Handbrake1
#define iSTR_Turn_over_left		$iSTR_Turn_over_left1
#define iSTR_Turn_over_right		$iSTR_Turn_over_right1
#define iSTR_Activate_KiD		$iSTR_Activate_KiD1
#define iSTR_Open			$iSTR_Open1
#define iSTR_Turn_device_ON		$iSTR_Turn_device_ON1
#define iSTR_Turn_device_OFF		$iSTR_Turn_device_OFF1
#define iSTR_Inventory_ON_OFF		$iSTR_Inventory_ON_OFF1
#define iSTR_Change_target		$iSTR_Change_target1
#define iSTR_Fire_all_weapons		$iSTR_Fire_all_weapons1
#define iSTR_Fire_weapon_1		$iSTR_Fire_weapon_11
#define iSTR_Fire_weapon_2		$iSTR_Fire_weapon_21
#define iSTR_Fire_weapon_3		$iSTR_Fire_weapon_31
#define iSTR_Fire_weapon_4		$iSTR_Fire_weapon_41
#define iSTR_Use_Gluek			$iSTR_Use_Gluek1
#define iSTR_Full_screen		$iSTR_Full_screen1
#define iSTR_Reduce_view		$iSTR_Reduce_view1
#define iSTR_Enlarge_view		$iSTR_Enlarge_view1
#define iSTR_Rotation			$iSTR_Rotation1
#define iSTR_Auto_tilt			$iSTR_Auto_tilt1
#define iSTR_Auto_zoom			$iSTR_Auto_zoom1
#define iSTR_Zoom_in			$iSTR_Zoom_in1
#define iSTR_Zoom_out			$iSTR_Zoom_out1
#define iSTR_Standard_zoom		$iSTR_Standard_zoom1
#define iSTR_SkipText			$iSTR_SkipText1
#define iSTR_UseVector			$iSTR_UseVector1
#define iSTR_ChatON			$iSTR_ChatON1
#define iSTR_Statistics 		$iSTR_Statistics1
#define iSTR_ExitGame			$iSTR_ExitGame1
#define iSTR_Screenshot			$iSTR_Screenshot1

#define iSTR_VAN_WAR			$iSTR_VAN_WAR1
#define iSTR_MECHOSOMA			$iSTR_MECHOSOMA1
#define iSTR_PASSEMBLOSS		$iSTR_PASSEMBLOSS1
#define iSTR_HUNTAGE			$iSTR_HUNTAGE1
#define iSTR_MUSTODONT			$iSTR_MUSTODONT1

#define BT00_TEXT	$BT00_TEXT1
#define BT01_TEXT	$BT01_TEXT1
#define BT02_TEXT	$BT02_TEXT1
#define BT03_TEXT	$BT03_TEXT1
#define BT04_TEXT	$BT04_TEXT1
#define BT05_TEXT	$BT05_TEXT1
#define BT06_TEXT	$BT06_TEXT1
#define BT07_TEXT	$BT07_TEXT1
#define BT08_TEXT	$BT08_TEXT1
#define BT09_TEXT	$BT09_TEXT1
#define BT10_TEXT	$BT10_TEXT1
#define BT11_TEXT	$BT11_TEXT1
#define BT12_TEXT	$BT12_TEXT1
#define BT13_TEXT	$BT13_TEXT1
#define BT14_TEXT	$BT14_TEXT1
#define BT15_TEXT	$BT15_TEXT1
#define AVI_TEXT	$AVI_TEXT1

#define iSTR_Controls		$iSTR_Controls1
#define iSTR_Movement		$iSTR_Movement1
#define iSTR_Utility		$iSTR_Utility1
#define iSTR_Combat		$iSTR_Combat1
#define iSTR_Camera		$iSTR_Camera1
#define iSTR_MultiplayerAndMisc		$iSTR_MultiplayerAndMisc1
#define iSTR_TO_MENU		$iSTR_TO_MENU1

#define iSTR_JOYSTICK_SETUP		$iSTR_JOYSTICK_SETUP1
#define iSTR_CUSTOMIZE			$iSTR_CUSTOMIZE1
#define iSTR_JoystickSetup		$iSTR_JoystickSetup1
#define iSTR_JoystickType		$iSTR_JoystickType1
#define iSTR_NONE			$iSTR_NONE1
#define iSTR_JoystickGamePad		$iSTR_JoystickGamePad1
#define iSTR_JoystickJoystick		$iSTR_JoystickJoystick1
#define iSTR_JoystickSteeringWheel	$iSTR_JoystickSteeringWheel1
#define iSTR_JoystickAlternFnc		$iSTR_JoystickAlternFnc1
#define iSTR_JoystickBUTTON1		$iSTR_JoystickBUTTON11
#define iSTR_JoystickBUTTON2		$iSTR_JoystickBUTTON21
#define iSTR_JoystickBUTTON3		$iSTR_JoystickBUTTON31
#define iSTR_JoystickBUTTON4		$iSTR_JoystickBUTTON41
#define iSTR_JoystickBUTTON5		$iSTR_JoystickBUTTON51
#define iSTR_JoystickBUTTON6		$iSTR_JoystickBUTTON61
#define iSTR_JoystickBUTTON7		$iSTR_JoystickBUTTON71
#define iSTR_JoystickBUTTON8		$iSTR_JoystickBUTTON81

#define iSTR_SOCKS5_Proxy		$iSTR_SOCKS5_Proxy1
#define iSTR_SOCKS5_ProxyServer 	$iSTR_SOCKS5_ProxyServer1
#define iSTR_SOCKS5_ProxyPort		$iSTR_SOCKS5_ProxyPort1

#define iSTR_GameInfo			$iSTR_GameInfo1

#define iSTR_CreditsPathA		$iSTR_CreditsPathA1
#define iSTR_CreditsPathB		$iSTR_CreditsPathB1
#define iSTR_CreditsPathCA		$iSTR_CreditsPathCA1
#define iSTR_CreditsPathCB		$iSTR_CreditsPathCB1
#define iSTR_CreditsPathDA		$iSTR_CreditsPathDA1
#define iSTR_CreditsPathDB		$iSTR_CreditsPathDB1
#define iSTR_CreditsPathEA		$iSTR_CreditsPathEA1
#define iSTR_CreditsPathEB		$iSTR_CreditsPathEB1
#define iSTR_CreditsPathF		$iSTR_CreditsPathF1
#define iSTR_CreditsPathG		$iSTR_CreditsPathG1
#define iSTR_CreditsPathH		$iSTR_CreditsPathH1
#define iSTR_CreditsPathIA		$iSTR_CreditsPathIA1
#define iSTR_CreditsPathIB		$iSTR_CreditsPathIB1

