
#define iSTR_LOAD_GAME		$iSTR_LOAD_GAME2
#define iSTR_MULTIPLAYER	$iSTR_MULTIPLAYER2
#define iSTR_NEW_GAME		$iSTR_NEW_GAME2
#define iSTR_OPTIONS		$iSTR_OPTIONS2
#define iSTR_CREDITS		$iSTR_CREDITS2
#define iSTR_EXIT		$iSTR_EXIT2
#define iSTR_Credits		$iSTR_Credits2
#define iSTR_CreditsSubA		$iSTR_CreditsSubA2
#define iSTR_CreditsSubBA		$iSTR_CreditsSubBA2
#define iSTR_CreditsSubBB		$iSTR_CreditsSubBB2
#define iSTR_CreditsSubCA		$iSTR_CreditsSubCA2
#define iSTR_CreditsSubCB		$iSTR_CreditsSubCB2
#define iSTR_MAIN_MENU		$iSTR_MAIN_MENU2
#define iSTR_HALL_OF_FAME	$iSTR_HALL_OF_FAME2

#define iSTR_Options		$iSTR_Options2
#define iSTR_GRAPHICS		$iSTR_GRAPHICS2
#define iSTR_SOUND		$iSTR_SOUND2
#define iSTR_CONTROLS		$iSTR_CONTROLS2

#define iSTR_Graphics_Options	$iSTR_Graphics_Options2
#define iSTR_DETAIL		$iSTR_DETAIL2
#define iSTR_MEM16MB		$iSTR_MEM16MB2
#define iSTR_MEM32MB		$iSTR_MEM32MB2
#define iSTR_TIPS		$iSTR_TIPS2

#define iSTR_ON 			$iSTR_ON2
#define iSTR_OFF			$iSTR_OFF2
#define iSTR_ENABLED 			$iSTR_ENABLED2
#define iSTR_DISABLED			$iSTR_DISABLED2
#define iSTR_BACK			$iSTR_BACK2
#define iSTR_SCREEN			$iSTR_SCREEN2
#define iSTR_800x600			$iSTR_800x6002
#define iSTR_640x480			$iSTR_640x4802
#define iSTR_DEFORMABLE_LANDSCAPE	$iSTR_DEFORMABLE_LANDSCAPE2
#define iSTR_KEEP_ALL_TERRAIN_CHANGES	$iSTR_KEEP_ALL_TERRAIN_CHANGES2
#define iSTR_FULL_SCREEN	$iSTR_FULL_SCREEN2
#define iSTR_DISK_SPACE_IN_USE		$iSTR_DISK_SPACE_IN_USE2
#define iSTR_CLEAN_UP			$iSTR_CLEAN_UP2

#define iSTR_Sound_Options		$iSTR_Sound_Options2
#define iSTR_SOUND_EFFECTS		$iSTR_SOUND_EFFECTS2
#define iSTR_MUSIC			$iSTR_MUSIC2
#define iSTR_SOUND_VOLUME		$iSTR_SOUND_VOLUME2
#define iSTR_MUSIC_VOLUME		$iSTR_MUSIC_VOLUME2
#define iSTR_EFFECTS_PANNING		$iSTR_EFFECTS_PANNING2
#define iSTR_ENGINE_NOISE		$iSTR_ENGINE_NOISE2
#define iSTR_BACKGROUND_SOUND		$iSTR_BACKGROUND_SOUND2

#define iSTR_Multiplayer		$iSTR_Multiplayer2
#define iSTR_JOIN_SERVER		$iSTR_JOIN_SERVER2
#define iSTR_CREATE_SERVER		$iSTR_CREATE_SERVER2
#define iSTR_PLAYER_SETUP		$iSTR_PLAYER_SETUP2
#define iSTR_Join_Server		$iSTR_Join_Server2

#define iSTR_LAN			$iSTR_LAN2
#define iSTR_INTERNET			$iSTR_INTERNET2
#define iSTR_SERVER_PORT		$iSTR_SERVER_PORT2
#define iSTR_Default			$iSTR_Default2
#define iSTR_Server_Port		$iSTR_Server_Port2
#define iSTR_CANT_CREATE		$iSTR_CANT_CREATE2

#define iSTR_LAN_Servers		$iSTR_LAN_Servers2
#define iSTR_UP 			$iSTR_UP2
#define iSTR_DOWN			$iSTR_DOWN2
#define iSTR_Update_List		$iSTR_Update_List2

#define iSTR_Searching_Servers		$iSTR_Searching_Servers2
#define iSTR_Please_wait		$iSTR_Please_wait2

#define iSTR_Player_Settings		$iSTR_Player_Settings2
#define iSTR_NAME			$iSTR_NAME02
#define iSTR_COLOR			$iSTR_COLOR2
#define iSTR_YELLOW			$iSTR_YELLOW2
#define iSTR_ORANGE			$iSTR_ORANGE2
#define iSTR_BLUE			$iSTR_BLUE2
#define iSTR_GREEN			$iSTR_GREEN2
#define iSTR_RED			$iSTR_RED2
#define iSTR_WHITE			$iSTR_WHITE2
#define iSTR_GRAY			$iSTR_GRAY2
#define iSTR_BLACK			$iSTR_BLACK2
#define iSTR_CAMOUFLAGE			$iSTR_CAMOUFLAGE2
#define iSTR_PATROL			$iSTR_PATROL2

#define iSTR_Connection_failed		$iSTR_Connection_failed2

#define iSTR_OK 			$iSTR_OK2
#define iSTR_CANCEL			$iSTR_CANCEL2

#define iSTR_MORE			$iSTR_MORE2
#define iSTR_Customize_keyboard 	$iSTR_Customize_keyboard2
#define iSTR_RESTORE_ALL		$iSTR_RESTORE_ALL2

#define iSTR_SELECT_GAME		$iSTR_SELECT_GAME2
#define iSTR_Nascency			$iSTR_Nascency2
#define iSTR_Any_World			$iSTR_Any_World2
#define iSTR_Fostral			$iSTR_Fostral2
#define iSTR_Glorx			$iSTR_Glorx2
#define iSTR_Necross			$iSTR_Necross2
#define iSTR_Team_Mode			$iSTR_Team_Mode2
#define iSTR_Access			$iSTR_Access2
#define iSTR_All_Worlds 		$iSTR_All_Worlds2
#define iSTR_One_World			$iSTR_One_World2
#define iSTR_World			$iSTR_World2
#define iSTR_MaxKills			$iSTR_MaxKills2
#define iSTR_MaxTime			$iSTR_MaxTime2

#define iSTR_Nymbos			$iSTR_Nymbos2
#define iSTR_Heroin			$iSTR_Heroin2
#define iSTR_Toxick			$iSTR_Toxick2
#define iSTR_Phlegma			$iSTR_Phlegma2
#define iSTR_Shrub			$iSTR_Shrub2
#define iSTR_Poponka			$iSTR_Poponka2
#define iSTR_One_at_a_time		$iSTR_One_at_a_time2
#define iSTR_Checkpoints_Number 	$iSTR_Checkpoints_Number2

#define iSTR_Unique_Mechos		$iSTR_Unique_Mechos2
#define iSTR_Last_Moggy 		$iSTR_Last_Moggy2
#define iSTR_Queen_Frog 		$iSTR_Queen_Frog2
#define iSTR_Sandoll			$iSTR_Sandoll2
#define iSTR_Lawn_Mower 		$iSTR_Lawn_Mower2
#define iSTR_Wormaster			$iSTR_Wormaster2

#define iSTR_IDENTIFICATION		$iSTR_IDENTIFICATION2
#define iSTR_PASSWORD			$iSTR_PASSWORD2
#define iSTR_DISCONNECT 		$iSTR_DISCONNECT2
#define iSTR_Server_Configuration	$iSTR_Server_Configuration2
#define iSTR_NAME2			$iSTR_NAME22
#define iSTR_GAME			$iSTR_GAME2

#define iSTR_THE_SERVER_HAS_ALREADY	$iSTR_THE_SERVER_HAS_ALREADY2
#define iSTR_BEEN_CONFIGURED_BY 	$iSTR_BEEN_CONFIGURED_BY2
#define iSTR_ANOTHER_PLAYER		$iSTR_ANOTHER_PLAYER2
#define iSTR_Server_Info		$iSTR_Server_Info2
#define iSTR_CHAT			$iSTR_CHAT2
#define iSTR_START			$iSTR_START2

#define iSTR_Chat_Room			$iSTR_Chat_Room2
#define iSTR_SERVER_INFO		$iSTR_SERVER_INFO2

#define iSTR_HOST_NAME			$iSTR_HOST_NAME2
#define iSTR_CurIP			$iSTR_CurIP2
#define iSTR_Internet_Servers		$iSTR_Internet_Servers2

#define iSTR_Game_Results		$iSTR_Game_Results2
#define iSTR_GAME_PARAMETERS		$iSTR_GAME_PARAMETERS2

#define iSTR_Initial_Cash		$iSTR_Initial_Cash2
#define iSTR_beebos			$iSTR_beebos2
#define iSTR_Artefacts_Using		$iSTR_Artefacts_Using2

#define iSTR_YES			$iSTR_YES2
#define iSTR_NO 			$iSTR_NO2

#define iSTR_In_Escave_Time		$iSTR_In_Escave_Time2
#define iSTR_min			$iSTR_min2

#define iSTR_ACHTUNG			$iSTR_ACHTUNG2
#define iSTR_VANGERS_APPROACHING	$iSTR_VANGERS_APPROACHING2

#define iSTR_Genesis			$iSTR_Genesis2
#define iSTR_Prehistory 		$iSTR_Prehistory2
#define iSTR_Present			$iSTR_Present2

#define iSTR_Turn_wheels_left		$iSTR_Turn_wheels_left2
#define iSTR_Turn_wheels_right		$iSTR_Turn_wheels_right2
#define iSTR_Move_forward		$iSTR_Move_forward2
#define iSTR_Move_backward		$iSTR_Move_backward2
#define iSTR_Acceleration		$iSTR_Acceleration2
#define iSTR_Auto_acceleration		$iSTR_Auto_acceleration2
#define iSTR_Handbrake			$iSTR_Handbrake2
#define iSTR_Turn_over_left		$iSTR_Turn_over_left2
#define iSTR_Turn_over_right		$iSTR_Turn_over_right2
#define iSTR_Activate_KiD		$iSTR_Activate_KiD2
#define iSTR_Open			$iSTR_Open2
#define iSTR_Turn_device_ON		$iSTR_Turn_device_ON2
#define iSTR_Turn_device_OFF		$iSTR_Turn_device_OFF2
#define iSTR_Inventory_ON_OFF		$iSTR_Inventory_ON_OFF2
#define iSTR_Change_target		$iSTR_Change_target2
#define iSTR_Fire_all_weapons		$iSTR_Fire_all_weapons2
#define iSTR_Fire_weapon_1		$iSTR_Fire_weapon_12
#define iSTR_Fire_weapon_2		$iSTR_Fire_weapon_22
#define iSTR_Fire_weapon_3		$iSTR_Fire_weapon_32
#define iSTR_Fire_weapon_4		$iSTR_Fire_weapon_42
#define iSTR_Use_Gluek			$iSTR_Use_Gluek2
#define iSTR_Full_screen		$iSTR_Full_screen2
#define iSTR_Reduce_view		$iSTR_Reduce_view2
#define iSTR_Enlarge_view		$iSTR_Enlarge_view2
#define iSTR_Rotation			$iSTR_Rotation2
#define iSTR_Auto_tilt			$iSTR_Auto_tilt2
#define iSTR_Auto_zoom			$iSTR_Auto_zoom2
#define iSTR_Zoom_in			$iSTR_Zoom_in2
#define iSTR_Zoom_out			$iSTR_Zoom_out2
#define iSTR_Standard_zoom		$iSTR_Standard_zoom2
#define iSTR_SkipText			$iSTR_SkipText2
#define iSTR_UseVector			$iSTR_UseVector2
#define iSTR_ChatON			$iSTR_ChatON2
#define iSTR_Statistics 		$iSTR_Statistics2
#define iSTR_ExitGame			$iSTR_ExitGame2
#define iSTR_Screenshot			$iSTR_Screenshot2

#define iSTR_VAN_WAR			$iSTR_VAN_WAR2
#define iSTR_MECHOSOMA			$iSTR_MECHOSOMA2
#define iSTR_PASSEMBLOSS		$iSTR_PASSEMBLOSS2
#define iSTR_HUNTAGE			$iSTR_HUNTAGE2
#define iSTR_MUSTODONT			$iSTR_MUSTODONT2

#define BT00_TEXT	$BT00_TEXT2
#define BT01_TEXT	$BT01_TEXT2
#define BT02_TEXT	$BT02_TEXT2
#define BT03_TEXT	$BT03_TEXT2
#define BT04_TEXT	$BT04_TEXT2
#define BT05_TEXT	$BT05_TEXT2
#define BT06_TEXT	$BT06_TEXT2
#define BT07_TEXT	$BT07_TEXT2
#define BT08_TEXT	$BT08_TEXT2
#define BT09_TEXT	$BT09_TEXT2
#define BT10_TEXT	$BT10_TEXT2
#define BT11_TEXT	$BT11_TEXT2
#define BT12_TEXT	$BT12_TEXT2
#define BT13_TEXT	$BT13_TEXT2
#define BT14_TEXT	$BT14_TEXT2
#define BT15_TEXT	$BT15_TEXT2
#define AVI_TEXT	$AVI_TEXT2

#define iSTR_Controls		$iSTR_Controls2
#define iSTR_Movement		$iSTR_Movement2
#define iSTR_Utility		$iSTR_Utility2
#define iSTR_Combat		$iSTR_Combat2
#define iSTR_Camera		$iSTR_Camera2
#define iSTR_MultiplayerAndMisc		$iSTR_MultiplayerAndMisc2
#define iSTR_TO_MENU		$iSTR_TO_MENU2

#define iSTR_JOYSTICK_SETUP		$iSTR_JOYSTICK_SETUP2
#define iSTR_CUSTOMIZE			$iSTR_CUSTOMIZE2
#define iSTR_JoystickSetup		$iSTR_JoystickSetup2
#define iSTR_JoystickType		$iSTR_JoystickType2
#define iSTR_NONE			$iSTR_NONE2
#define iSTR_JoystickGamePad		$iSTR_JoystickGamePad2
#define iSTR_JoystickJoystick		$iSTR_JoystickJoystick2
#define iSTR_JoystickSteeringWheel	$iSTR_JoystickSteeringWheel2
#define iSTR_JoystickAlternFnc		$iSTR_JoystickAlternFnc2
#define iSTR_JoystickBUTTON1		$iSTR_JoystickBUTTON12
#define iSTR_JoystickBUTTON2		$iSTR_JoystickBUTTON22
#define iSTR_JoystickBUTTON3		$iSTR_JoystickBUTTON32
#define iSTR_JoystickBUTTON4		$iSTR_JoystickBUTTON42
#define iSTR_JoystickBUTTON5		$iSTR_JoystickBUTTON52
#define iSTR_JoystickBUTTON6		$iSTR_JoystickBUTTON62
#define iSTR_JoystickBUTTON7		$iSTR_JoystickBUTTON72
#define iSTR_JoystickBUTTON8		$iSTR_JoystickBUTTON82

#define iSTR_SOCKS5_Proxy		$iSTR_SOCKS5_Proxy2
#define iSTR_SOCKS5_ProxyServer 	$iSTR_SOCKS5_ProxyServer2
#define iSTR_SOCKS5_ProxyPort		$iSTR_SOCKS5_ProxyPort2

#define iSTR_GameInfo			$iSTR_GameInfo2

#define iSTR_CreditsPathA		$iSTR_CreditsPathA2
#define iSTR_CreditsPathB		$iSTR_CreditsPathB2
#define iSTR_CreditsPathCA		$iSTR_CreditsPathCA2
#define iSTR_CreditsPathCB		$iSTR_CreditsPathCB2
#define iSTR_CreditsPathDA		$iSTR_CreditsPathDA2
#define iSTR_CreditsPathDB		$iSTR_CreditsPathDB2
#define iSTR_CreditsPathEA		$iSTR_CreditsPathEA2
#define iSTR_CreditsPathEB		$iSTR_CreditsPathEB2
#define iSTR_CreditsPathF		$iSTR_CreditsPathF2
#define iSTR_CreditsPathG		$iSTR_CreditsPathG2
#define iSTR_CreditsPathH		$iSTR_CreditsPathH2
#define iSTR_CreditsPathIA		$iSTR_CreditsPathIA2
#define iSTR_CreditsPathIB		$iSTR_CreditsPathIB2

