// Please refer to the remarks I've made (seperated by a double-slash //)

/*
	iScreen string defines

	English Version:
	#define <SOMEWORD>1	"..."

	Local Version:
	#define <SOMEWORD>2	"..."
*/

#define iSTR_LOAD_GAME1 		"LOAD GAME"
#define iSTR_LOAD_GAME2 		"ПРОДОЛЖИТЬ ИГРУ"

#define iSTR_MULTIPLAYER1		"MULTIPLAYER"
#define iSTR_MULTIPLAYER2		"СЕТЕВАЯ ИГРА"

#define iSTR_NEW_GAME1			"NEW GAME"
#define iSTR_NEW_GAME2			"НОВАЯ ИГРА"

#define iSTR_OPTIONS1			"OPTIONS"
#define iSTR_OPTIONS2			"НАСТРОЙКИ"

#define iSTR_CREDITS1			"CREDITS"
#define iSTR_CREDITS2			"АВТОРЫ"

#define iSTR_EXIT1			"EXIT"
#define iSTR_EXIT2			"ВЫХОД"

#define iSTR_Credits1			"Credits"
#define iSTR_Credits2			"О создателях"

#define iSTR_MAIN_MENU1 		"MAIN MENU"
#define iSTR_MAIN_MENU2 		"ГЛАВНОЕ МЕНЮ"

#define iSTR_HALL_OF_FAME1		"HALL OF FAME"
#define iSTR_HALL_OF_FAME2		"ТАБЛИЦА РЕКОРДОВ"

#define iSTR_Options1			"Options"
#define iSTR_Options2			"Настройки"

#define iSTR_GRAPHICS1			"GRAPHICS"
#define iSTR_GRAPHICS2			"ГРАФИКА"

#define iSTR_SOUND1			"SOUND"
#define iSTR_SOUND2			"ЗВУК"

#define iSTR_CONTROLS1			"CONTROLS"
#define iSTR_CONTROLS2			"УПРАВЛЕНИЕ"


#define iSTR_Graphics_Options1		"Graphics Options"
#define iSTR_Graphics_Options2		"Настройка графики"

#define iSTR_DETAIL1			"MEMORY:"
#define iSTR_DETAIL2			"ПАМЯТЬ:"

#define iSTR_MEM16MB1			"GOOD-16MB"
#define iSTR_MEM16MB2			"ХОРОШО - 16 MB"

#define iSTR_MEM32MB1			"EXCELLENT-32MB"
#define iSTR_MEM32MB2			"ОТЛИЧНО - 32 MB"

#define iSTR_TIPS1			"TIPS:"
#define iSTR_TIPS2			"ПОДСКАЗКИ:"

#define iSTR_ON1			"ON"
#define iSTR_ON2			"ДА"

#define iSTR_OFF1			"OFF"
#define iSTR_OFF2			"НЕТ"

#define iSTR_BACK1			"BACK"
#define iSTR_BACK2			"НАЗАД"

#define iSTR_SCREEN1			"SCREEN:"
#define iSTR_SCREEN2			"ЭКРАН:"

#define iSTR_800x6001			"800x600"
#define iSTR_800x6002			"800x600"

#define iSTR_640x4801			"640x480"
#define iSTR_640x4802			"640x480"

#define iSTR_DEFORMABLE_LANDSCAPE1	"DEFORMABLE LANDSCAPE:"
#define iSTR_DEFORMABLE_LANDSCAPE2	"ИЗМЕНЯЕМЫЙ ЛАНДШАФТ:"

#define iSTR_KEEP_ALL_TERRAIN_CHANGES1	"KEEP ALL TERRAIN CHANGES:"
#define iSTR_KEEP_ALL_TERRAIN_CHANGES2	"СОХРАНЯТЬ ЛАНДШАФТ:"

#define iSTR_FULL_SCREEN1	"FULL SCREEN:"
#define iSTR_FULL_SCREEN2	"ПОЛНЫЙ ЭКРАН:"

#define iSTR_DISK_SPACE_IN_USE1 	"DISK SPACE IN USE: 100 MB"
#define iSTR_DISK_SPACE_IN_USE2 	"МЕСТА НА ДИСКЕ: 100 MB"

#define iSTR_CLEAN_UP1			"CLEAN UP!"
#define iSTR_CLEAN_UP2			"ОСВОБОДИТЬ!"


#define iSTR_Sound_Options1		"Sound Options"
#define iSTR_Sound_Options2		"Настройка звука"

#define iSTR_SOUND_EFFECTS1		"SOUND EFFECTS"
#define iSTR_SOUND_EFFECTS2		"ЗВУКОВЫЕ ЭФФЕКТЫ"

#define iSTR_MUSIC1			"MUSIC"
#define iSTR_MUSIC2			"МУЗЫКА"

#define iSTR_SOUND_VOLUME1		"SOUND VOLUME"
#define iSTR_SOUND_VOLUME2		"ГРОМКОСТЬ ЗВУКА"

#define iSTR_MUSIC_VOLUME1		"MUSIC VOLUME"
#define iSTR_MUSIC_VOLUME2		"ГРОМКОСТЬ МУЗЫКИ"

#define iSTR_EFFECTS_PANNING1		"EFFECTS PANNING"
#define iSTR_EFFECTS_PANNING2		"ЭФФЕКТ ПАНОРАМЫ"

#define iSTR_ENGINE_NOISE1		"ENGINE NOISE"
#define iSTR_ENGINE_NOISE2		"РАБОТА ДВИГАТЕЛЯ"

#define iSTR_BACKGROUND_SOUND1		"BACKGROUND SOUND"
#define iSTR_BACKGROUND_SOUND2		"ФОНОВЫЕ ЗВУКИ"

#define iSTR_Controls1			"Controls"
#define iSTR_Controls2			"Управление"

#define iSTR_Multiplayer1		"Multiplayer"
#define iSTR_Multiplayer2		"Сетевая игра"

#define iSTR_JOIN_SERVER1		"JOIN SERVER"
#define iSTR_JOIN_SERVER2		"НАЙТИ СЕРВЕР"

#define iSTR_CREATE_SERVER1		"CREATE SERVER"
#define iSTR_CREATE_SERVER2		"СОЗДАТЬ СЕРВЕР"

#define iSTR_PLAYER_SETUP1		"PLAYER SETUP"
#define iSTR_PLAYER_SETUP2		"НАСТРОИТЬ ИГРОКА"

#define iSTR_SERVER_PORT1		"SET SERVER PORT"
#define iSTR_SERVER_PORT2		"ПОРТ СЕРВЕРА"

#define iSTR_Default1			"RESTORE"
#define iSTR_Default2			"ВОСТАНОВИТЬ"

#define iSTR_Server_Port1		"Server Port:"
#define iSTR_Server_Port2		"Порт сервера:"

#define iSTR_Join_Server1		"Join Server"
#define iSTR_Join_Server2		"Где искать сервер?"


#define iSTR_LAN1			"LAN"
#define iSTR_LAN2			"ЛОКАЛЬНАЯ СЕТЬ"

#define iSTR_INTERNET1			"INTERNET"
#define iSTR_INTERNET2			"ИНТЕРНЕТ"

#define iSTR_CANT_CREATE1		"Can't create server..."
#define iSTR_CANT_CREATE2		"Невозможно создать сервер..."


#define iSTR_LAN_Servers1		"LAN Servers"
#define iSTR_LAN_Servers2		"Локальные сервера"

#define iSTR_UP1			"UP"
#define iSTR_UP2			"ВВЕРХ"

#define iSTR_DOWN1			"DOWN"
#define iSTR_DOWN2			"ВНИЗ"

#define iSTR_Update_List1		"Update List"
#define iSTR_Update_List2		"Обновить Список"

#define iSTR_Searching_Servers1 	"Searching Servers"
#define iSTR_Searching_Servers2 	"Поиск Серверов"

#define iSTR_Please_wait1		"Please wait"
#define iSTR_Please_wait2		"Ждите"


#define iSTR_Player_Settings1		"Player Settings"
#define iSTR_Player_Settings2		"Настройки Игрока"

#define iSTR_NAME01			"NAME"
#define iSTR_NAME02			"ИМЯ"

#define iSTR_COLOR1			"COLOR"
#define iSTR_COLOR2			"ЦВЕТ"

#define iSTR_YELLOW1			"YELLOW"
#define iSTR_YELLOW2			"ЖЁЛТЫЙ"

#define iSTR_ORANGE1			"ORANGE"
#define iSTR_ORANGE2			"ОРАНЖЕВЫЙ"

#define iSTR_BLUE1			"BLUE"
#define iSTR_BLUE2			"СИНИЙ"

#define iSTR_GREEN1			"GREEN"
#define iSTR_GREEN2			"ЗЕЛЕНЫЙ"


#define iSTR_Connection_failed1 	"Connection failed"
#define iSTR_Connection_failed2 	"Сбой подключения"

#define iSTR_OK1			"OK"
#define iSTR_OK2			"ОК"

#define iSTR_CANCEL1			"CANCEL"
#define iSTR_CANCEL2			"ОТМЕНА"

#define iSTR_MORE1			"MORE"
#define iSTR_MORE2			"ДАЛЬШЕ"

#define iSTR_Customize_keyboard1	"Customize keyboard"
#define iSTR_Customize_keyboard2	"Подстройка клавиш"

#define iSTR_RESTORE_ALL1		"RESTORE ALL"
#define iSTR_RESTORE_ALL2		"ВОССТАНОВИТЬ ВСЕ"


#define iSTR_SELECT_GAME1		"SELECT GAME"
#define iSTR_SELECT_GAME2		"Список Доступных Игр"

#define iSTR_Nascency1			"Nascency:"
#define iSTR_Nascency2			"Рождение:"             // whats that? An artificial word -
								// cloned from nasty...? Difficulty?
								// if yes, please use: 'Schwierigkeit'

#define iSTR_Any_World1 		"Any World"
#define iSTR_Any_World2 		"Любой мир"

#define iSTR_Fostral1			"Fostral"
#define iSTR_Fostral2			"Фострал"

#define iSTR_Glorx1			"Glorx"
#define iSTR_Glorx2			"Глоркс"

#define iSTR_Necross1			"Necross"
#define iSTR_Necross2			"Некросс"

#define iSTR_Team_Mode1 		"Team Mode:"
#define iSTR_Team_Mode2 		"Командная Игра:"

#define iSTR_Access1			"Access:"
#define iSTR_Access2			"Доступ:"

#define iSTR_All_Worlds1		"All Worlds"
#define iSTR_All_Worlds2		"Все Миры"

#define iSTR_One_World1 		"One World"
#define iSTR_One_World2 		"Один Мир"

#define iSTR_World1			"World:"
#define iSTR_World2			"Мир:"

#define iSTR_Nymbos1			"Nymbos"
#define iSTR_Nymbos2			"Нимбос"

#define iSTR_Heroin1			"Heroin"
#define iSTR_Heroin2			"Героин"

#define iSTR_Toxick1			"Toxick"
#define iSTR_Toxick2			"Токсик"

#define iSTR_Phlegma1			"Phlegma"
#define iSTR_Phlegma2			"Флегма"

#define iSTR_Shrub1			"Shrub"
#define iSTR_Shrub2			"Куст"

#define iSTR_Poponka1			"Poponka"
#define iSTR_Poponka2			"Попонка"

#define iSTR_One_at_a_time1		"One at a time:"
#define iSTR_One_at_a_time2		"Сколько штук за раз:"

#define iSTR_Checkpoints_Number1	"Checkpoints Number:"
#define iSTR_Checkpoints_Number2	"Число этапов:"

#define iSTR_Unique_Mechos1		"Unique Mechos:"
#define iSTR_Unique_Mechos2		"Уникальные Мехосы:"

#define iSTR_Last_Moggy1		"Last Moggy"
#define iSTR_Last_Moggy2		"Последний из Могикан"

#define iSTR_Queen_Frog1		"Queen Frog"
#define iSTR_Queen_Frog2		"Жаба"

#define iSTR_Sandoll1			"Sandoll"
#define iSTR_Sandoll2			"Песколаз"

#define iSTR_Lawn_Mower1		"Lawn Mower"
#define iSTR_Lawn_Mower2		"Винтокрыл"

#define iSTR_Wormaster1 		"Wormaster"
#define iSTR_Wormaster2 		"Червонец"


#define iSTR_IDENTIFICATION1		"IDENTIFICATION"
#define iSTR_IDENTIFICATION2		"ИНДЕНТИФИКАЦИЯ"

#define iSTR_PASSWORD1			"PASSWORD"
#define iSTR_PASSWORD2			"ПАРОЛЬ"

#define iSTR_DISCONNECT1		"DISCONNECT"
#define iSTR_DISCONNECT2		"ОТСОЕДИНИТЬСЯ"

#define iSTR_Server_Configuration1	"Server Configuration"
#define iSTR_Server_Configuration2	"Конфигурация Сервера"

#define iSTR_NAME21			"NAME:"
#define iSTR_NAME22			"ИМЯ:"

#define iSTR_GAME1			"GAME:"
#define iSTR_GAME2			"ИГРА:"


#define iSTR_THE_SERVER_HAS_ALREADY1	"THE SERVER HAS ALREADY"
#define iSTR_THE_SERVER_HAS_ALREADY2	"ПРОСТИТЕ, НО СЕРВЕР"

#define iSTR_BEEN_CONFIGURED_BY1	"BEEN CONFIGURED BY"
#define iSTR_BEEN_CONFIGURED_BY2	"УЖЕ СКОНФИГУРИРОВАН"

#define iSTR_ANOTHER_PLAYER1		"ANOTHER PLAYER!"
#define iSTR_ANOTHER_PLAYER2		"ДРУГИМ ИГРОКОМ!"

#define iSTR_Server_Info1		"Server Info"
#define iSTR_Server_Info2		"Текущая Игра"

#define iSTR_CHAT1			"CHAT"
#define iSTR_CHAT2			"ЧАТ"

#define iSTR_START1			"START!"
#define iSTR_START2			"ВПЕРЁД!"


#define iSTR_Chat_Room1 		"Chat Room"
#define iSTR_Chat_Room2 		"Чат"

#define iSTR_SERVER_INFO1		"SERVER INFO"
#define iSTR_SERVER_INFO2		"ТЕКУЩАЯ ИГРА"


#define iSTR_HOST_NAME1 		"HOST NAME:"
#define iSTR_HOST_NAME2 		"ИМЯ СЕРВЕРА:"

#define iSTR_Internet_Servers1		"Internet Servers"
#define iSTR_Internet_Servers2		"Серверы Интернет"


#define iSTR_Game_Results1		"Game Results"
#define iSTR_Game_Results2		"Результаты Игры"

#define iSTR_GAME_PARAMETERS1		"GAME PARAMETERS"
#define iSTR_GAME_PARAMETERS2		"ПАРАМЕТРЫ ИГРЫ"


#define iSTR_Initial_Cash1		"Initial Cash:"
#define iSTR_Initial_Cash2		"Начальный капитал:"

#define iSTR_Artefacts_Using1		"Artefacts Using:"
#define iSTR_Artefacts_Using2		"Использование Артефактов:"


#define iSTR_YES1			"YES"
#define iSTR_YES2			"ДА"

#define iSTR_NO1			"NO"
#define iSTR_NO2			"НЕТ"


#define iSTR_In_Escave_Time1		"In-Escave Time:"
#define iSTR_In_Escave_Time2		"Пребывание в эскейве:"

#define iSTR_min1			"min"           // this one means "minutes"...
#define iSTR_min2			"мин"           // this one means "minutes"...


#define iSTR_ACHTUNG1			"ACHTUNG"
#define iSTR_ACHTUNG2			"ВНИМАНИЕ"

#define iSTR_VANGERS_APPROACHING1	"VANGERS APPROACHING"
#define iSTR_VANGERS_APPROACHING2	"СОЕДИНЯЕМ С ВАШИМ ВАНГЕРОМ"


#define iSTR_Genesis1			"Genesis"
#define iSTR_Genesis2			"Генезис"

#define iSTR_Prehistory1		"Prehistory"
#define iSTR_Prehistory2		"Предыстория..."

#define iSTR_Present1			"Present"
#define iSTR_Present2			"Настоящее"


#define iSTR_Turn_wheels_left1		"Turn wheels left"
#define iSTR_Turn_wheels_left2		"Поворот колёс влево"

#define iSTR_Turn_wheels_right1 	"Turn wheels right"
#define iSTR_Turn_wheels_right2 	"Поворот колёс вправо"

#define iSTR_Move_forward1		"Move forward"
#define iSTR_Move_forward2		"Вперёд"

#define iSTR_Move_backward1		"Move backward"
#define iSTR_Move_backward2		"Назад"

#define iSTR_Acceleration1		"Acceleration"
#define iSTR_Acceleration2		"Ускорение"

#define iSTR_Handbrake1 		"Handbrake"
#define iSTR_Handbrake2 		"Ручной тормоз"

#define iSTR_Turn_over_left1		"Turn over left"
#define iSTR_Turn_over_left2		"Переворот влево"

#define iSTR_Turn_over_right1		"Turn over right"
#define iSTR_Turn_over_right2		"Переворот вправо"

#define iSTR_Activate_KiD1		"Activate KiD"
#define iSTR_Activate_KiD2		"Активация пружины"

#define iSTR_Open1			"Open"
#define iSTR_Open2			"Открыть"

#define iSTR_Turn_device_ON1		"Turn device UP"
#define iSTR_Turn_device_ON2		"Прибор ВВЕРХ"

#define iSTR_Turn_device_OFF1		"Turn device DOWN"
#define iSTR_Turn_device_OFF2		"Прибор ВНИЗ"

#define iSTR_Inventory_ON_OFF1		"Inventory"
#define iSTR_Inventory_ON_OFF2		"Показать трюм"

#define iSTR_Change_target1		"Change target"
#define iSTR_Change_target2		"Переключить цель"

#define iSTR_Fire_all_weapons1		"Fire all weapons"
#define iSTR_Fire_all_weapons2		"Огонь из всего оружия"

#define iSTR_Fire_weapon_11		"Fire weapon 1"
#define iSTR_Fire_weapon_12		"Огонь из оружия 1"

#define iSTR_Fire_weapon_21		"Fire weapon 2"
#define iSTR_Fire_weapon_22		"Огонь из оружия 2"

#define iSTR_Fire_weapon_31		"Fire weapon 3"
#define iSTR_Fire_weapon_32		"Огонь из оружия 3"

#define iSTR_Fire_weapon_41		"Terminator release"
#define iSTR_Fire_weapon_42		"Запуск терминатора"

#define iSTR_Full_screen1		"Full screen"
#define iSTR_Full_screen2		"Полный экран"

#define iSTR_Reduce_view1		"Reduce view"
#define iSTR_Reduce_view2		"Уменьшить обзор"

#define iSTR_Enlarge_view1		"Enlarge view"
#define iSTR_Enlarge_view2		"Увеличить обзор"

#define iSTR_Rotation1			"Rotation"
#define iSTR_Rotation2			"Вращение"

#define iSTR_Auto_tilt1 		"Auto tilt"
#define iSTR_Auto_tilt2 		"Авто наклон"

#define iSTR_Auto_zoom1 		"Auto zoom"
#define iSTR_Auto_zoom2 		"Авто маштаб"

#define iSTR_Zoom_in1			"Zoom in"
#define iSTR_Zoom_in2			"Приблизить камеру"

#define iSTR_Zoom_out1			"Zoom out"
#define iSTR_Zoom_out2			"Отодвинуть камеру"

#define iSTR_Standard_zoom1		"Standard zoom"
#define iSTR_Standard_zoom2		"Маштаб 1:1"

#define iSTR_SkipText1			"Next text part"
#define iSTR_SkipText2			"Следующая часть"

#define iSTR_UseVector1 		"Activate Vector"
#define iSTR_UseVector2 		"Включить Вектор"

#define iSTR_ExitGame1			"Exit game"
#define iSTR_ExitGame2			"Выход из игры"

#define iSTR_ChatON1			"Chat"
#define iSTR_ChatON2			"Чат"

#define iSTR_Statistics1		"Game statistics"
#define iSTR_Statistics2		"Статистика игры"

#define iSTR_VAN_WAR1			"VAN-WAR"
#define iSTR_VAN_WAR2			"ВАН-ВАР"

#define iSTR_MECHOSOMA1 		"MECHOSOMA"
#define iSTR_MECHOSOMA2 		"МЕХОСОМА"

#define iSTR_PASSEMBLOSS1		"PASSEMBLOSS"
#define iSTR_PASSEMBLOSS2		"ПАССЕМБЛОС"

#define iSTR_HUNTAGE1			"HUNTAGE"
#define iSTR_HUNTAGE2			"ХАНТЭЙДЖ"

#define iSTR_MUSTODONT1 		"MUSTODONT"
#define iSTR_MUSTODONT2 		"МАСТОДОНТ"

#define iSTR_JOYSTICK_SETUP1		"JOYSTICK SETUP"
#define iSTR_JOYSTICK_SETUP2		"НАСТРОЙКА ДЖОСТИКА"

#define iSTR_CUSTOMIZE1 		"CUSTOMIZE CONTROLS"
#define iSTR_CUSTOMIZE2 		"НАСТРОЙКА УПРАВЛЕНИЯ"

#define iSTR_JoystickSetup1		"Joystick Setup"
#define iSTR_JoystickSetup2		"Настройка Джостика"

#define iSTR_JoystickType1		"Type:"
#define iSTR_JoystickType2		"Тип:"

#define iSTR_NONE1			"NONE"
#define iSTR_NONE2			"НЕТ"

#define iSTR_JoystickGamePad1		"GamePad"
#define iSTR_JoystickGamePad2		"Геймпад"

#define iSTR_JoystickJoystick1		"Joystick"
#define iSTR_JoystickJoystick2		"Джойстик"

#define iSTR_JoystickSteeringWheel1	"Steering Wheel"
#define iSTR_JoystickSteeringWheel2	"Руль"

#define iSTR_JoystickAlternFnc1 	"Handle Alternative Function:"
#define iSTR_JoystickAlternFnc2 	"Альтернативная функция рукоятки:"

#define iSTR_JoystickBUTTON11		"BUTTON1"
#define iSTR_JoystickBUTTON12		"КНОПКА1"

#define iSTR_JoystickBUTTON21		"BUTTON2"
#define iSTR_JoystickBUTTON22		"КНОПКА2"

#define iSTR_JoystickBUTTON31		"BUTTON3"
#define iSTR_JoystickBUTTON32		"КНОПКА3"

#define iSTR_JoystickBUTTON41		"BUTTON4"
#define iSTR_JoystickBUTTON42		"КНОПКА4"

#define iSTR_JoystickBUTTON51		"BUTTON5"
#define iSTR_JoystickBUTTON52		"КНОПКА5"

#define iSTR_JoystickBUTTON61		"BUTTON6"
#define iSTR_JoystickBUTTON62		"КНОПКА6"

#define iSTR_JoystickBUTTON71		"BUTTON7"
#define iSTR_JoystickBUTTON72		"КНОПКА7"

#define iSTR_JoystickBUTTON81		"BUTTON8"
#define iSTR_JoystickBUTTON82		"КНОПКА8"

#define iSTR_SOCKS5_Proxy1		"SOCKS5 Proxy:"
#define iSTR_SOCKS5_Proxy2		"SOCKS5 Прокси:"

#define iSTR_SOCKS5_ProxyServer1	"Server:"
#define iSTR_SOCKS5_ProxyServer2	"Сервер:"

#define iSTR_SOCKS5_ProxyPort1		"Port:"
#define iSTR_SOCKS5_ProxyPort2		"Порт:"

#define iSTR_Use_Gluek1 	"Use Gluek"
#define iSTR_Use_Gluek2 	"Использовать Глюк"

// Added...
#define iSTR_MaxTime1			"Time:"
#define iSTR_MaxTime2			"Время:"

#define iSTR_MaxKills1			"Max Kills:"
#define iSTR_MaxKills2			"Максимум побед:"

#define iSTR_GameInfo1		"CURRENT GAME"
#define iSTR_GameInfo2		"ТЕКУЩАЯ ИГРА"

#define iSTR_CurIP1			"Your IP:"
#define iSTR_CurIP2			"Ваш IP:"

