
/*
	actInt strings - English Version
*/

// Menu strings...
#define STR_OFF 		$STR_OFF1
#define STR_MAP 		$STR_MAP1
#define STR_WMAP		$STR_WMAP1
#define STR_TARGETS		$STR_TARGETS1
#define STR_CAMERAS		$STR_CAMERAS1
#define STR_PARAMS		$STR_PARAMS1
#define STR_BOOTSECTOR		$STR_BOOTSECTOR1
#define STR_PROTRACTOR		$STR_PROTRACTOR1
#define STR_MECH_MESSIAH	$STR_MECH_MESSIAH1
#define STR_PASS_TO		$STR_PASS_TO1

// Protractor menu strings...
#define STR_Spobsion		$STR_Spobsion1
#define STR_Resizing		$STR_Resizing1
#define STR_Barrier		$STR_Barrier1
#define STR_Beebs_Festival	$STR_Beebs_Festival1
#define STR_Circus		$STR_Circus1
#define STR_Ostrich		$STR_Ostrich1
#define STR_Function83		$STR_Function831
#define STR_HyperBeacon 	$STR_HyperBeacon1

// Mech messiah menu strings...
#define STR_Cloak		$STR_Cloak1
#define STR_Luck		$STR_Luck1
#define STR_Beebsospy		$STR_Beebsospy1
#define STR_Firework		$STR_Firework1
#define STR_Shake_Up		$STR_Shake_Up1
#define STR_Blackada		$STR_Blackada1

// Function-83 menu strings (and world names)...
#define STR_Fostral		$STR_Fostral1
#define STR_Glorx		$STR_Glorx1
#define STR_Necross		$STR_Necross1
#define STR_Xplo		$STR_Xplo1
#define STR_Khox		$STR_Khox1
#define STR_Boozeena		$STR_Boozeena1
#define STR_Weexow		$STR_Weexow1
#define STR_hMok		$STR_hMok1
#define STR_Threall		$STR_Threall1
#define STR_Ark_a_Znoy		$STR_Ark_a_Znoy1


// Mechoses...
#define MECH00_NAME		$MECH00_NAME1
#define MECH01_NAME		$MECH01_NAME1
#define MECH02_NAME		$MECH02_NAME1
#define MECH03_NAME		$MECH03_NAME1
#define MECH04_NAME		$MECH04_NAME1
#define MECH05_NAME		$MECH05_NAME1
#define MECH06_NAME		$MECH06_NAME1
#define MECH07_NAME		$MECH07_NAME1
#define MECH08_NAME		$MECH08_NAME1
#define MECH09_NAME		$MECH09_NAME1
#define MECH10_NAME		$MECH10_NAME1
#define MECH11_NAME		$MECH11_NAME1
#define MECH12_NAME		$MECH12_NAME1
#define MECH13_NAME		$MECH13_NAME1
#define MECH14_NAME		$MECH14_NAME1
#define MECH15_NAME		$MECH15_NAME1
#define MECH16_NAME		$MECH16_NAME1
#define MECH17_NAME		$MECH17_NAME1
#define MECH18_NAME		$MECH18_NAME1
#define MECH19_NAME		$MECH19_NAME1
#define MECH20_NAME		$MECH20_NAME1
#define MECH21_NAME		$MECH21_NAME1
#define MECH22_NAME		$MECH22_NAME1
#define MECH23_NAME		$MECH23_NAME1
#define MECH24_NAME		$MECH24_NAME1
#define MECH25_NAME		$MECH25_NAME1
#define MECH26_NAME		$MECH26_NAME1
#define MECH27_NAME		$MECH27_NAME1
#define MECH28_NAME		$MECH28_NAME1
#define MECH29_NAME		$MECH29_NAME1
#define MECH30_NAME		$MECH30_NAME1
#define MECH31_NAME		$MECH31_NAME1
#define MECH32_NAME		$MECH32_NAME1
#define MECH33_NAME		$MECH33_NAME1
#define MECH34_NAME		$MECH34_NAME1
#define MECH35_NAME		$MECH35_NAME1
#define MECH36_NAME		$MECH36_NAME1
#define MECH37_NAME		$MECH37_NAME1
#define MECH38_NAME		$MECH38_NAME1

/* --------------------------------- ITEMS ---------------------------------- */


/* ----------------------------- NAMES SECTION ------------------------------ */

// MacHOTine Gun (light)
#define ITM01_NAME		$ITM01_NAME1

// MacHOTine Gun (heavy)
#define ITM02_NAME		$ITM02_NAME1

// Speetle System (light)
#define ITM03_NAME		$ITM03_NAME1

// Speetle System (heavy)
#define ITM04_NAME		$ITM04_NAME1

// ghOrb Gear (light)
#define ITM05_NAME		$ITM05_NAME1

// ghOrb Gear (heavy)
#define ITM06_NAME		$ITM06_NAME1

// Beebbanoza Blockade
#define ITM07_NAME		$ITM07_NAME1

// Crustest Cannon
#define ITM08_NAME		$ITM08_NAME1

// Terminator 'Wormer'
#define ITM09_NAME		$ITM09_NAME1

// Terminator 'Wasp'
#define ITM10_NAME		$ITM10_NAME1

// Pupok pile
#define ITM11_NAME		$ITM11_NAME1

// OKorOK pile
#define ITM12_NAME		$ITM12_NAME1

// Boltoon pack
#define ITM13_NAME		$ITM13_NAME1

// CopteRig
#define ITM14_NAME		$ITM14_NAME1

// CopteRig (empty)
#define ITM15_NAME		$ITM15_NAME1

// CutteRig
#define ITM16_NAME		$ITM16_NAME1

// CutteRig (empty)
#define ITM17_NAME		$ITM17_NAME1

// CrotRig
#define ITM18_NAME		$ITM18_NAME1

// CrotRig (empty)
#define ITM19_NAME		$ITM19_NAME1

// Lhark - does not exist :)
#define ITM20_NAME		$ITM20_NAME1

// Lhark - does not exist :)
#define ITM21_NAME		$ITM21_NAME1

// Vector
#define ITM22_NAME		$ITM22_NAME1

// Cirtainer
#define ITM23_NAME		$ITM23_NAME1

// Cirtainer (empty)
#define ITM24_NAME		$ITM24_NAME1

// Conlarver
#define ITM25_NAME		$ITM25_NAME1

// Conlarver (empty)
#define ITM26_NAME		$ITM26_NAME1

// Nymbos
#define ITM27_NAME		$ITM27_NAME1

// Phlegma
#define ITM28_NAME		$ITM28_NAME1

// Heroin
#define ITM29_NAME		$ITM29_NAME1

// Shrub
#define ITM30_NAME		$ITM30_NAME1

// Poponka
#define ITM31_NAME		$ITM31_NAME1

// Toxick
#define ITM32_NAME		$ITM32_NAME1

// eLeech
#define ITM33_NAME		$ITM33_NAME1

// Kernoboo
#define ITM34_NAME		$ITM34_NAME1

// Pipetka
#define ITM35_NAME		$ITM35_NAME1

// WeeZyk
#define ITM36_NAME		$ITM36_NAME1

// Protractor
#define ITM37_NAME		$ITM37_NAME1

// Mechanic Messiah
#define ITM38_NAME		$ITM38_NAME1

// Function-83+
#define ITM39_NAME		$ITM39_NAME1

// SpuMMy
#define ITM40_NAME		$ITM40_NAME1

// Leepuringa
#define ITM41_NAME		$ITM41_NAME1

// Dead eLeech
#define ITM42_NAME		$ITM42_NAME1

// Rubox
#define ITM43_NAME		$ITM43_NAME1

// Zigger-Zagger
#define ITM44_NAME		$ITM44_NAME1

// Cart
#define ITM45_NAME		$ITM45_NAME1

// Put-Put
#define ITM46_NAME		$ITM46_NAME1

// Box
#define ITM47_NAME		$ITM47_NAME1

// Rattle
#define ITM48_NAME		$ITM48_NAME1

// Heavy Iron
#define ITM49_NAME		$ITM49_NAME1

// Star
#define ITM50_NAME		$ITM50_NAME1

// Whizzer
#define ITM51_NAME		$ITM51_NAME1

// Husker
#define ITM52_NAME		$ITM52_NAME1

// Cogged Widget
#define ITM53_NAME		$ITM53_NAME1

// TankAcid
#define ITM54_NAME		$ITM54_NAME1

// Boot Sector
#define ITM56_NAME		$ITM56_NAME1

// Peelot
#define ITM55_NAME		$ITM55_NAME1

// Mechoscope
#define ITM57_NAME		$ITM57_NAME1

// Gluek
#define ITM58_NAME		$ITM58_NAME1

// Degradator
#define ITM59_NAME		$ITM59_NAME1

// Tabutask (active)
#define ITM60_NAME		$ITM60_NAME1

// Amputator
#define ITM61_NAME		$ITM61_NAME1

// Eleepod
#define ITM62_NAME		$ITM62_NAME1

// Beeboorat
#define ITM63_NAME		$ITM63_NAME1

// Zeex
#define ITM64_NAME		$ITM64_NAME1

// Palochka
#define ITM65_NAME		$ITM65_NAME1

// Pipka
#define ITM66_NAME		$ITM66_NAME1

// Nobool
#define ITM67_NAME		$ITM67_NAME1

// Boorawchick
#define ITM68_NAME		$ITM68_NAME1

// Pereponka
#define ITM69_NAME		$ITM69_NAME1

// Zeefick
#define ITM70_NAME		$ITM70_NAME1

// Dead WeeZyk
#define ITM71_NAME		$ITM71_NAME1

// Rotten Kernoboo
#define ITM72_NAME		$ITM72_NAME1

// Tabutask (failed)
#define ITM73_NAME		$ITM73_NAME1

// Tabutask (completed)
#define ITM74_NAME		$ITM74_NAME1

// Amputator (empty)
#define ITM75_NAME		$ITM75_NAME1

// Degradator (empty)
#define ITM76_NAME		$ITM76_NAME1

// Rotten Pipetka
#define ITM77_NAME		$ITM77_NAME1

// Mechoscope (empty)
#define ITM78_NAME		$ITM78_NAME1

/* ---------------------------- COMMENTS SECTION ---------------------------- */

// MacHOTine Gun (light)
#define ITM01_COMMENTS		$ITM01_COMMENTS1

// MacHOTine Gun (heavy)
#define ITM02_COMMENTS		$ITM02_COMMENTS1

// Speetle System (light)
#define ITM03_COMMENTS		$ITM03_COMMENTS1

// Speetle System (heavy)
#define ITM04_COMMENTS		$ITM04_COMMENTS1

// ghOrb Gear (light)
#define ITM05_COMMENTS		$ITM05_COMMENTS1

// ghOrb Gear (heavy)
#define ITM06_COMMENTS		$ITM06_COMMENTS1

// Beebbanoza Blockade
#define ITM07_COMMENTS		$ITM07_COMMENTS1

// Crustest Cannon
#define ITM08_COMMENTS		$ITM08_COMMENTS1

// Terminator 'Wormer'
#define ITM09_COMMENTS		$ITM09_COMMENTS1

// Terminator 'Wasp'
#define ITM10_COMMENTS		$ITM10_COMMENTS1

// Pupok pile
#define ITM11_COMMENTS		$ITM11_COMMENTS1

// OKorOK pile
#define ITM12_COMMENTS		$ITM12_COMMENTS1

// Boltoon pack
#define ITM13_COMMENTS		$ITM13_COMMENTS1

// CopteRig
#define ITM14_COMMENTS		$ITM14_COMMENTS1

// CopteRig (empty)
#define ITM15_COMMENTS		$ITM15_COMMENTS1

// CutteRig
#define ITM16_COMMENTS		$ITM16_COMMENTS1

// CutteRig (empty)
#define ITM17_COMMENTS		$ITM17_COMMENTS1

// CrotRig
#define ITM18_COMMENTS		$ITM18_COMMENTS1

// CrotRig (empty)
#define ITM19_COMMENTS		$ITM19_COMMENTS1

// Lhark - does not exist :)
#define ITM20_COMMENTS		$ITM20_COMMENTS1

// Lhark - does not exist :)
#define ITM21_COMMENTS		$ITM21_COMMENTS1

// Vector
#define ITM22_COMMENTS		$ITM22_COMMENTS1

// Cirtainer
#define ITM23_COMMENTS		$ITM23_COMMENTS1

// Cirtainer (empty)
#define ITM24_COMMENTS		$ITM24_COMMENTS1

// Conlarver
#define ITM25_COMMENTS		$ITM25_COMMENTS1

// Conlarver (empty)
#define ITM26_COMMENTS		$ITM26_COMMENTS1

// Nymbos
#define ITM27_COMMENTS		$ITM27_COMMENTS1

// Phlegma
#define ITM28_COMMENTS		$ITM28_COMMENTS1

// Heroin
#define ITM29_COMMENTS		$ITM29_COMMENTS1

// Shrub
#define ITM30_COMMENTS		$ITM30_COMMENTS1

// Poponka
#define ITM31_COMMENTS		$ITM31_COMMENTS1

// Toxick
#define ITM32_COMMENTS		$ITM32_COMMENTS1

// eLeech
#define ITM33_COMMENTS		$ITM33_COMMENTS1

// Kernoboo
#define ITM34_COMMENTS		$ITM34_COMMENTS1

// Pipetka
#define ITM35_COMMENTS		$ITM35_COMMENTS1

// WeeZyk
#define ITM36_COMMENTS		$ITM36_COMMENTS1

// Leepuringa
#define ITM41_COMMENTS		$ITM41_COMMENTS1

// Dead eLeech
#define ITM42_COMMENTS		$ITM42_COMMENTS1

// Protractor
#define ITM37_COMMENTS		$ITM37_COMMENTS1

// Mechanic Messiah
#define ITM38_COMMENTS		$ITM38_COMMENTS1

// Function-83+
#define ITM39_COMMENTS		$ITM39_COMMENTS1

// SpuMMy
#define ITM40_COMMENTS		$ITM40_COMMENTS1

// Rubox
#define ITM43_COMMENTS		$ITM43_COMMENTS1

// Zigger-Zagger
#define ITM44_COMMENTS		$ITM44_COMMENTS1

// Cart
#define ITM45_COMMENTS		$ITM45_COMMENTS1

// Put-Put
#define ITM46_COMMENTS		$ITM46_COMMENTS1

// Box
#define ITM47_COMMENTS		$ITM47_COMMENTS1

// Rattle
#define ITM48_COMMENTS		$ITM48_COMMENTS1

// Heavy Iron
#define ITM49_COMMENTS		$ITM49_COMMENTS1

// Star
#define ITM50_COMMENTS		$ITM50_COMMENTS1

// Whizzer
#define ITM51_COMMENTS		$ITM51_COMMENTS1

// Husker
#define ITM52_COMMENTS		$ITM52_COMMENTS1

// Cogged Widget
#define ITM53_COMMENTS		$ITM53_COMMENTS1

// TankAcid
#define ITM54_COMMENTS		$ITM54_COMMENTS1

// Peelot
#define ITM55_COMMENTS		$ITM55_COMMENTS1

// Boot Sector
#define ITM56_COMMENTS		$ITM56_COMMENTS1

// Mechoscope
#define ITM57_COMMENTS		$ITM57_COMMENTS1

// Gluek
#define ITM58_COMMENTS		$ITM58_COMMENTS1

// Degradator
#define ITM59_COMMENTS		$ITM59_COMMENTS1

// Tabutask (active)
#define ITM60_COMMENTS		$ITM60_COMMENTS1

// Amputator
#define ITM61_COMMENTS		$ITM61_COMMENTS1

// Eleepod
#define ITM62_COMMENTS		$ITM62_COMMENTS1

// Beeboorat
#define ITM63_COMMENTS		$ITM63_COMMENTS1

// Zeex
#define ITM64_COMMENTS		$ITM64_COMMENTS1

// Palochka
#define ITM65_COMMENTS		$ITM65_COMMENTS1

// Pipka
#define ITM66_COMMENTS		$ITM66_COMMENTS1

// Nobool
#define ITM67_COMMENTS		$ITM67_COMMENTS1

// Boorawchick
#define ITM68_COMMENTS		$ITM68_COMMENTS1

// Pereponka
#define ITM69_COMMENTS		$ITM69_COMMENTS1

// Zeefick
#define ITM70_COMMENTS		$ITM70_COMMENTS1

// Dead WeeZyk
#define ITM71_COMMENTS		$ITM71_COMMENTS1

// Rotten Kernoboo
#define ITM72_COMMENTS		$ITM72_COMMENTS1

// Tabutask (failed)
#define ITM73_COMMENTS		$ITM73_COMMENTS1

// Tabutask (completed)
#define ITM74_COMMENTS		$ITM74_COMMENTS1

// Amputator (empty)
#define ITM75_COMMENTS		$ITM75_COMMENTS1

// Degradator (empty)
#define ITM76_COMMENTS		$ITM76_COMMENTS1

// Rotten Pipetka
#define ITM77_COMMENTS		$ITM77_COMMENTS1

// Mechoscope (empty)
#define ITM78_COMMENTS		$ITM78_COMMENTS1

/* ------------------------- SHOP COMMENTS SECTION -------------------------- */

// MacHOTine Gun (light)
#define iITM01_COMMENTS 	$iITM01_COMMENTS1

// MacHOTine Gun (heavy)
#define iITM02_COMMENTS 	$iITM02_COMMENTS1

// Speetle System (light)
#define iITM03_COMMENTS 	$iITM03_COMMENTS1

// Speetle System (heavy)
#define iITM04_COMMENTS 	$iITM04_COMMENTS1

// ghOrb Gear (light)
#define iITM05_COMMENTS 	$iITM05_COMMENTS1

// ghOrb Gear (heavy)
#define iITM06_COMMENTS 	$iITM06_COMMENTS1

// Beebbanoza Blockade
#define iITM07_COMMENTS 	$iITM07_COMMENTS1

// Crustest Cannon
#define iITM08_COMMENTS 	$iITM08_COMMENTS1

// Terminator 'Wormer'
#define iITM09_COMMENTS 	$iITM09_COMMENTS1

// Terminator 'Wasp'
#define iITM10_COMMENTS 	$iITM10_COMMENTS1

// Pupok pile
#define iITM11_COMMENTS 	$iITM11_COMMENTS1

// OKorOK pile
#define iITM12_COMMENTS 	$iITM12_COMMENTS1

// Boltoon pack
#define iITM13_COMMENTS 	$iITM13_COMMENTS1

// CopteRig
#define iITM14_COMMENTS 	$iITM14_COMMENTS1

// CopteRig (empty)
#define iITM15_COMMENTS 	$iITM15_COMMENTS1

// CutteRig
#define iITM16_COMMENTS 	$iITM16_COMMENTS1

// CutteRig (empty)
#define iITM17_COMMENTS 	$iITM17_COMMENTS1

// CrotRig
#define iITM18_COMMENTS 	$iITM18_COMMENTS1

// CrotRig (empty)
#define iITM19_COMMENTS 	$iITM19_COMMENTS1

// Lhark - does not exist :)
#define iITM20_COMMENTS 	$iITM20_COMMENTS1

// Lhark - does not exist :)
#define iITM21_COMMENTS 	$iITM21_COMMENTS1

// Vector
#define iITM22_COMMENTS 	$iITM22_COMMENTS1

// Cirtainer
#define iITM23_COMMENTS 	$iITM23_COMMENTS1

// Cirtainer (empty)
#define iITM24_COMMENTS 	$iITM24_COMMENTS1

// Conlarver
#define iITM25_COMMENTS 	$iITM25_COMMENTS1

// Conlarver (empty)
#define iITM26_COMMENTS 	$iITM26_COMMENTS1

// Nymbos
#define iITM27_COMMENTS 	$iITM27_COMMENTS1

// Phlegma
#define iITM28_COMMENTS 	$iITM28_COMMENTS1

// Heroin
#define iITM29_COMMENTS 	$iITM29_COMMENTS1

// Shrub
#define iITM30_COMMENTS 	$iITM30_COMMENTS1

// Poponka
#define iITM31_COMMENTS 	$iITM31_COMMENTS1

// Toxick
#define iITM32_COMMENTS 	$iITM32_COMMENTS1

// eLeech
#define iITM33_COMMENTS 	$iITM33_COMMENTS1

// Kernoboo
#define iITM34_COMMENTS 	$iITM34_COMMENTS1

// Pipetka
#define iITM35_COMMENTS 	$iITM35_COMMENTS1

// WeeZyk
#define iITM36_COMMENTS 	$iITM36_COMMENTS1

// Protractor
#define iITM37_COMMENTS 	$iITM37_COMMENTS1

// Mechanic Messiah
#define iITM38_COMMENTS 	$iITM38_COMMENTS1

// Function-83+
#define iITM39_COMMENTS 	$iITM39_COMMENTS1

// SpuMMy
#define iITM40_COMMENTS 	$iITM40_COMMENTS1

// Leepuringa
#define iITM41_COMMENTS 	$iITM41_COMMENTS1

// Dead eLeech
#define iITM42_COMMENTS 	$iITM42_COMMENTS1

// Rubox
#define iITM43_COMMENTS 	$iITM43_COMMENTS1

// Zigger-Zagger
#define iITM44_COMMENTS 	$iITM44_COMMENTS1

// Cart
#define iITM45_COMMENTS 	$iITM45_COMMENTS1

// Put-Put
#define iITM46_COMMENTS 	$iITM46_COMMENTS1

// Box
#define iITM47_COMMENTS 	$iITM47_COMMENTS1

// Rattle
#define iITM48_COMMENTS 	$iITM48_COMMENTS1

// Heavy Iron
#define iITM49_COMMENTS 	$iITM49_COMMENTS1

// Star
#define iITM50_COMMENTS 	$iITM50_COMMENTS1

// Whizzer
#define iITM51_COMMENTS 	$iITM51_COMMENTS1

// Husker
#define iITM52_COMMENTS 	$iITM52_COMMENTS1

// Cogged Widget
#define iITM53_COMMENTS 	$iITM53_COMMENTS1

// TankAcid
#define iITM54_COMMENTS 	$iITM54_COMMENTS1

// Boot Sector
#define iITM56_COMMENTS 	$iITM56_COMMENTS1

// Peelot
#define iITM55_COMMENTS 	$iITM55_COMMENTS1

// Mechoscope
#define iITM57_COMMENTS 	$iITM57_COMMENTS1

// Gluek
#define iITM58_COMMENTS 	$iITM58_COMMENTS1

// Degradator
#define iITM59_COMMENTS 	$iITM59_COMMENTS1

// Tabutask (active)
#define iITM60_COMMENTS 	$iITM60_COMMENTS1

// Amputator
#define iITM61_COMMENTS 	$iITM61_COMMENTS1

// Eleepod
#define iITM62_COMMENTS 	$iITM62_COMMENTS1

// Beeboorat
#define iITM63_COMMENTS 	$iITM63_COMMENTS1

// Zeex
#define iITM64_COMMENTS 	$iITM64_COMMENTS1

// Palochka
#define iITM65_COMMENTS 	$iITM65_COMMENTS1

// Pipka
#define iITM66_COMMENTS 	$iITM66_COMMENTS1

// Nobool
#define iITM67_COMMENTS 	$iITM67_COMMENTS1

// Boorawchick
#define iITM68_COMMENTS 	$iITM68_COMMENTS1

// Pereponka
#define iITM69_COMMENTS 	$iITM69_COMMENTS1

// Zeefick
#define iITM70_COMMENTS 	$iITM70_COMMENTS1

// Dead WeeZyk
#define iITM71_COMMENTS 	$iITM71_COMMENTS1

// Rotten Kernoboo
#define iITM72_COMMENTS 	$iITM72_COMMENTS1

// Tabutask (failed)
#define iITM73_COMMENTS 	$iITM73_COMMENTS1

// Tabutask (completed)
#define iITM74_COMMENTS 	$iITM74_COMMENTS1

// Amputator (empty)
#define iITM75_COMMENTS 	$iITM75_COMMENTS1

// Degradator (empty)
#define iITM76_COMMENTS 	$iITM76_COMMENTS1

// Rotten Pipetka
#define iITM77_COMMENTS 	$iITM77_COMMENTS1

// Mechoscope (empty)
#define iITM78_COMMENTS 	$iITM78_COMMENTS1

/* --------------------------- ITEMS INFO SECTION --------------------------- */

// MacHOTine Gun (light)
#define ITM01_INFO		$ITM01_INFO1

// MacHOTine Gun (heavy)
#define ITM02_INFO		$ITM02_INFO1

// Speetle System (light)
#define ITM03_INFO		$ITM03_INFO1

// Speetle System (heavy)
#define ITM04_INFO		$ITM04_INFO1

// ghOrb Gear (light)
#define ITM05_INFO		$ITM05_INFO1

// ghOrb Gear (heavy)
#define ITM06_INFO		$ITM06_INFO1

// Beebbanoza Blockade
#define ITM07_INFO		$ITM07_INFO1

// Crustest Cannon
#define ITM08_INFO		$ITM08_INFO1

// Terminator 'Wormer'
#define ITM09_INFO		$ITM09_INFO1

// Terminator 'Wasp'
#define ITM10_INFO		$ITM10_INFO1

// CopteRig
#define ITM14_INFO		$ITM14_INFO1

// CopteRig (empty)
#define ITM15_INFO		$ITM15_INFO1

// CutteRig
#define ITM16_INFO		$ITM16_INFO1

// CutteRig (empty)
#define ITM17_INFO		$ITM17_INFO1

// CrotRig
#define ITM18_INFO		$ITM18_INFO1

// CrotRig (empty)
#define ITM19_INFO		$ITM19_INFO1

// Vector
#define ITM22_INFO		$ITM22_INFO1

// Cirtainer (empty)
#define ITM24_INFO		$ITM24_INFO1

// Conlarver (empty)
#define ITM26_INFO		$ITM26_INFO1

// Tabutask
#define ITM60_INFO		$ITM60_INFO1

// Poponka
#define ITM31_INFO		$ITM31_INFO1

// Protractor
#define ITM37_INFO		$ITM37_INFO1

// Mechanic Messiah
#define ITM38_INFO		$ITM38_INFO1

// Function-83+
#define ITM39_INFO		$ITM39_INFO1

// Boot Sector
#define ITM56_INFO		$ITM56_INFO1

// Peelot
#define ITM55_INFO		$ITM55_INFO1

// Mechoscope(empty)
#define ITM75_INFO		$ITM75_INFO1

// Gluek
#define ITM58_INFO		$ITM58_INFO1

// Degradator(empty)
#define ITM76_INFO		$ITM76_INFO1

// Amputator(empty)
#define ITM78_INFO		$ITM78_INFO1

// Eleepod
#define ITM62_INFO		$ITM62_INFO1

// Beeboorat
#define ITM63_INFO		$ITM63_INFO1

// Zeex
#define ITM64_INFO		$ITM64_INFO1

/* --------------------------- PARAMETERS SECTION --------------------------- */

// MacHOTine Gun (light)
#define ITM01_PARAMS		$ITM01_PARAMS1

// MacHOTine Gun (heavy)
#define ITM02_PARAMS		$ITM02_PARAMS1

// Speetle System (light)
#define ITM03_PARAMS		$ITM03_PARAMS1

// Speetle System (heavy)
#define ITM04_PARAMS		$ITM04_PARAMS1

// ghOrb Gear (light)
#define ITM05_PARAMS		$ITM05_PARAMS1

// ghOrb Gear (heavy)
#define ITM06_PARAMS		$ITM06_PARAMS1

// Beebbanoza Blockade
#define ITM07_PARAMS		$ITM07_PARAMS1

// Crustest Cannon
#define ITM08_PARAMS		$ITM08_PARAMS1

// Terminator 'Wormer'
#define ITM09_PARAMS		$ITM09_PARAMS1

// Terminator 'Wasp'
#define ITM10_PARAMS		$ITM10_PARAMS1

// Pupok pile
#define ITM11_PARAMS		$ITM11_PARAMS1

// OKorOK pile
#define ITM12_PARAMS		$ITM12_PARAMS1

// Boltoon pack
#define ITM13_PARAMS		$ITM13_PARAMS1

// CopteRig
#define ITM14_PARAMS		$ITM14_PARAMS1

// CopteRig (empty)
#define ITM15_PARAMS		$ITM15_PARAMS1

// CutteRig
#define ITM16_PARAMS		$ITM16_PARAMS1

// CutteRig (empty)
#define ITM17_PARAMS		$ITM17_PARAMS1

// CrotRig
#define ITM18_PARAMS		$ITM18_PARAMS1

// CrotRig (empty)
#define ITM19_PARAMS		$ITM19_PARAMS1

// Lhark - does not exist :)
#define ITM20_PARAMS		$ITM20_PARAMS1

// Lhark - does not exist :)
#define ITM21_PARAMS		$ITM21_PARAMS1

// Vector
#define ITM22_PARAMS		$ITM22_PARAMS1

// Cirtainer
#define ITM23_PARAMS		$ITM23_PARAMS1

// Cirtainer (empty)
#define ITM24_PARAMS		$ITM24_PARAMS1

// Conlarver
#define ITM25_PARAMS		$ITM25_PARAMS1

// Conlarver (empty)
#define ITM26_PARAMS		$ITM26_PARAMS1

// Nymbos
#define ITM27_PARAMS		$ITM27_PARAMS1

// Phlegma
#define ITM28_PARAMS		$ITM28_PARAMS1

// Heroin
#define ITM29_PARAMS		$ITM29_PARAMS1

// Shrub
#define ITM30_PARAMS		$ITM30_PARAMS1

// Poponka
#define ITM31_PARAMS		$ITM31_PARAMS1

// Toxick
#define ITM32_PARAMS		$ITM32_PARAMS1

// eLeech
#define ITM33_PARAMS		$ITM33_PARAMS1

// Kernoboo
#define ITM34_PARAMS		$ITM34_PARAMS1

// Pipetka
#define ITM35_PARAMS		$ITM35_PARAMS1

// WeeZyk
#define ITM36_PARAMS		$ITM36_PARAMS1

// Protractor
#define ITM37_PARAMS		$ITM37_PARAMS1

// Mechanic Messiah
#define ITM38_PARAMS		$ITM38_PARAMS1

// Function-83+
#define ITM39_PARAMS		$ITM39_PARAMS1

// SpuMMy
#define ITM40_PARAMS		$ITM40_PARAMS1

// Leepuringa
#define ITM41_PARAMS		$ITM41_PARAMS1

// Dead eLeech
#define ITM42_PARAMS		$ITM42_PARAMS1

// Rubox
#define ITM43_PARAMS		$ITM43_PARAMS1

// Zigger-Zagger
#define ITM44_PARAMS		$ITM44_PARAMS1

// Cart
#define ITM45_PARAMS		$ITM45_PARAMS1

// Put-Put
#define ITM46_PARAMS		$ITM46_PARAMS1

// Box
#define ITM47_PARAMS		$ITM47_PARAMS1

// Rattle
#define ITM48_PARAMS		$ITM48_PARAMS1

// Heavy Iron
#define ITM49_PARAMS		$ITM49_PARAMS1

// Star
#define ITM50_PARAMS		$ITM50_PARAMS1

// Whizzer
#define ITM51_PARAMS		$ITM51_PARAMS1

// Husker
#define ITM52_PARAMS		$ITM52_PARAMS1

// Cogged Widget
#define ITM53_PARAMS		$ITM53_PARAMS1

// TankAcid
#define ITM54_PARAMS		$ITM54_PARAMS1

// Boot Sector
#define ITM56_PARAMS		$ITM56_PARAMS1

// Peelot
#define ITM55_PARAMS		$ITM55_PARAMS1

// Mechoscope
#define ITM57_PARAMS		$ITM57_PARAMS1

// Gluek
#define ITM58_PARAMS		$ITM58_PARAMS1

// Degradator
#define ITM59_PARAMS		$ITM59_PARAMS1

// Tabutask (active)
#define ITM60_PARAMS		$ITM60_PARAMS1

// Amputator
#define ITM61_PARAMS		$ITM61_PARAMS1

// Eleepod
#define ITM62_PARAMS		$ITM62_PARAMS1

// Beeboorat
#define ITM63_PARAMS		$ITM63_PARAMS1

// Zeex
#define ITM64_PARAMS		$ITM64_PARAMS1

// Palochka
#define ITM65_PARAMS		$ITM65_PARAMS1

// Pipka
#define ITM66_PARAMS		$ITM66_PARAMS1

// Nobool
#define ITM67_PARAMS		$ITM67_PARAMS1

// Boorawchick
#define ITM68_PARAMS		$ITM68_PARAMS1

// Pereponka
#define ITM69_PARAMS		$ITM69_PARAMS1

// Zeefick
#define ITM70_PARAMS		$ITM70_PARAMS1

// Dead WeeZyk
#define ITM71_PARAMS		$ITM71_PARAMS1

// Rotten Kernoboo
#define ITM72_PARAMS		$ITM72_PARAMS1

// Tabutask (failed)
#define ITM73_PARAMS		$ITM73_PARAMS1

// Tabutask (completed)
#define ITM74_PARAMS		$ITM74_PARAMS1

// Amputator (empty)
#define ITM75_PARAMS		$ITM75_PARAMS1

// Degradator (empty)
#define ITM76_PARAMS		$ITM76_PARAMS1

// Rotten Pipetka
#define ITM77_PARAMS		$ITM77_PARAMS1

// Mechoscope (empty)
#define ITM78_PARAMS		$ITM78_PARAMS1

// Tips...

#define MODE_BUTTON_TEXT		$MODE_BUTTON_TEXT1
#define PICKUP_ITEMS_BUTTON_TEXT	$PICKUP_ITEMS_BUTTON_TEXT1
#define PICKUP_WEAPONS_BUTTON_TEXT	$PICKUP_WEAPONS_BUTTON_TEXT1
#define ESCAVE_BUTTON_TEXT		$ESCAVE_BUTTON_TEXT1
#define ENERGY_IND_TEXT 		$ENERGY_IND_TEXT1
#define LOAD_IND_TEXT			$LOAD_IND_TEXT1
#define POWERUP_IND_TEXT		$POWERUP_IND_TEXT1
#define SPIRAL_IND_TEXT 		$SPIRAL_IND_TEXT1

// Escaves...
#define ESCAVE_NAME0		$ESCAVE_NAME01
#define ESCAVE_NAME1		$ESCAVE_NAME11
#define ESCAVE_NAME2		$ESCAVE_NAME21
#define ESCAVE_NAME3		$ESCAVE_NAME31
#define ESCAVE_NAME4		$ESCAVE_NAME41
#define ESCAVE_NAME5		$ESCAVE_NAME51
#define ESCAVE_NAME6		$ESCAVE_NAME61
#define ESCAVE_NAME7		$ESCAVE_NAME71

