
/*
	actInt string defines

	English Version:
	#define <SOMEWORD>1	"..."

	Local Version:
	#define <SOMEWORD>2	"..."
*/

// Menu strings...
#define STR_OFF1		"OFF"
#define STR_OFF2		"Выкл."

#define STR_MAP1		"MAP"
#define STR_MAP2		"КАРТА"

#define STR_WMAP1		"THE CHAIN"
#define STR_WMAP2		"ЦЕПЬ МИРОВ"

#define STR_TARGETS1		"COMPASS"
#define STR_TARGETS2		"КОМПАС"

#define STR_CAMERAS1		"CAMERA"
#define STR_CAMERAS2		"КАМЕРА"

#define STR_PARAMS1		"PARAMETERS"
#define STR_PARAMS2		"ПАРАМЕТРЫ"

#define STR_BOOTSECTOR1 	"BOOTSECTOR"
#define STR_BOOTSECTOR2 	"Бут Сектор"

#define STR_PROTRACTOR1 	"PROTRACTOR"
#define STR_PROTRACTOR2 	"Начертатель"

#define STR_MECH_MESSIAH1	"MECH MESSIAH"
#define STR_MECH_MESSIAH2	"Мех. Мессия"

#define STR_PASS_TO1		"PASS TO"
#define STR_PASS_TO2		"ПЕРЕЙТИ НА"

// Protractor menu strings...
#define STR_Spobsion1		"Spobsion"
#define STR_Spobsion2		"Спобсобность"

#define STR_Resizing1		"Resizing"
#define STR_Resizing2		"Размеривание"

#define STR_Barrier1		"Barrier"
#define STR_Barrier2		"Оградка"

#define STR_Beebs_Festival1	"Beeb's Festival"
#define STR_Beebs_Festival2	"Фестиваль бибов"

#define STR_Circus1		"Circus"
#define STR_Circus2		"Цирк"

#define STR_Ostrich1		"Ostrich"
#define STR_Ostrich2		"Страус"

#define STR_Function831 	"Function-83"
#define STR_Function832 	"Способ-83"

#define STR_HyperBeacon1	"Hyper Beacon"
#define STR_HyperBeacon2	"Гипермаяк"

// Mech messiah menu strings...
#define STR_Cloak1		"Cloak"
#define STR_Cloak2		"Покров"

#define STR_Luck1		"Luck"
#define STR_Luck2		"Счастливчик"

#define STR_Beebsospy1		"Beebsospy"
#define STR_Beebsospy2		"Мал-да-Удал"

#define STR_Firework1		"Firework"
#define STR_Firework2		"Фейерверк"

#define STR_Shake_Up1		"Shake-Up"
#define STR_Shake_Up2		"Встряска"

#define STR_Blackada1		"Blackada"
#define STR_Blackada2		"Чернозем"

// Function-83 menu strings (and world names)...
#define STR_Fostral1		"Fostral"
#define STR_Fostral2		"Фострал"

#define STR_Glorx1		"Glorx"
#define STR_Glorx2		"Глоркс"

#define STR_Necross1		"Necross"
#define STR_Necross2		"Некросс"

#define STR_Xplo1		"Xplo"
#define STR_Xplo2		"Икспло"

#define STR_Khox1		"Khox"
#define STR_Khox2		"Кокс"

#define STR_Boozeena1		"Boozeena"
#define STR_Boozeena2		"Бузина"

#define STR_Weexow1		"Weexow"
#define STR_Weexow2		"Виксов"

#define STR_hMok1		"hMok"
#define STR_hMok2		"хМок"

#define STR_Threall1		"Threall"
#define STR_Threall2		"Трилл"

#define STR_Ark_a_Znoy1 	"Ark-a-Znoy"
#define STR_Ark_a_Znoy2 	"Арк-а-Зной"


// Mechoses...
#define MECH00_NAME1	"Oxidize Monk"
#define MECH00_NAME2	"Кислый Монк"

#define MECH01_NAME1	"Blade Keeper"
#define MECH01_NAME2	"Пернатый Санитар"

#define MECH02_NAME1	"Spread Spot"
#define MECH02_NAME2	"Мгновенный"

#define MECH03_NAME1	"Ripper"
#define MECH03_NAME2	"Потрошитель"

#define MECH04_NAME1	"Heavy Lady"
#define MECH04_NAME2	"Мамочка"

#define MECH05_NAME1	"Ancient Demon"
#define MECH05_NAME2	"Дряхлый Душегуб"

#define MECH06_NAME1	"Iron Shadow"
#define MECH06_NAME2	"Железный Призрак"

#define MECH07_NAME1	"AtTractor"
#define MECH07_NAME2	"атТрактор"

#define MECH08_NAME1	"Sandoll"
#define MECH08_NAME2	"Песколаз"

#define MECH09_NAME1	"Arcan"
#define MECH09_NAME2	"Арканоид"

#define MECH10_NAME1	"Mad Surgeon"
#define MECH10_NAME2	"Безумный Коновал"

#define MECH11_NAME1	"Zippax"
#define MECH11_NAME2	"Пуля"

#define MECH12_NAME1	"Rivet Bier"
#define MECH12_NAME2	"Клёпаный Гроб"

#define MECH13_NAME1	"Piercator"
#define MECH13_NAME2	"Прокалыватель"

#define MECH14_NAME1	"Excorps"
#define MECH14_NAME2	"Реаниматор"

#define MECH15_NAME1	"Last Moggy"
#define MECH15_NAME2	"Последний из Могикан"

#define MECH16_NAME1	"Queen Frog"
#define MECH16_NAME2	"Жаба"

#define MECH17_NAME1	"Lawn Mower"
#define MECH17_NAME2	"Винтокрыл"

#define MECH18_NAME1	"BLOCH"
#define MECH18_NAME2	"БЛОХ"

#define MECH19_NAME1	"SMOK"
#define MECH19_NAME2	"СМОК"

#define MECH20_NAME1	"MOTOK"
#define MECH20_NAME2	"МОТОК"

#define MECH21_NAME1	"SHROT"
#define MECH21_NAME2	"ШРОТ"

#define MECH22_NAME1	"DOCHOD"
#define MECH22_NAME2	"ДОХОД"

#define MECH23_NAME1	"Sandoll"
#define MECH23_NAME2	"Песколаз"

#define MECH24_NAME1	"Sandoll"
#define MECH24_NAME2	"Песколаз"

#define MECH25_NAME1	"Sandoll"
#define MECH25_NAME2	"Песколаз"

#define MECH26_NAME1	"Last Moggy"
#define MECH26_NAME2	"Последний из Могикан"

#define MECH27_NAME1	"Last Moggy"
#define MECH27_NAME2	"Последний из Могикан"

#define MECH28_NAME1	"Last Moggy"
#define MECH28_NAME2	"Последний из Могикан"

#define MECH29_NAME1	"Queen Frog"
#define MECH29_NAME2	"Жаба"

#define MECH30_NAME1	"Queen Frog"
#define MECH30_NAME2	"Жаба"

#define MECH31_NAME1	"Queen Frog"
#define MECH31_NAME2	"Жаба"

#define MECH32_NAME1	"Lawn Mower"
#define MECH32_NAME2	"Винтокрыл"

#define MECH33_NAME1	"Lawn Mower"
#define MECH33_NAME2	"Винтокрыл"

#define MECH34_NAME1	"Lawn Mower"
#define MECH34_NAME2	"Винтокрыл"

#define MECH35_NAME1	"Wormaster"
#define MECH35_NAME2	"Червонец"

#define MECH36_NAME1	"Wormaster"
#define MECH36_NAME2	"Червонец"

#define MECH37_NAME1	"Wormaster"
#define MECH37_NAME2	"Червонец"

#define MECH38_NAME1	"Wormaster"
#define MECH38_NAME2	"Червонец"

// Escaves...
#define ESCAVE_NAME01	"Podish"
#define ESCAVE_NAME02	"Подиш"

#define ESCAVE_NAME11	"Incubator"
#define ESCAVE_NAME12	"Инкубатор"

#define ESCAVE_NAME21	"VigBoo"
#define ESCAVE_NAME22	"ВигБу"

#define ESCAVE_NAME31	"Lampasso"
#define ESCAVE_NAME32	"Лампассы"

#define ESCAVE_NAME41	"Ogorod"
#define ESCAVE_NAME42	"Огород"

#define ESCAVE_NAME51	"ZeePa"
#define ESCAVE_NAME52	"ЦыПа"

#define ESCAVE_NAME61	"B-Zone"
#define ESCAVE_NAME62	"БиЗона"

#define ESCAVE_NAME71	"Spobs"
#define ESCAVE_NAME72	"Спобс"

