
/*
	actInt strings - Local Version
*/

// Menu strings...
#define STR_OFF 		$STR_OFF2
#define STR_MAP 		$STR_MAP2
#define STR_WMAP		$STR_WMAP2
#define STR_TARGETS		$STR_TARGETS2
#define STR_CAMERAS		$STR_CAMERAS2
#define STR_PARAMS		$STR_PARAMS2
#define STR_BOOTSECTOR		$STR_BOOTSECTOR2
#define STR_PROTRACTOR		$STR_PROTRACTOR2
#define STR_MECH_MESSIAH	$STR_MECH_MESSIAH2
#define STR_PASS_TO		$STR_PASS_TO2

// Protractor menu strings...
#define STR_Spobsion		$STR_Spobsion2
#define STR_Resizing		$STR_Resizing2
#define STR_Barrier		$STR_Barrier2
#define STR_Beebs_Festival	$STR_Beebs_Festival2
#define STR_Circus		$STR_Circus2
#define STR_Ostrich		$STR_Ostrich2
#define STR_Function83		$STR_Function832
#define STR_HyperBeacon 	$STR_HyperBeacon2

// Mech messiah menu strings...
#define STR_Cloak		$STR_Cloak2
#define STR_Luck		$STR_Luck2
#define STR_Beebsospy		$STR_Beebsospy2
#define STR_Firework		$STR_Firework2
#define STR_Shake_Up		$STR_Shake_Up2
#define STR_Blackada		$STR_Blackada2

// Function-83 menu strings (and world names)...
#define STR_Fostral		$STR_Fostral2
#define STR_Glorx		$STR_Glorx2
#define STR_Necross		$STR_Necross2
#define STR_Xplo		$STR_Xplo2
#define STR_Khox		$STR_Khox2
#define STR_Boozeena		$STR_Boozeena2
#define STR_Weexow		$STR_Weexow2
#define STR_hMok		$STR_hMok2
#define STR_Threall		$STR_Threall2
#define STR_Ark_a_Znoy		$STR_Ark_a_Znoy2

// Mechoses...
#define MECH00_NAME		$MECH00_NAME2
#define MECH01_NAME		$MECH01_NAME2
#define MECH02_NAME		$MECH02_NAME2
#define MECH03_NAME		$MECH03_NAME2
#define MECH04_NAME		$MECH04_NAME2
#define MECH05_NAME		$MECH05_NAME2
#define MECH06_NAME		$MECH06_NAME2
#define MECH07_NAME		$MECH07_NAME2
#define MECH08_NAME		$MECH08_NAME2
#define MECH09_NAME		$MECH09_NAME2
#define MECH10_NAME		$MECH10_NAME2
#define MECH11_NAME		$MECH11_NAME2
#define MECH12_NAME		$MECH12_NAME2
#define MECH13_NAME		$MECH13_NAME2
#define MECH14_NAME		$MECH14_NAME2
#define MECH15_NAME		$MECH15_NAME2
#define MECH16_NAME		$MECH16_NAME2
#define MECH17_NAME		$MECH17_NAME2
#define MECH18_NAME		$MECH18_NAME2
#define MECH19_NAME		$MECH19_NAME2
#define MECH20_NAME		$MECH20_NAME2
#define MECH21_NAME		$MECH21_NAME2
#define MECH22_NAME		$MECH22_NAME2
#define MECH23_NAME		$MECH23_NAME2
#define MECH24_NAME		$MECH24_NAME2
#define MECH25_NAME		$MECH25_NAME2
#define MECH26_NAME		$MECH26_NAME2
#define MECH27_NAME		$MECH27_NAME2
#define MECH28_NAME		$MECH28_NAME2
#define MECH29_NAME		$MECH29_NAME2
#define MECH30_NAME		$MECH30_NAME2
#define MECH31_NAME		$MECH31_NAME2
#define MECH32_NAME		$MECH32_NAME2
#define MECH33_NAME		$MECH33_NAME2
#define MECH34_NAME		$MECH34_NAME2
#define MECH35_NAME		$MECH35_NAME2
#define MECH36_NAME		$MECH36_NAME2
#define MECH37_NAME		$MECH37_NAME2
#define MECH38_NAME		$MECH38_NAME2

/* --------------------------------- ITEMS ---------------------------------- */
/* ----------------------------- NAMES SECTION ------------------------------ */

// MacHOTine Gun (light)
#define ITM01_NAME		$ITM01_NAME2

// MacHOTine Gun (heavy)
#define ITM02_NAME		$ITM02_NAME2

// Speetle System (light)
#define ITM03_NAME		$ITM03_NAME2

// Speetle System (heavy)
#define ITM04_NAME		$ITM04_NAME2

// ghOrb Gear (light)
#define ITM05_NAME		$ITM05_NAME2

// ghOrb Gear (heavy)
#define ITM06_NAME		$ITM06_NAME2

// Beebbanoza Blockade
#define ITM07_NAME		$ITM07_NAME2

// Crustest Cannon
#define ITM08_NAME		$ITM08_NAME2

// Terminator 'Wormer'
#define ITM09_NAME		$ITM09_NAME2

// Terminator 'Wasp'
#define ITM10_NAME		$ITM10_NAME2

// Pupok pile
#define ITM11_NAME		$ITM11_NAME2

// OKorOK pile
#define ITM12_NAME		$ITM12_NAME2

// Boltoon pack
#define ITM13_NAME		$ITM13_NAME2

// CopteRig
#define ITM14_NAME		$ITM14_NAME2

// CopteRig (empty)
#define ITM15_NAME		$ITM15_NAME2

// CutteRig
#define ITM16_NAME		$ITM16_NAME2

// CutteRig (empty)
#define ITM17_NAME		$ITM17_NAME2

// CrotRig
#define ITM18_NAME		$ITM18_NAME2

// CrotRig (empty)
#define ITM19_NAME		$ITM19_NAME2

// Lhark - does not exist :)
#define ITM20_NAME		$ITM20_NAME2

// Lhark - does not exist :)
#define ITM21_NAME		$ITM21_NAME2

// Vector
#define ITM22_NAME		$ITM22_NAME2

// Cirtainer
#define ITM23_NAME		$ITM23_NAME2

// Cirtainer (empty)
#define ITM24_NAME		$ITM24_NAME2

// Conlarver
#define ITM25_NAME		$ITM25_NAME2

// Conlarver (empty)
#define ITM26_NAME		$ITM26_NAME2

// Nymbos
#define ITM27_NAME		$ITM27_NAME2

// Phlegma
#define ITM28_NAME		$ITM28_NAME2

// Heroin
#define ITM29_NAME		$ITM29_NAME2

// Shrub
#define ITM30_NAME		$ITM30_NAME2

// Poponka
#define ITM31_NAME		$ITM31_NAME2

// Toxick
#define ITM32_NAME		$ITM32_NAME2

// eLeech
#define ITM33_NAME		$ITM33_NAME2

// Kernoboo
#define ITM34_NAME		$ITM34_NAME2

// Pipetka
#define ITM35_NAME		$ITM35_NAME2

// WeeZyk
#define ITM36_NAME		$ITM36_NAME2

// Protractor
#define ITM37_NAME		$ITM37_NAME2

// Mechanic Messiah
#define ITM38_NAME		$ITM38_NAME2

// Function-83+
#define ITM39_NAME		$ITM39_NAME2

// SpuMMy
#define ITM40_NAME		$ITM40_NAME2

// Leepuringa
#define ITM41_NAME		$ITM41_NAME2

// Dead eLeech
#define ITM42_NAME		$ITM42_NAME2

// Rubox
#define ITM43_NAME		$ITM43_NAME2

// Zigger-Zagger
#define ITM44_NAME		$ITM44_NAME2

// Cart
#define ITM45_NAME		$ITM45_NAME2

// Put-Put
#define ITM46_NAME		$ITM46_NAME2

// Box
#define ITM47_NAME		$ITM47_NAME2

// Rattle
#define ITM48_NAME		$ITM48_NAME2

// Heavy Iron
#define ITM49_NAME		$ITM49_NAME2

// Star
#define ITM50_NAME		$ITM50_NAME2

// Whizzer
#define ITM51_NAME		$ITM51_NAME2

// Husker
#define ITM52_NAME		$ITM52_NAME2

// Cogged Widget
#define ITM53_NAME		$ITM53_NAME2

// TankAcid
#define ITM54_NAME		$ITM54_NAME2

// Boot Sector
#define ITM56_NAME		$ITM56_NAME2

// Peelot
#define ITM55_NAME		$ITM55_NAME2

// Mechoscope
#define ITM57_NAME		$ITM57_NAME2

// Gluek
#define ITM58_NAME		$ITM58_NAME2

// Degradator
#define ITM59_NAME		$ITM59_NAME2

// Tabutask (active)
#define ITM60_NAME		$ITM60_NAME2

// Amputator
#define ITM61_NAME		$ITM61_NAME2

// Eleepod
#define ITM62_NAME		$ITM62_NAME2

// Beeboorat
#define ITM63_NAME		$ITM63_NAME2

// Zeex
#define ITM64_NAME		$ITM64_NAME2

// Palochka
#define ITM65_NAME		$ITM65_NAME2

// Pipka
#define ITM66_NAME		$ITM66_NAME2

// Nobool
#define ITM67_NAME		$ITM67_NAME2

// Boorawchick
#define ITM68_NAME		$ITM68_NAME2

// Pereponka
#define ITM69_NAME		$ITM69_NAME2

// Zeefick
#define ITM70_NAME		$ITM70_NAME2

// Dead WeeZyk
#define ITM71_NAME		$ITM71_NAME2

// Rotten Kernoboo
#define ITM72_NAME		$ITM72_NAME2

// Tabutask (failed)
#define ITM73_NAME		$ITM73_NAME2

// Tabutask (completed)
#define ITM74_NAME		$ITM74_NAME2

// Amputator (empty)
#define ITM75_NAME		$ITM75_NAME2

// Degradator (empty)
#define ITM76_NAME		$ITM76_NAME2

// Rotten Pipetka
#define ITM77_NAME		$ITM77_NAME2

// Mechoscope (empty)
#define ITM78_NAME		$ITM78_NAME2

/* ---------------------------- COMMENTS SECTION ---------------------------- */

// MacHOTine Gun (light)
#define ITM01_COMMENTS		$ITM01_COMMENTS2

// MacHOTine Gun (heavy)
#define ITM02_COMMENTS		$ITM02_COMMENTS2

// Speetle System (light)
#define ITM03_COMMENTS		$ITM03_COMMENTS2

// Speetle System (heavy)
#define ITM04_COMMENTS		$ITM04_COMMENTS2

// ghOrb Gear (light)
#define ITM05_COMMENTS		$ITM05_COMMENTS2

// ghOrb Gear (heavy)
#define ITM06_COMMENTS		$ITM06_COMMENTS2

// Beebbanoza Blockade
#define ITM07_COMMENTS		$ITM07_COMMENTS2

// Crustest Cannon
#define ITM08_COMMENTS		$ITM08_COMMENTS2

// Terminator 'Wormer'
#define ITM09_COMMENTS		$ITM09_COMMENTS2

// Terminator 'Wasp'
#define ITM10_COMMENTS		$ITM10_COMMENTS2

// Pupok pile
#define ITM11_COMMENTS		$ITM11_COMMENTS2

// OKorOK pile
#define ITM12_COMMENTS		$ITM12_COMMENTS2

// Boltoon pack
#define ITM13_COMMENTS		$ITM13_COMMENTS2

// CopteRig
#define ITM14_COMMENTS		$ITM14_COMMENTS2

// CopteRig (empty)
#define ITM15_COMMENTS		$ITM15_COMMENTS2

// CutteRig
#define ITM16_COMMENTS		$ITM16_COMMENTS2

// CutteRig (empty)
#define ITM17_COMMENTS		$ITM17_COMMENTS2

// CrotRig
#define ITM18_COMMENTS		$ITM18_COMMENTS2

// CrotRig (empty)
#define ITM19_COMMENTS		$ITM19_COMMENTS2

// Lhark - does not exist :)
#define ITM20_COMMENTS		$ITM20_COMMENTS2

// Lhark - does not exist :)
#define ITM21_COMMENTS		$ITM21_COMMENTS2

// Vector
#define ITM22_COMMENTS		$ITM22_COMMENTS2

// Cirtainer
#define ITM23_COMMENTS		$ITM23_COMMENTS2

// Cirtainer (empty)
#define ITM24_COMMENTS		$ITM24_COMMENTS2

// Conlarver
#define ITM25_COMMENTS		$ITM25_COMMENTS2

// Conlarver (empty)
#define ITM26_COMMENTS		$ITM26_COMMENTS2

// Nymbos
#define ITM27_COMMENTS		$ITM27_COMMENTS2

// Phlegma
#define ITM28_COMMENTS		$ITM28_COMMENTS2

// Heroin
#define ITM29_COMMENTS		$ITM29_COMMENTS2

// Shrub
#define ITM30_COMMENTS		$ITM30_COMMENTS2

// Poponka
#define ITM31_COMMENTS		$ITM31_COMMENTS2

// Toxick
#define ITM32_COMMENTS		$ITM32_COMMENTS2

// eLeech
#define ITM33_COMMENTS		$ITM33_COMMENTS2

// Kernoboo
#define ITM34_COMMENTS		$ITM34_COMMENTS2

// Pipetka
#define ITM35_COMMENTS		$ITM35_COMMENTS2

// WeeZyk
#define ITM36_COMMENTS		$ITM36_COMMENTS2

// Leepuringa
#define ITM41_COMMENTS		$ITM41_COMMENTS2

// Dead eLeech
#define ITM42_COMMENTS		$ITM42_COMMENTS2

// Protractor
#define ITM37_COMMENTS		$ITM37_COMMENTS2

// Mechanic Messiah
#define ITM38_COMMENTS		$ITM38_COMMENTS2

// Function-83+
#define ITM39_COMMENTS		$ITM39_COMMENTS2

// SpuMMy
#define ITM40_COMMENTS		$ITM40_COMMENTS2

// Rubox
#define ITM43_COMMENTS		$ITM43_COMMENTS2

// Zigger-Zagger
#define ITM44_COMMENTS		$ITM44_COMMENTS2

// Cart
#define ITM45_COMMENTS		$ITM45_COMMENTS2

// Put-Put
#define ITM46_COMMENTS		$ITM46_COMMENTS2

// Box
#define ITM47_COMMENTS		$ITM47_COMMENTS2

// Rattle
#define ITM48_COMMENTS		$ITM48_COMMENTS2

// Heavy Iron
#define ITM49_COMMENTS		$ITM49_COMMENTS2

// Star
#define ITM50_COMMENTS		$ITM50_COMMENTS2

// Whizzer
#define ITM51_COMMENTS		$ITM51_COMMENTS2

// Husker
#define ITM52_COMMENTS		$ITM52_COMMENTS2

// Cogged Widget
#define ITM53_COMMENTS		$ITM53_COMMENTS2

// TankAcid
#define ITM54_COMMENTS		$ITM54_COMMENTS2

// Peelot
#define ITM55_COMMENTS		$ITM55_COMMENTS2

// Boot Sector
#define ITM56_COMMENTS		$ITM56_COMMENTS2

// Mechoscope
#define ITM57_COMMENTS		$ITM57_COMMENTS2

// Gluek
#define ITM58_COMMENTS		$ITM58_COMMENTS2

// Degradator
#define ITM59_COMMENTS		$ITM59_COMMENTS2

// Tabutask (active)
#define ITM60_COMMENTS		$ITM60_COMMENTS2

// Amputator
#define ITM61_COMMENTS		$ITM61_COMMENTS2

// Eleepod
#define ITM62_COMMENTS		$ITM62_COMMENTS2

// Beeboorat
#define ITM63_COMMENTS		$ITM63_COMMENTS2

// Zeex
#define ITM64_COMMENTS		$ITM64_COMMENTS2

// Palochka
#define ITM65_COMMENTS		$ITM65_COMMENTS2

// Pipka
#define ITM66_COMMENTS		$ITM66_COMMENTS2

// Nobool
#define ITM67_COMMENTS		$ITM67_COMMENTS2

// Boorawchick
#define ITM68_COMMENTS		$ITM68_COMMENTS2

// Pereponka
#define ITM69_COMMENTS		$ITM69_COMMENTS2

// Zeefick
#define ITM70_COMMENTS		$ITM70_COMMENTS2

// Dead WeeZyk
#define ITM71_COMMENTS		$ITM71_COMMENTS2

// Rotten Kernoboo
#define ITM72_COMMENTS		$ITM72_COMMENTS2

// Tabutask (failed)
#define ITM73_COMMENTS		$ITM73_COMMENTS2

// Tabutask (completed)
#define ITM74_COMMENTS		$ITM74_COMMENTS2

// Amputator (empty)
#define ITM75_COMMENTS		$ITM75_COMMENTS2

// Degradator (empty)
#define ITM76_COMMENTS		$ITM76_COMMENTS2

// Rotten Pipetka
#define ITM77_COMMENTS		$ITM77_COMMENTS2

// Mechoscope (empty)
#define ITM78_COMMENTS		$ITM78_COMMENTS2

/* ------------------------- SHOP COMMENTS SECTION -------------------------- */

// MacHOTine Gun (light)
#define iITM01_COMMENTS 	$iITM01_COMMENTS2

// MacHOTine Gun (heavy)
#define iITM02_COMMENTS 	$iITM02_COMMENTS2

// Speetle System (light)
#define iITM03_COMMENTS 	$iITM03_COMMENTS2

// Speetle System (heavy)
#define iITM04_COMMENTS 	$iITM04_COMMENTS2

// ghOrb Gear (light)
#define iITM05_COMMENTS 	$iITM05_COMMENTS2

// ghOrb Gear (heavy)
#define iITM06_COMMENTS 	$iITM06_COMMENTS2

// Beebbanoza Blockade
#define iITM07_COMMENTS 	$iITM07_COMMENTS2

// Crustest Cannon
#define iITM08_COMMENTS 	$iITM08_COMMENTS2

// Terminator 'Wormer'
#define iITM09_COMMENTS 	$iITM09_COMMENTS2

// Terminator 'Wasp'
#define iITM10_COMMENTS 	$iITM10_COMMENTS2

// Pupok pile
#define iITM11_COMMENTS 	$iITM11_COMMENTS2

// OKorOK pile
#define iITM12_COMMENTS 	$iITM12_COMMENTS2

// Boltoon pack
#define iITM13_COMMENTS 	$iITM13_COMMENTS2

// CopteRig
#define iITM14_COMMENTS 	$iITM14_COMMENTS2

// CopteRig (empty)
#define iITM15_COMMENTS 	$iITM15_COMMENTS2

// CutteRig
#define iITM16_COMMENTS 	$iITM16_COMMENTS2

// CutteRig (empty)
#define iITM17_COMMENTS 	$iITM17_COMMENTS2

// CrotRig
#define iITM18_COMMENTS 	$iITM18_COMMENTS2

// CrotRig (empty)
#define iITM19_COMMENTS 	$iITM19_COMMENTS2

// Lhark - does not exist :)
#define iITM20_COMMENTS 	$iITM20_COMMENTS2

// Lhark - does not exist :)
#define iITM21_COMMENTS 	$iITM21_COMMENTS2

// Vector
#define iITM22_COMMENTS 	$iITM22_COMMENTS2

// Cirtainer
#define iITM23_COMMENTS 	$iITM23_COMMENTS2

// Cirtainer (empty)
#define iITM24_COMMENTS 	$iITM24_COMMENTS2

// Conlarver
#define iITM25_COMMENTS 	$iITM25_COMMENTS2

// Conlarver (empty)
#define iITM26_COMMENTS 	$iITM26_COMMENTS2

// Nymbos
#define iITM27_COMMENTS 	$iITM27_COMMENTS2

// Phlegma
#define iITM28_COMMENTS 	$iITM28_COMMENTS2

// Heroin
#define iITM29_COMMENTS 	$iITM29_COMMENTS2

// Shrub
#define iITM30_COMMENTS 	$iITM30_COMMENTS2

// Poponka
#define iITM31_COMMENTS 	$iITM31_COMMENTS2

// Toxick
#define iITM32_COMMENTS 	$iITM32_COMMENTS2

// eLeech
#define iITM33_COMMENTS 	$iITM33_COMMENTS2

// Kernoboo
#define iITM34_COMMENTS 	$iITM34_COMMENTS2

// Pipetka
#define iITM35_COMMENTS 	$iITM35_COMMENTS2

// WeeZyk
#define iITM36_COMMENTS 	$iITM36_COMMENTS2

// Protractor
#define iITM37_COMMENTS 	$iITM37_COMMENTS2

// Mechanic Messiah
#define iITM38_COMMENTS 	$iITM38_COMMENTS2

// Function-83+
#define iITM39_COMMENTS 	$iITM39_COMMENTS2

// SpuMMy
#define iITM40_COMMENTS 	$iITM40_COMMENTS2

// Leepuringa
#define iITM41_COMMENTS 	$iITM41_COMMENTS2

// Dead eLeech
#define iITM42_COMMENTS 	$iITM42_COMMENTS2

// Rubox
#define iITM43_COMMENTS 	$iITM43_COMMENTS2

// Zigger-Zagger
#define iITM44_COMMENTS 	$iITM44_COMMENTS2

// Cart
#define iITM45_COMMENTS 	$iITM45_COMMENTS2

// Put-Put
#define iITM46_COMMENTS 	$iITM46_COMMENTS2

// Box
#define iITM47_COMMENTS 	$iITM47_COMMENTS2

// Rattle
#define iITM48_COMMENTS 	$iITM48_COMMENTS2

// Heavy Iron
#define iITM49_COMMENTS 	$iITM49_COMMENTS2

// Star
#define iITM50_COMMENTS 	$iITM50_COMMENTS2

// Whizzer
#define iITM51_COMMENTS 	$iITM51_COMMENTS2

// Husker
#define iITM52_COMMENTS 	$iITM52_COMMENTS2

// Cogged Widget
#define iITM53_COMMENTS 	$iITM53_COMMENTS2

// TankAcid
#define iITM54_COMMENTS 	$iITM54_COMMENTS2

// Boot Sector
#define iITM56_COMMENTS 	$iITM56_COMMENTS2

// Peelot
#define iITM55_COMMENTS 	$iITM55_COMMENTS2

// Mechoscope
#define iITM57_COMMENTS 	$iITM57_COMMENTS2

// Gluek
#define iITM58_COMMENTS 	$iITM58_COMMENTS2

// Degradator
#define iITM59_COMMENTS 	$iITM59_COMMENTS2

// Tabutask (active)
#define iITM60_COMMENTS 	$iITM60_COMMENTS2

// Amputator
#define iITM61_COMMENTS 	$iITM61_COMMENTS2

// Eleepod
#define iITM62_COMMENTS 	$iITM62_COMMENTS2

// Beeboorat
#define iITM63_COMMENTS 	$iITM63_COMMENTS2

// Zeex
#define iITM64_COMMENTS 	$iITM64_COMMENTS2

// Palochka
#define iITM65_COMMENTS 	$iITM65_COMMENTS2

// Pipka
#define iITM66_COMMENTS 	$iITM66_COMMENTS2

// Nobool
#define iITM67_COMMENTS 	$iITM67_COMMENTS2

// Boorawchick
#define iITM68_COMMENTS 	$iITM68_COMMENTS2

// Pereponka
#define iITM69_COMMENTS 	$iITM69_COMMENTS2

// Zeefick
#define iITM70_COMMENTS 	$iITM70_COMMENTS2

// Dead WeeZyk
#define iITM71_COMMENTS 	$iITM71_COMMENTS2

// Rotten Kernoboo
#define iITM72_COMMENTS 	$iITM72_COMMENTS2

// Tabutask (failed)
#define iITM73_COMMENTS 	$iITM73_COMMENTS2

// Tabutask (completed)
#define iITM74_COMMENTS 	$iITM74_COMMENTS2

// Amputator (empty)
#define iITM75_COMMENTS 	$iITM75_COMMENTS2

// Degradator (empty)
#define iITM76_COMMENTS 	$iITM76_COMMENTS2

// Rotten Pipetka
#define iITM77_COMMENTS 	$iITM77_COMMENTS2

// Mechoscope (empty)
#define iITM78_COMMENTS 	$iITM78_COMMENTS2

/* --------------------------- ITEMS INFO SECTION --------------------------- */

// MacHOTine Gun (light)
#define ITM01_INFO		$ITM01_INFO2

// MacHOTine Gun (heavy)
#define ITM02_INFO		$ITM02_INFO2

// Speetle System (light)
#define ITM03_INFO		$ITM03_INFO2

// Speetle System (heavy)
#define ITM04_INFO		$ITM04_INFO2

// ghOrb Gear (light)
#define ITM05_INFO		$ITM05_INFO2

// ghOrb Gear (heavy)
#define ITM06_INFO		$ITM06_INFO2

// Beebbanoza Blockade
#define ITM07_INFO		$ITM07_INFO2

// Crustest Cannon
#define ITM08_INFO		$ITM08_INFO2

// Terminator 'Wormer'
#define ITM09_INFO		$ITM09_INFO2

// Terminator 'Wasp'
#define ITM10_INFO		$ITM10_INFO2

// CopteRig
#define ITM14_INFO		$ITM14_INFO2

// CopteRig (empty)
#define ITM15_INFO		$ITM15_INFO2

// CutteRig
#define ITM16_INFO		$ITM16_INFO2

// CutteRig (empty)
#define ITM17_INFO		$ITM17_INFO2

// CrotRig
#define ITM18_INFO		$ITM18_INFO2

// CrotRig (empty)
#define ITM19_INFO		$ITM19_INFO2

// Vector
#define ITM22_INFO		$ITM22_INFO2

// Cirtainer (empty)
#define ITM24_INFO		$ITM24_INFO2

// Conlarver (empty)
#define ITM26_INFO		$ITM26_INFO2

// Tabutask
#define ITM60_INFO		$ITM60_INFO2

// Poponka
#define ITM31_INFO		$ITM31_INFO2

// Protractor
#define ITM37_INFO		$ITM37_INFO2

// Mechanic Messiah
#define ITM38_INFO		$ITM38_INFO2

// Function-83+
#define ITM39_INFO		$ITM39_INFO2

// Boot Sector
#define ITM56_INFO		$ITM56_INFO2

// Peelot
#define ITM55_INFO		$ITM55_INFO2

// Mechoscope(empty)
#define ITM75_INFO		$ITM75_INFO2

// Gluek
#define ITM58_INFO		$ITM58_INFO2

// Degradator(empty)
#define ITM76_INFO		$ITM76_INFO2

// Amputator(empty)
#define ITM78_INFO		$ITM78_INFO2

// Eleepod
#define ITM62_INFO		$ITM62_INFO2

// Beeboorat
#define ITM63_INFO		$ITM63_INFO2

// Zeex
#define ITM64_INFO		$ITM64_INFO2

/* --------------------------- PARAMETERS SECTION --------------------------- */

// MacHOTine Gun (light)
#define ITM01_PARAMS		$ITM01_PARAMS2

// MacHOTine Gun (heavy)
#define ITM02_PARAMS		$ITM02_PARAMS2

// Speetle System (light)
#define ITM03_PARAMS		$ITM03_PARAMS2

// Speetle System (heavy)
#define ITM04_PARAMS		$ITM04_PARAMS2

// ghOrb Gear (light)
#define ITM05_PARAMS		$ITM05_PARAMS2

// ghOrb Gear (heavy)
#define ITM06_PARAMS		$ITM06_PARAMS2

// Beebbanoza Blockade
#define ITM07_PARAMS		$ITM07_PARAMS2

// Crustest Cannon
#define ITM08_PARAMS		$ITM08_PARAMS2

// Terminator 'Wormer'
#define ITM09_PARAMS		$ITM09_PARAMS2

// Terminator 'Wasp'
#define ITM10_PARAMS		$ITM10_PARAMS2

// Pupok pile
#define ITM11_PARAMS		$ITM11_PARAMS2

// OKorOK pile
#define ITM12_PARAMS		$ITM12_PARAMS2

// Boltoon pack
#define ITM13_PARAMS		$ITM13_PARAMS2

// CopteRig
#define ITM14_PARAMS		$ITM14_PARAMS2

// CopteRig (empty)
#define ITM15_PARAMS		$ITM15_PARAMS2

// CutteRig
#define ITM16_PARAMS		$ITM16_PARAMS2

// CutteRig (empty)
#define ITM17_PARAMS		$ITM17_PARAMS2

// CrotRig
#define ITM18_PARAMS		$ITM18_PARAMS2

// CrotRig (empty)
#define ITM19_PARAMS		$ITM19_PARAMS2

// Lhark - does not exist :)
#define ITM20_PARAMS		$ITM20_PARAMS2

// Lhark - does not exist :)
#define ITM21_PARAMS		$ITM21_PARAMS2

// Vector
#define ITM22_PARAMS		$ITM22_PARAMS2

// Cirtainer
#define ITM23_PARAMS		$ITM23_PARAMS2

// Cirtainer (empty)
#define ITM24_PARAMS		$ITM24_PARAMS2

// Conlarver
#define ITM25_PARAMS		$ITM25_PARAMS2

// Conlarver (empty)
#define ITM26_PARAMS		$ITM26_PARAMS2

// Nymbos
#define ITM27_PARAMS		$ITM27_PARAMS2

// Phlegma
#define ITM28_PARAMS		$ITM28_PARAMS2

// Heroin
#define ITM29_PARAMS		$ITM29_PARAMS2

// Shrub
#define ITM30_PARAMS		$ITM30_PARAMS2

// Poponka
#define ITM31_PARAMS		$ITM31_PARAMS2

// Toxick
#define ITM32_PARAMS		$ITM32_PARAMS2

// eLeech
#define ITM33_PARAMS		$ITM33_PARAMS2

// Kernoboo
#define ITM34_PARAMS		$ITM34_PARAMS2

// Pipetka
#define ITM35_PARAMS		$ITM35_PARAMS2

// WeeZyk
#define ITM36_PARAMS		$ITM36_PARAMS2

// Protractor
#define ITM37_PARAMS		$ITM37_PARAMS2

// Mechanic Messiah
#define ITM38_PARAMS		$ITM38_PARAMS2

// Function-83+
#define ITM39_PARAMS		$ITM39_PARAMS2

// SpuMMy
#define ITM40_PARAMS		$ITM40_PARAMS2

// Leepuringa
#define ITM41_PARAMS		$ITM41_PARAMS2

// Dead eLeech
#define ITM42_PARAMS		$ITM42_PARAMS2

// Rubox
#define ITM43_PARAMS		$ITM43_PARAMS2

// Zigger-Zagger
#define ITM44_PARAMS		$ITM44_PARAMS2

// Cart
#define ITM45_PARAMS		$ITM45_PARAMS2

// Put-Put
#define ITM46_PARAMS		$ITM46_PARAMS2

// Box
#define ITM47_PARAMS		$ITM47_PARAMS2

// Rattle
#define ITM48_PARAMS		$ITM48_PARAMS2

// Heavy Iron
#define ITM49_PARAMS		$ITM49_PARAMS2

// Star
#define ITM50_PARAMS		$ITM50_PARAMS2

// Whizzer
#define ITM51_PARAMS		$ITM51_PARAMS2

// Husker
#define ITM52_PARAMS		$ITM52_PARAMS2

// Cogged Widget
#define ITM53_PARAMS		$ITM53_PARAMS2

// TankAcid
#define ITM54_PARAMS		$ITM54_PARAMS2

// Boot Sector
#define ITM56_PARAMS		$ITM56_PARAMS2

// Peelot
#define ITM55_PARAMS		$ITM55_PARAMS2

// Mechoscope
#define ITM57_PARAMS		$ITM57_PARAMS2

// Gluek
#define ITM58_PARAMS		$ITM58_PARAMS2

// Degradator
#define ITM59_PARAMS		$ITM59_PARAMS2

// Tabutask (active)
#define ITM60_PARAMS		$ITM60_PARAMS2

// Amputator
#define ITM61_PARAMS		$ITM61_PARAMS2

// Eleepod
#define ITM62_PARAMS		$ITM62_PARAMS2

// Beeboorat
#define ITM63_PARAMS		$ITM63_PARAMS2

// Zeex
#define ITM64_PARAMS		$ITM64_PARAMS2

// Palochka
#define ITM65_PARAMS		$ITM65_PARAMS2

// Pipka
#define ITM66_PARAMS		$ITM66_PARAMS2

// Nobool
#define ITM67_PARAMS		$ITM67_PARAMS2

// Boorawchick
#define ITM68_PARAMS		$ITM68_PARAMS2

// Pereponka
#define ITM69_PARAMS		$ITM69_PARAMS2

// Zeefick
#define ITM70_PARAMS		$ITM70_PARAMS2

// Dead WeeZyk
#define ITM71_PARAMS		$ITM71_PARAMS2

// Rotten Kernoboo
#define ITM72_PARAMS		$ITM72_PARAMS2

// Tabutask (failed)
#define ITM73_PARAMS		$ITM73_PARAMS2

// Tabutask (completed)
#define ITM74_PARAMS		$ITM74_PARAMS2

// Amputator (empty)
#define ITM75_PARAMS		$ITM75_PARAMS2

// Degradator (empty)
#define ITM76_PARAMS		$ITM76_PARAMS2

// Rotten Pipetka
#define ITM77_PARAMS		$ITM77_PARAMS2

// Mechoscope (empty)
#define ITM78_PARAMS		$ITM78_PARAMS2

// Tips...
#define MODE_BUTTON_TEXT		$MODE_BUTTON_TEXT2
#define PICKUP_ITEMS_BUTTON_TEXT	$PICKUP_ITEMS_BUTTON_TEXT2
#define PICKUP_WEAPONS_BUTTON_TEXT	$PICKUP_WEAPONS_BUTTON_TEXT2
#define ESCAVE_BUTTON_TEXT		$ESCAVE_BUTTON_TEXT2
#define ENERGY_IND_TEXT 		$ENERGY_IND_TEXT2
#define LOAD_IND_TEXT			$LOAD_IND_TEXT2
#define POWERUP_IND_TEXT		$POWERUP_IND_TEXT2
#define SPIRAL_IND_TEXT 		$SPIRAL_IND_TEXT2

// Escaves...
#define ESCAVE_NAME0		$ESCAVE_NAME02
#define ESCAVE_NAME1		$ESCAVE_NAME12
#define ESCAVE_NAME2		$ESCAVE_NAME22
#define ESCAVE_NAME3		$ESCAVE_NAME32
#define ESCAVE_NAME4		$ESCAVE_NAME42
#define ESCAVE_NAME5		$ESCAVE_NAME52
#define ESCAVE_NAME6		$ESCAVE_NAME62
#define ESCAVE_NAME7		$ESCAVE_NAME72

