
/* ---------------------------- ISCREEN SECTION ----------------------------- */

#include "actint/escaves.inc"

#define SHUTTER_DELTA_X 	20
#define SHUTTER_DELTA_Y 	20

#define MSHUTTER_DELTA_X	40
#define MSHUTTER_DELTA_Y	60

iscreen_section {
	cell_size	36

/* ----------------------------- ITEMS SECTION ------------------------------ */

	invItem $ITM01_NAME
		$ITM01
		$iITM01_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm01.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm01.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm01.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm01r.avi"
		no_show_shots
	}
	invItem $ITM02_NAME
		$ITM02
		$iITM02_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm02.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm02.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm02.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm02r.avi"
		no_show_shots
	}
	invItem $ITM03_NAME
		$ITM03
		$iITM03_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm03.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm03.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm03.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm03r.avi"
		no_show_shots
	}
	invItem $ITM04_NAME
		$ITM04
		$iITM04_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm04.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm04.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm04.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm04r.avi"
		no_show_shots
	}
	invItem $ITM05_NAME
		$ITM05
		$iITM05_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm05.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm05.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm05.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm05r.avi"
		no_show_shots
	}
	invItem $ITM06_NAME
		$ITM06
		$iITM06_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm06.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm06.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm06.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm06r.avi"
		no_show_shots
	}
	invItem $ITM07_NAME
		$ITM07
		$iITM07_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm07.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm07.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm07.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm07r.avi"
		no_show_shots
	}
	invItem $ITM08_NAME
		$ITM08
		$iITM08_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm08.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm08.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm08.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm08r.avi"
		no_show_shots
	}
	invItem $ITM09_NAME
		$ITM09
		$iITM09_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm09.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm09.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm09.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm09r.avi"
		no_show_shots
	}
	invItem $ITM10_NAME
		$ITM10
		$iITM10_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm10.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm10.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm10.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm10r.avi"
		no_show_shots
	}
	invItem $ITM11_NAME
		$ITM11
		$iITM11_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm11.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm11.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm11.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm11r.avi"
	}
	invItem $ITM12_NAME
		$ITM12
		$iITM12_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm12.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm12.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm12.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm12r.avi"
	}
	invItem $ITM13_NAME
		$ITM13
		$iITM13_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm13.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm13.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm13.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm13r.avi"
	}
	invItem $ITM14_NAME
		$ITM14
		$iITM14_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm14.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm14.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm14.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm14r.avi"
	}
	invItem $ITM15_NAME
		$ITM15
		$iITM15_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm15.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm15.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm14.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm14r.avi"
	}
	invItem $ITM16_NAME
		$ITM16
		$iITM16_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm16.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm16.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm16.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm16r.avi"
	}
	invItem $ITM17_NAME
		$ITM17
		$iITM17_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm17.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm17.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm16.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm16r.avi"
	}
	invItem $ITM18_NAME
		$ITM18
		$iITM18_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm18.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm18.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm18.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm18r.avi"
	}
	invItem $ITM19_NAME
		$ITM19
		$iITM19_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm19.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm19.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm18.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm18r.avi"
	}
	invItem $ITM20_NAME
		$ITM20
		$iITM20_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm20.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm20.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm20.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm20r.avi"
	}
	invItem $ITM21_NAME
		$ITM21
		$iITM21_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm21.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm21.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm21.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm21r.avi"
	}
	invItem $ITM22_NAME
		$ITM22
		$iITM22_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm22.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm22.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm22.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm22r.avi"
	}
	invItem $ITM23_NAME
		$ITM23
		$iITM23_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm23.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm24.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm24.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm24r.avi"
	}
	invItem $ITM24_NAME
		$ITM24
		$iITM24_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm24.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm24.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm24.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm24r.avi"
	}
	invItem $ITM25_NAME
		$ITM25
		$iITM25_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm25.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm25.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm26.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm26r.avi"
	}
	invItem $ITM26_NAME
		$ITM26
		$iITM26_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm26.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm26.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm26.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm26r.avi"
	}
	invItem $ITM27_NAME
		$ITM27
		$iITM27_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm27.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm27.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm27.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm27r.avi"
	}
	invItem $ITM28_NAME
		$ITM28
		$iITM28_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm28.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm28.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm28.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm28r.avi"
	}
	invItem $ITM29_NAME
		$ITM29
		$iITM29_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm29.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm29.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm29.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm29r.avi"
	}
	invItem $ITM30_NAME
		$ITM30
		$iITM30_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm30.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm30.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm30.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm30r.avi"
	}
	invItem $ITM31_NAME
		$ITM31
		$iITM31_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm31.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm31.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm31.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm31r.avi"
	}
	invItem $ITM32_NAME
		$ITM32
		$iITM32_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm32.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm32.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm32.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm32r.avi"
	}
	invItem $ITM33_NAME
		$ITM33
		$iITM33_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm33.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm33.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm33.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm33r.avi"
	}
	invItem $ITM34_NAME
		$ITM34
		$iITM34_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm34.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm34.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm34.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm34r.avi"
	}
	invItem $ITM35_NAME
		$ITM35
		$iITM35_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm35.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm35.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm35.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm35r.avi"
	}
	invItem $ITM36_NAME
		$ITM36
		$iITM36_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm36.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm36.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm36.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm36r.avi"
	}
	invItem $ITM37_NAME
		$ITM37
		$iITM37_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm37.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm37.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm37.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm37r.avi"
	}
	invItem $ITM38_NAME
		$ITM38
		$iITM38_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm38.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm38.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm38.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm38r.avi"
	}
	invItem $ITM39_NAME
		$ITM39
		$iITM39_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm39.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm39.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm39.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm39r.avi"
	}
	invItem $ITM40_NAME
		$ITM40
		$iITM40_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm40.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm40.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm40.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm40r.avi"
	}
	invItem $ITM41_NAME
		$ITM41
		$iITM41_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm41.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm41.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm41.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm41r.avi"
	}
	invItem $ITM42_NAME
		$ITM42
		$iITM42_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm42.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm42.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm42.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm42r.avi"
	}
	invItem $ITM43_NAME
		$ITM43
		$iITM43_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm43.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm43.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm43.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm43r.avi"
	}
	invItem $ITM44_NAME
		$ITM44
		$iITM44_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm44.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm44.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm44.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm44r.avi"
	}
	invItem $ITM45_NAME
		$ITM45
		$iITM45_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm45.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm45.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm45.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm45r.avi"
	}
	invItem $ITM46_NAME
		$ITM46
		$iITM46_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm46.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm46.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm46.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm46r.avi"
	}
	invItem $ITM47_NAME
		$ITM47
		$iITM47_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm47.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm47.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm47.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm47r.avi"
	}
	invItem $ITM48_NAME
		$ITM48
		$iITM48_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm48.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm48.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm48.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm48r.avi"
	}
	invItem $ITM49_NAME
		$ITM49
		$iITM49_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm49.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm49.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm49.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm49r.avi"
	}
	invItem $ITM50_NAME
		$ITM50
		$iITM50_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm50.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm50.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm50.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm50r.avi"
	}
	invItem $ITM51_NAME
		$ITM51
		$iITM51_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm51.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm51.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm51.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm51r.avi"
	}
	invItem $ITM52_NAME
		$ITM52
		$iITM52_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm52.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm52.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm52.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm52r.avi"
	}
	invItem $ITM53_NAME
		$ITM53
		$iITM53_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm53.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm53.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm53.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm53r.avi"
	}
	invItem $ITM54_NAME
		$ITM54
		$iITM54_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm54.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm54.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm54.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm54r.avi"
	}
	invItem $ITM55_NAME
		$ITM55
		$iITM55_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm55.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm55.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm55.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm55r.avi"
	}
	invItem $ITM56_NAME
		$ITM56
		$iITM56_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm56.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm56.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm56.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm56r.avi"
	}
	invItem $ITM57_NAME
		$ITM57
		$iITM57_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm57.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm57.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm57.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm57r.avi"
	}
	invItem $ITM58_NAME
		$ITM58
		$iITM58_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm58.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm58.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm58.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm58r.avi"
	}
	invItem $ITM59_NAME
		$ITM59
		$iITM59_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm59.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm59.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm59.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm59r.avi"
	}
	invItem $ITM60_NAME
		$ITM60
		$iITM60_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm60.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm60.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm60.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm60r.avi"
	}
	invItem $ITM61_NAME
		$ITM61
		$iITM61_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm61.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm61.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm61.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm61r.avi"
	}
	invItem $ITM62_NAME
		$ITM62
		$iITM62_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm62.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm62.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm62.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm62r.avi"
	}
	invItem $ITM63_NAME
		$ITM63
		$iITM63_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm63.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm63.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm63.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm63r.avi"
	}
	invItem $ITM64_NAME
		$ITM64
		$iITM64_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm64.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm64.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm64.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm64r.avi"
	}
	invItem $ITM65_NAME
		$ITM65
		$iITM65_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm65.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm65.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm65.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm65r.avi"
	}
	invItem $ITM66_NAME
		$ITM66
		$iITM66_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm66.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm66.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm66.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm66r.avi"
	}
	invItem $ITM67_NAME
		$ITM67
		$iITM67_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm67.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm67.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm67.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm67r.avi"
	}
	invItem $ITM68_NAME
		$ITM68
		$iITM68_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm68.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm68.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm68.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm68r.avi"
	}
	invItem $ITM69_NAME
		$ITM69
		$iITM69_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm69.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm69.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm69.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm69r.avi"
	}
	invItem $ITM70_NAME
		$ITM70
		$iITM70_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm70.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm70.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm70.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm70r.avi"
	}
	invItem $ITM71_NAME
		$ITM71
		$iITM71_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm71.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm71.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm71.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm71r.avi"
	}
	invItem $ITM72_NAME
		$ITM72
		$iITM72_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm72.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm72.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm72.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm72r.avi"
	}
	invItem $ITM73_NAME
		$ITM73
		$iITM73_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm74.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm60.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm60.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm60r.avi"
	}
	invItem $ITM74_NAME
		$ITM74
		$iITM74_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm73.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm60.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm60.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm60r.avi"
	}
	invItem $ITM75_NAME
		$ITM75
		$iITM75_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm75.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm61.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm61.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm61r.avi"
	}
	invItem $ITM76_NAME
		$ITM76
		$iITM76_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm76.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm59.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm59.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm59r.avi"
	}
	invItem $ITM77_NAME
		$ITM77
		$iITM77_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm77.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm77.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm77.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm77r.avi"
	}
	invItem $ITM78_NAME
		$ITM78
		$iITM78_COMMENTS
		bmp_file	"resource/actint/iscreen/items/itm78.bmp"
		num_avi_ids	3
		avi_id		$ACI_PICTURE_AVI_ENG	"items/itm57.avi"
		avi_id		$ACI_TEXT_AVI_ENG	"items/text/itm57.avi"
		avi_id		$ACI_TEXT_AVI_RUS	"items/text/itm57r.avi"
	}

/* -------------------------------------------------------------------------- */

	info_panel {
		x	460
		y	465

		size_x	332
		size_y	112

		range_font
		font	1
	}

	info_panel {
		id		$ACI_ANSWER_PANEL
		back_col	0

//		  vspace	  0

		vspace		-2
		hspace		1

		range_font
		font		$ACI_PHRASE_FONT

		max_str 	5
	}

	info_panel {
		id	$ACI_SHOP_TIME_PANEL

		no_align

		info_offs_x	5
		info_offs_y	10

		hspace		2
		vspace		10

		back_col	0

		range_font
		font	1
	}

	info_panel {
		id	$ACI_PRICE_PANEL

		hspace	1
		vspace	-1

		range_font
		font	1
	}
	counter INV_COUNTER {
		id	$ACI_CREDITS_PANEL

		x	476
		y	16

		font	2
		range_font

		size_x	100
		size_y	40
	}

	invMatrix $MECH00_ID {
		$iMATRIX_HIRES
		$MATRIX00_BODY
	}
	invMatrix $MECH01_ID {
		$iMATRIX_HIRES
		$MATRIX01_BODY
	}
	invMatrix $MECH02_ID {
		$iMATRIX_HIRES
		$MATRIX02_BODY
	}
	invMatrix $MECH03_ID {
		$iMATRIX_HIRES
		$MATRIX03_BODY
	}
	invMatrix $MECH04_ID {
		$iMATRIX_HIRES
		$MATRIX04_BODY
	}
	invMatrix $MECH05_ID {
		$iMATRIX_HIRES
		$MATRIX05_BODY
	}
	invMatrix $MECH06_ID {
		$iMATRIX_HIRES
		$MATRIX06_BODY
	}
	invMatrix $MECH07_ID {
		$iMATRIX_HIRES
		$MATRIX07_BODY
	}
	invMatrix $MECH08_ID {
		$iMATRIX_HIRES
		$MATRIX08_BODY
	}
	invMatrix $MECH09_ID {
		$iMATRIX_HIRES
		$MATRIX09_BODY
	}
	invMatrix $MECH10_ID {
		$iMATRIX_HIRES
		$MATRIX10_BODY
	}
	invMatrix $MECH11_ID {
		$iMATRIX_HIRES
		$MATRIX11_BODY
	}
	invMatrix $MECH12_ID {
		$iMATRIX_HIRES
		$MATRIX12_BODY
	}
	invMatrix $MECH13_ID {
		$iMATRIX_HIRES
		$MATRIX13_BODY
	}
	invMatrix $MECH14_ID {
		$iMATRIX_HIRES
		$MATRIX14_BODY
	}
	invMatrix $MECH15_ID {
		$iMATRIX_HIRES
		$MATRIX15_BODY
	}
	invMatrix $MECH16_ID {
		$iMATRIX_HIRES
		$MATRIX16_BODY
	}
	invMatrix $MECH17_ID {
		$iMATRIX_HIRES
		$MATRIX17_BODY
	}
	invMatrix $MECH18_ID {
		$iMATRIX_HIRES
		$MATRIX18_BODY
	}
	invMatrix $MECH19_ID {
		$iMATRIX_HIRES
		$MATRIX19_BODY
	}
	invMatrix $MECH20_ID {
		$iMATRIX_HIRES
		$MATRIX20_BODY
	}
	invMatrix $MECH21_ID {
		$iMATRIX_HIRES
		$MATRIX21_BODY
	}
	invMatrix $MECH22_ID {
		$iMATRIX_HIRES
		$MATRIX22_BODY
	}
	invMatrix $MECH23_ID {
		$iMATRIX_HIRES
		$MATRIX23_BODY
	}
	invMatrix $MECH24_ID {
		$iMATRIX_HIRES
		$MATRIX24_BODY
	}
	invMatrix $MECH25_ID {
		$iMATRIX_HIRES
		$MATRIX25_BODY
	}
	invMatrix $MECH26_ID {
		$iMATRIX_HIRES
		$MATRIX26_BODY
	}
	invMatrix $MECH27_ID {
		$iMATRIX_HIRES
		$MATRIX27_BODY
	}
	invMatrix $MECH28_ID {
		$iMATRIX_HIRES
		$MATRIX28_BODY
	}
	invMatrix $MECH29_ID {
		$iMATRIX_HIRES
		$MATRIX29_BODY
	}
	invMatrix $MECH30_ID {
		$iMATRIX_HIRES
		$MATRIX30_BODY
	}
	invMatrix $MECH31_ID {
		$iMATRIX_HIRES
		$MATRIX31_BODY
	}
	invMatrix $MECH32_ID {
		$iMATRIX_HIRES
		$MATRIX32_BODY
	}
	invMatrix $MECH33_ID {
		$iMATRIX_HIRES
		$MATRIX33_BODY
	}
	invMatrix $MECH34_ID {
		$iMATRIX_HIRES
		$MATRIX34_BODY
	}
	invMatrix $MECH35_ID {
		$iMATRIX_HIRES
		$MATRIX35_BODY
	}
	invMatrix $MECH36_ID {
		$iMATRIX_HIRES
		$MATRIX36_BODY
	}
	invMatrix $MECH37_ID {
		$iMATRIX_HIRES
		$MATRIX37_BODY
	}
	invMatrix $MECH38_ID {
		$iMATRIX_HIRES
		$MATRIX38_BODY
	}

	fncMenu {
		menu_type	$SHOP_ITEMS_MENU_ID

		no_deactivate

		x	49
		y	145

		size_x	364
		size_y	266

		range_font
		cur_function	0

		back_col	0
	}
	fncMenu {
		menu_type	$ACI_QUEST_MENU

		back_col	0

		no_deactivate
		location_menu

		cur_function	0

		visible_items	3
	}

	// Podish...
	location_data $ESCAVE_ID0 {
		name		$_ESCAVE_NAME0
		map_name	"resource/iscreen/ldata/l0/escave.ini"
		palette 	"resource/iscreen/ldata/l0/escave.pal"

		sounds		"resource/iscreen/ldata/l0/sound"

//		  map_data	  "resource/iscreen/ldata/l0/map_data/data1.bmo"

		screen_id	"LocScreen00"

		exclude_item	$ACI_LEEPURINGA
		exclude_item	$ACI_TABUTASK
		exclude_item	$ACI_TABUTASK_FAILED
		exclude_item	$ACI_TABUTASK_SUCCESSFUL
		exclude_item	$ACI_ELEEPOD
		exclude_item	$ACI_BEEBOORAT
		exclude_item	$ACI_ZEEX

		exclude_item	$ACI_ROTTEN_KERNOBOO
		exclude_item	$ACI_ROTTEN_PIPETKA
		exclude_item	$ACI_ROTTEN_WEEZYK
		exclude_item	$ACI_DEAD_ELEECH

		exclude_item	$ACI_ELEECH
		exclude_item	$ACI_KERNOBOO
		exclude_item	$ACI_PIPETKA
		exclude_item	$ACI_WEEZYK
		exclude_item	$ACI_BOORAWCHICK

		num_index	$ACI_BUTTON_OFF_TYPE	3
		num_index	$ACI_BUTTON_ON_TYPE	6

		save_screen	3
		world		$FOSTRAL_ID

		num_gate_shutters	1
		gate_shutter 0 {
			pos 0	$ACI_SHUTTER_CENTER	0
			pos 1	$ACI_SHUTTER_CENTER	$ACI_SHUTTER_LEFT

			pos 2	$ACI_SHUTTER_CENTER	$ACI_SHUTTER_LEFT
			pos 3	$ACI_SHUTTER_CENTER	0

			delta	0	$SHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l0/bitmap/g0.bmp"
		}

		num_matrix_shutters	1	1
		matrix_shutter 1 0 {
			pos 0	0	0
			pos 1	0	$ACI_SHUTTER_LEFT

			pos 2	0	$ACI_SHUTTER_LEFT
			pos 3	0	0

			delta	0	$MSHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l0/bitmap/shp1.bmp"
		}
		num_matrix_shutters	2	1
		matrix_shutter 2 0 {
			pos 0	$ACI_SHUTTER_RIGHT	0
			pos 1	$ACI_SHUTTER_RIGHT	600

			pos 2	$ACI_SHUTTER_RIGHT	600
			pos 3	$ACI_SHUTTER_RIGHT	0

			delta	0	$MSHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l0/bitmap/shp2.bmp"
		}

		id	$ACI_SHOP_SCREEN_ID		"LocScreen00Shop"
		id	$ACI_PRICE_PANEL_ID		"PricePanelBMP"
		id	$ACI_MATRIX_BORDER_ID		"MatrixBorder"
		id	$ACI_SMATRIX_BORDER_ID		"sMatrixBorder"
		id	$ACI_MECHOS_ID_OBJ		"MechNameObj"
		id	$ACI_MECHOS_ID_STR		"MechNameStr"
		id	$ACI_MECHOS_AVI_ID		"AVI Element"
		id	$ACI_TRIGGER_ID 		"TRIG00"
		id	$ACI_INFO_PANEL_ID		"InfoPanelBMP"
		id	$ACI_CREDITS_PANEL_ID		"CreditsBMP"

		id	$ACI_ITEMS_MENU_ID		"ItemsMenuBMP"
		id	$ACI_AVI_OBJ_ID 		"Avi00"

		id	$ACI_WEAPONS_BUTTON_ID		"Button06el"
		id	$ACI_MECHOS_BUTTON_ID		"Button07el"
		id	$ACI_ITEMS_BUTTON_ID		"Button08el"
		id	$ACI_MENU_BUTTON_ID		"Button11el"

		s_id	$ACI_QUEST_PANEL_ID		"QuestPanelBMP"
		s_id	$ACI_ANSWER_PANEL_ID		"AnswerPanelBMP"
		s_id	$ACI_TIME_PANEL_ID		"TimePanelBMP"
	}
	// Incubator...
	location_data $ESCAVE_ID1 {
		name		$_ESCAVE_NAME1
		map_name	"resource/iscreen/ldata/l1/escave.ini"
		palette 	"resource/iscreen/ldata/l1/escave.pal"
		screen_id	"LocScreen01"

		sounds		"resource/iscreen/ldata/l1/sound"

		save_screen	3
		world		$FOSTRAL_ID

		exclude_item	$ACI_TABUTASK
		exclude_item	$ACI_TABUTASK_FAILED
		exclude_item	$ACI_TABUTASK_SUCCESSFUL
		exclude_item	$ACI_ELEEPOD
		exclude_item	$ACI_BEEBOORAT
		exclude_item	$ACI_ZEEX

		exclude_item	$ACI_ROTTEN_KERNOBOO
		exclude_item	$ACI_ROTTEN_PIPETKA
		exclude_item	$ACI_ROTTEN_WEEZYK
		exclude_item	$ACI_DEAD_ELEECH

		exclude_item	$ACI_ELEECH
		exclude_item	$ACI_KERNOBOO
		exclude_item	$ACI_PIPETKA
		exclude_item	$ACI_WEEZYK
		exclude_item	$ACI_BOORAWCHICK

		num_index	$ACI_BUTTON_OFF_TYPE	3
		num_index	$ACI_BUTTON_ON_TYPE	6

		num_gate_shutters	1
		gate_shutter 0 {
			pos 0	$ACI_SHUTTER_CENTER	0
			pos 1	$ACI_SHUTTER_CENTER	$ACI_SHUTTER_LEFT

			pos 2	$ACI_SHUTTER_CENTER	$ACI_SHUTTER_LEFT
			pos 3	$ACI_SHUTTER_CENTER	0

			delta	0	$SHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l1/bitmap/g0.bmp"
		}
		num_matrix_shutters	1	1
		matrix_shutter 1 0 {
			pos 0	0	0
			pos 1	0	$ACI_SHUTTER_LEFT

			pos 2	0	$ACI_SHUTTER_LEFT
			pos 3	0	0

			delta	0	$MSHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l0/bitmap/shp1.bmp"
		}
		num_matrix_shutters	2	1
		matrix_shutter 2 0 {
			pos 0	$ACI_SHUTTER_RIGHT	0
			pos 1	$ACI_SHUTTER_RIGHT	600

			pos 2	$ACI_SHUTTER_RIGHT	600
			pos 3	$ACI_SHUTTER_RIGHT	0

			delta	0	$MSHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l0/bitmap/shp2.bmp"
		}

		id	$ACI_SHOP_SCREEN_ID		"LocScreen01Shop"
		id	$ACI_PRICE_PANEL_ID		"PricePanelBMP"
		id	$ACI_MATRIX_BORDER_ID		"MatrixBorder"
		id	$ACI_SMATRIX_BORDER_ID		"sMatrixBorder"
		id	$ACI_MECHOS_ID_OBJ		"MechNameObj"
		id	$ACI_MECHOS_ID_STR		"MechNameStr"
		id	$ACI_MECHOS_AVI_ID		"AVI Element"
		id	$ACI_TRIGGER_ID 		"TRIG00"
		id	$ACI_INFO_PANEL_ID		"InfoPanelBMP"
		id	$ACI_CREDITS_PANEL_ID		"CreditsBMP"

		id	$ACI_ITEMS_MENU_ID		"ItemsMenuBMP"
		id	$ACI_AVI_OBJ_ID 		"Avi00"

		id	$ACI_WEAPONS_BUTTON_ID		"Button06el"
		id	$ACI_MECHOS_BUTTON_ID		"Button07el"
		id	$ACI_ITEMS_BUTTON_ID		"Button08el"
		id	$ACI_MENU_BUTTON_ID		"Button11el"

		s_id	$ACI_QUEST_PANEL_ID		"QuestPanelBMP"
		s_id	$ACI_ANSWER_PANEL_ID		"AnswerPanelBMP"
		s_id	$ACI_TIME_PANEL_ID		"TimePanelBMP"
	}
	// VigBoo...
	location_data $ESCAVE_ID2 {
		name		$_ESCAVE_NAME2
		map_name	"resource/iscreen/ldata/l2/escave.ini"
		palette 	"resource/iscreen/ldata/l2/escave.pal"
		screen_id	"LocScreen02"

		sounds		"resource/iscreen/ldata/l2/sound"

		save_screen	4
		world		$GLORX_ID

		exclude_item	$ACI_TABUTASK
		exclude_item	$ACI_TABUTASK_FAILED
		exclude_item	$ACI_TABUTASK_SUCCESSFUL
		exclude_item	$ACI_ELEEPOD
		exclude_item	$ACI_BEEBOORAT
		exclude_item	$ACI_ZEEX

		exclude_item	$ACI_ROTTEN_KERNOBOO
		exclude_item	$ACI_ROTTEN_PIPETKA
		exclude_item	$ACI_ROTTEN_WEEZYK
		exclude_item	$ACI_DEAD_ELEECH

		exclude_item	$ACI_ELEECH
		exclude_item	$ACI_KERNOBOO
		exclude_item	$ACI_PIPETKA
		exclude_item	$ACI_WEEZYK
		exclude_item	$ACI_BOORAWCHICK

		num_index	$ACI_BUTTON_OFF_TYPE	1
		num_index	$ACI_BUTTON_ON_TYPE	6

		num_gate_shutters	2
		gate_shutter 0 {
			pos 0	0			$ACI_SHUTTER_CENTER
			pos 1	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER

			pos 2	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER
			pos 3	0			$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l2/bitmap/g0.bmp"
		}
		gate_shutter 1 {
			pos 0	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER
			pos 1	800			$ACI_SHUTTER_CENTER

			pos 2	800			$ACI_SHUTTER_CENTER
			pos 3	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l2/bitmap/g1.bmp"
		}
		num_matrix_shutters	1	1
		matrix_shutter 1 0 {
			pos 0	0			$ACI_SHUTTER_CENTER
			pos 1	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER

			pos 2	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER
			pos 3	0			$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l2/bitmap/g0.bmp"
		}
		num_matrix_shutters	2	1
		matrix_shutter 2 0 {
			pos 0	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER
			pos 1	800			$ACI_SHUTTER_CENTER

			pos 2	800			$ACI_SHUTTER_CENTER
			pos 3	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l2/bitmap/g1.bmp"
		}

		id	$ACI_SHOP_SCREEN_ID		"LocScreen02Shop"
		id	$ACI_PRICE_PANEL_ID		"PricePanelBMP"
		id	$ACI_MATRIX_BORDER_ID		"MatrixBorder"
		id	$ACI_SMATRIX_BORDER_ID		"sMatrixBorder"
		id	$ACI_MECHOS_ID_OBJ		"MechNameObj"
		id	$ACI_MECHOS_ID_STR		"MechNameStr"
		id	$ACI_MECHOS_AVI_ID		"AVI Element"
		id	$ACI_TRIGGER_ID 		"TRIG00"
		id	$ACI_INFO_PANEL_ID		"InfoPanelBMP"
		id	$ACI_CREDITS_PANEL_ID		"CreditsBMP"

		id	$ACI_ITEMS_MENU_ID		"ItemsMenuBMP"
		id	$ACI_AVI_OBJ_ID 		"Avi00"

		id	$ACI_WEAPONS_BUTTON_ID		"Button06el"
		id	$ACI_MECHOS_BUTTON_ID		"Button07el"
		id	$ACI_ITEMS_BUTTON_ID		"Button08el"
		id	$ACI_MENU_BUTTON_ID		"Button11el"

		s_id	$ACI_QUEST_PANEL_ID		"QuestPanelBMP"
		s_id	$ACI_ANSWER_PANEL_ID		"AnswerPanelBMP"
		s_id	$ACI_TIME_PANEL_ID		"TimePanelBMP"
	}
	// Lampasso...
	location_data $ESCAVE_ID3 {
		name		$_ESCAVE_NAME3
		map_name	"resource/iscreen/ldata/l3/escave.ini"
		palette 	"resource/iscreen/ldata/l3/escave.pal"
		screen_id	"LocScreen03"

		sounds		"resource/iscreen/ldata/l3/sound"

		save_screen	4
		world		$GLORX_ID

		exclude_item	$ACI_TABUTASK
		exclude_item	$ACI_TABUTASK_FAILED
		exclude_item	$ACI_TABUTASK_SUCCESSFUL
		exclude_item	$ACI_ELEEPOD
		exclude_item	$ACI_BEEBOORAT
		exclude_item	$ACI_ZEEX

		exclude_item	$ACI_ROTTEN_KERNOBOO
		exclude_item	$ACI_ROTTEN_PIPETKA
		exclude_item	$ACI_ROTTEN_WEEZYK
		exclude_item	$ACI_DEAD_ELEECH

		exclude_item	$ACI_ELEECH
		exclude_item	$ACI_KERNOBOO
		exclude_item	$ACI_PIPETKA
		exclude_item	$ACI_WEEZYK
		exclude_item	$ACI_BOORAWCHICK

		num_index	$ACI_BUTTON_OFF_TYPE	1
		num_index	$ACI_BUTTON_ON_TYPE	6

		num_gate_shutters	2
		gate_shutter 0 {
			pos 0	0			$ACI_SHUTTER_CENTER
			pos 1	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER

			pos 2	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER
			pos 3	0			$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l3/bitmap/g0.bmp"
		}
		gate_shutter 1 {
			pos 0	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER
			pos 1	800			$ACI_SHUTTER_CENTER

			pos 2	800			$ACI_SHUTTER_CENTER
			pos 3	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l3/bitmap/g1.bmp"
		}
		num_matrix_shutters	1	1
		matrix_shutter 1 0 {
			pos 0	0			$ACI_SHUTTER_CENTER
			pos 1	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER

			pos 2	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER
			pos 3	0			$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l3/bitmap/g0.bmp"
		}
		num_matrix_shutters	2	1
		matrix_shutter 2 0 {
			pos 0	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER
			pos 1	800			$ACI_SHUTTER_CENTER

			pos 2	800			$ACI_SHUTTER_CENTER
			pos 3	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l3/bitmap/g1.bmp"
		}

		id	$ACI_SHOP_SCREEN_ID		"LocScreen03Shop"
		id	$ACI_PRICE_PANEL_ID		"PricePanelBMP"
		id	$ACI_MATRIX_BORDER_ID		"MatrixBorder"
		id	$ACI_SMATRIX_BORDER_ID		"sMatrixBorder"
		id	$ACI_MECHOS_ID_OBJ		"MechNameObj"
		id	$ACI_MECHOS_ID_STR		"MechNameStr"
		id	$ACI_MECHOS_AVI_ID		"AVI Element"
		id	$ACI_TRIGGER_ID 		"TRIG00"
		id	$ACI_INFO_PANEL_ID		"InfoPanelBMP"
		id	$ACI_CREDITS_PANEL_ID		"CreditsBMP"

		id	$ACI_ITEMS_MENU_ID		"ItemsMenuBMP"
		id	$ACI_AVI_OBJ_ID 		"Avi00"

		id	$ACI_WEAPONS_BUTTON_ID		"Button06el"
		id	$ACI_MECHOS_BUTTON_ID		"Button07el"
		id	$ACI_ITEMS_BUTTON_ID		"Button08el"
		id	$ACI_MENU_BUTTON_ID		"Button11el"

		s_id	$ACI_QUEST_PANEL_ID		"QuestPanelBMP"
		s_id	$ACI_ANSWER_PANEL_ID		"AnswerPanelBMP"
		s_id	$ACI_TIME_PANEL_ID		"TimePanelBMP"
	}
	// Ogorod...
	location_data $ESCAVE_ID4 {
		name		$_ESCAVE_NAME4
		map_name	"resource/iscreen/ldata/l4/escave.ini"
		palette 	"resource/iscreen/ldata/l4/escave.pal"
		screen_id	"LocScreen04"

		sounds		"resource/iscreen/ldata/l4/sound"

		save_screen	4
		world		$GLORX_ID

		exclude_item	$ACI_TABUTASK
		exclude_item	$ACI_TABUTASK_FAILED
		exclude_item	$ACI_TABUTASK_SUCCESSFUL
		exclude_item	$ACI_ELEEPOD
		exclude_item	$ACI_BEEBOORAT
		exclude_item	$ACI_ZEEX

		exclude_item	$ACI_ROTTEN_KERNOBOO
		exclude_item	$ACI_ROTTEN_PIPETKA
		exclude_item	$ACI_ROTTEN_WEEZYK
		exclude_item	$ACI_DEAD_ELEECH

		exclude_item	$ACI_ELEECH
		exclude_item	$ACI_KERNOBOO
		exclude_item	$ACI_PIPETKA
		exclude_item	$ACI_WEEZYK
		exclude_item	$ACI_BOORAWCHICK

		num_index	$ACI_BUTTON_OFF_TYPE	1
		num_index	$ACI_BUTTON_ON_TYPE	6

		num_gate_shutters	2
		gate_shutter 0 {
			pos 0	0			$ACI_SHUTTER_CENTER
			pos 1	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER

			pos 2	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER
			pos 3	0			$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l4/bitmap/g0.bmp"
		}
		gate_shutter 1 {
			pos 0	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER
			pos 1	800			$ACI_SHUTTER_CENTER

			pos 2	800			$ACI_SHUTTER_CENTER
			pos 3	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l4/bitmap/g1.bmp"
		}
		num_matrix_shutters	1	1
		matrix_shutter 1 0 {
			pos 0	0			$ACI_SHUTTER_CENTER
			pos 1	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER

			pos 2	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER
			pos 3	0			$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l4/bitmap/g0.bmp"
		}
		num_matrix_shutters	2	1
		matrix_shutter 2 0 {
			pos 0	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER
			pos 1	800			$ACI_SHUTTER_CENTER

			pos 2	800			$ACI_SHUTTER_CENTER
			pos 3	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l4/bitmap/g1.bmp"
		}

		id	$ACI_SHOP_SCREEN_ID		"LocScreen04Shop"
		id	$ACI_PRICE_PANEL_ID		"PricePanelBMP"
		id	$ACI_MATRIX_BORDER_ID		"MatrixBorder"
		id	$ACI_SMATRIX_BORDER_ID		"sMatrixBorder"
		id	$ACI_MECHOS_ID_OBJ		"MechNameObj"
		id	$ACI_MECHOS_ID_STR		"MechNameStr"
		id	$ACI_MECHOS_AVI_ID		"AVI Element"
		id	$ACI_TRIGGER_ID 		"TRIG00"
		id	$ACI_INFO_PANEL_ID		"InfoPanelBMP"
		id	$ACI_CREDITS_PANEL_ID		"CreditsBMP"

		id	$ACI_ITEMS_MENU_ID		"ItemsMenuBMP"
		id	$ACI_AVI_OBJ_ID 		"Avi00"

		id	$ACI_WEAPONS_BUTTON_ID		"Button06el"
		id	$ACI_MECHOS_BUTTON_ID		"Button07el"
		id	$ACI_ITEMS_BUTTON_ID		"Button08el"
		id	$ACI_MENU_BUTTON_ID		"Button11el"

		s_id	$ACI_QUEST_PANEL_ID		"QuestPanelBMP"
		s_id	$ACI_ANSWER_PANEL_ID		"AnswerPanelBMP"
		s_id	$ACI_TIME_PANEL_ID		"TimePanelBMP"
	}
	// ZeePa
	location_data $ESCAVE_ID5 {
		name		$_ESCAVE_NAME5
		map_name	"resource/iscreen/ldata/l5/escave.ini"
		palette 	"resource/iscreen/ldata/l5/escave.pal"
		screen_id	"LocScreen05"

		sounds		"resource/iscreen/ldata/l5/sound"

		save_screen	5
		world		$NECROSS_ID

		exclude_item	$ACI_TABUTASK
		exclude_item	$ACI_TABUTASK_FAILED
		exclude_item	$ACI_TABUTASK_SUCCESSFUL
		exclude_item	$ACI_ELEEPOD
		exclude_item	$ACI_BEEBOORAT
		exclude_item	$ACI_ZEEX

		exclude_item	$ACI_ROTTEN_KERNOBOO
		exclude_item	$ACI_ROTTEN_PIPETKA
		exclude_item	$ACI_ROTTEN_WEEZYK
		exclude_item	$ACI_DEAD_ELEECH

		exclude_item	$ACI_ELEECH
		exclude_item	$ACI_KERNOBOO
		exclude_item	$ACI_PIPETKA
		exclude_item	$ACI_WEEZYK
		exclude_item	$ACI_BOORAWCHICK

		num_index	$ACI_BUTTON_OFF_TYPE	2
		num_index	$ACI_BUTTON_ON_TYPE	6

		num_gate_shutters	1
		gate_shutter 0 {
			pos 0	$ACI_SHUTTER_CENTER	0
			pos 1	$ACI_SHUTTER_CENTER	600

			pos 2	$ACI_SHUTTER_CENTER	$ACI_SHUTTER_LEFT
			pos 3	$ACI_SHUTTER_CENTER	0

			delta	0	$SHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l5/bitmap/g0.bmp"
		}
		num_matrix_shutters	1	1
		matrix_shutter 1 0 {
			pos 0	0	0
			pos 1	0	600

			pos 2	0	-1200
			pos 3	0	0

			delta	0	$MSHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l5/bitmap/s0.bmp"
		}
		num_matrix_shutters	2	1
		matrix_shutter 2 0 {
			pos 0	$ACI_SHUTTER_RIGHT	0
			pos 1	$ACI_SHUTTER_RIGHT	600

			pos 2	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_LEFT
			pos 3	$ACI_SHUTTER_RIGHT	0

			delta	0	$MSHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l5/bitmap/s0.bmp"
		}

		id	$ACI_SHOP_SCREEN_ID		"LocScreen05Shop"
		id	$ACI_PRICE_PANEL_ID		"PricePanelBMP"
		id	$ACI_MATRIX_BORDER_ID		"MatrixBorder"
		id	$ACI_SMATRIX_BORDER_ID		"sMatrixBorder"
		id	$ACI_MECHOS_ID_OBJ		"MechNameObj"
		id	$ACI_MECHOS_ID_STR		"MechNameStr"
		id	$ACI_MECHOS_AVI_ID		"AVI Element"
		id	$ACI_TRIGGER_ID 		"TRIG00"
		id	$ACI_INFO_PANEL_ID		"InfoPanelBMP"
		id	$ACI_CREDITS_PANEL_ID		"CreditsBMP"

		id	$ACI_ITEMS_MENU_ID		"ItemsMenuBMP"
		id	$ACI_AVI_OBJ_ID 		"Avi00"

		id	$ACI_WEAPONS_BUTTON_ID		"Button06el"
		id	$ACI_MECHOS_BUTTON_ID		"Button07el"
		id	$ACI_ITEMS_BUTTON_ID		"Button08el"
		id	$ACI_MENU_BUTTON_ID		"Button11el"

		s_id	$ACI_QUEST_PANEL_ID		"QuestPanelBMP"
		s_id	$ACI_ANSWER_PANEL_ID		"AnswerPanelBMP"
		s_id	$ACI_TIME_PANEL_ID		"TimePanelBMP"
	}
	// B-Zone
	location_data $ESCAVE_ID6 {
		name		$_ESCAVE_NAME6
		map_name	"resource/iscreen/ldata/l6/escave.ini"
		palette 	"resource/iscreen/ldata/l6/escave.pal"
		screen_id	"LocScreen06"

		sounds		"resource/iscreen/ldata/l6/sound"

		save_screen	5
		world		$NECROSS_ID

		exclude_item	$ACI_TABUTASK
		exclude_item	$ACI_TABUTASK_FAILED
		exclude_item	$ACI_TABUTASK_SUCCESSFUL
		exclude_item	$ACI_ELEEPOD
		exclude_item	$ACI_BEEBOORAT
		exclude_item	$ACI_ZEEX

		exclude_item	$ACI_ROTTEN_KERNOBOO
		exclude_item	$ACI_ROTTEN_PIPETKA
		exclude_item	$ACI_ROTTEN_WEEZYK
		exclude_item	$ACI_DEAD_ELEECH

		exclude_item	$ACI_ELEECH
		exclude_item	$ACI_KERNOBOO
		exclude_item	$ACI_PIPETKA
		exclude_item	$ACI_WEEZYK
		exclude_item	$ACI_BOORAWCHICK

		num_index	$ACI_BUTTON_OFF_TYPE	2
		num_index	$ACI_BUTTON_ON_TYPE	6

		num_gate_shutters	1
		gate_shutter 0 {
			pos 0	$ACI_SHUTTER_CENTER	0
			pos 1	$ACI_SHUTTER_CENTER	600

			pos 2	$ACI_SHUTTER_CENTER	$ACI_SHUTTER_LEFT
			pos 3	$ACI_SHUTTER_CENTER	0

			delta	0	$SHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l6/bitmap/g0.bmp"
		}
		num_matrix_shutters	1	1
		matrix_shutter 1 0 {
			pos 0	0	0
			pos 1	0	$ACI_SHUTTER_LEFT

			pos 2	0	$ACI_SHUTTER_LEFT
			pos 3	0	0

			delta	0	$MSHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l5/bitmap/s0.bmp"
		}
		num_matrix_shutters	2	1
		matrix_shutter 2 0 {
			pos 0	$ACI_SHUTTER_RIGHT	0
			pos 1	$ACI_SHUTTER_RIGHT	600

			pos 2	$ACI_SHUTTER_RIGHT	600
			pos 3	$ACI_SHUTTER_RIGHT	0

			delta	0	$MSHUTTER_DELTA_Y

			name	"resource/iscreen/ldata/l5/bitmap/s0.bmp"
		}

		id	$ACI_SHOP_SCREEN_ID		"LocScreen06Shop"
		id	$ACI_PRICE_PANEL_ID		"PricePanelBMP"
		id	$ACI_MATRIX_BORDER_ID		"MatrixBorder"
		id	$ACI_SMATRIX_BORDER_ID		"sMatrixBorder"
		id	$ACI_MECHOS_ID_OBJ		"MechNameObj"
		id	$ACI_MECHOS_ID_STR		"MechNameStr"
		id	$ACI_MECHOS_AVI_ID		"AVI Element"
		id	$ACI_TRIGGER_ID 		"TRIG00"
		id	$ACI_INFO_PANEL_ID		"InfoPanelBMP"
		id	$ACI_CREDITS_PANEL_ID		"CreditsBMP"

		id	$ACI_ITEMS_MENU_ID		"ItemsMenuBMP"
		id	$ACI_AVI_OBJ_ID 		"Avi00"

		id	$ACI_WEAPONS_BUTTON_ID		"Button06el"
		id	$ACI_MECHOS_BUTTON_ID		"Button07el"
		id	$ACI_ITEMS_BUTTON_ID		"Button08el"
		id	$ACI_MENU_BUTTON_ID		"Button11el"

		s_id	$ACI_QUEST_PANEL_ID		"QuestPanelBMP"
		s_id	$ACI_ANSWER_PANEL_ID		"AnswerPanelBMP"
		s_id	$ACI_TIME_PANEL_ID		"TimePanelBMP"
	}
	// Spobs...
	location_data $ESCAVE_ID7 {
		name		$_ESCAVE_NAME7
		map_name	"resource/iscreen/ldata/l7/escave.ini"
		palette 	"resource/iscreen/ldata/l7/escave.pal"
		screen_id	"LocScreen07"

		world		$XPLO_ID
		sounds		"resource/iscreen/ldata/l7/sound"

		num_gate_shutters	2
		gate_shutter 0 {
			pos 0	0			$ACI_SHUTTER_CENTER
			pos 1	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER

			pos 2	$ACI_SHUTTER_LEFT	$ACI_SHUTTER_CENTER
			pos 3	0			$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l7/bitmap/g00.bmp"
		}
		gate_shutter 1 {
			pos 0	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER
			pos 1	800			$ACI_SHUTTER_CENTER

			pos 2	800			$ACI_SHUTTER_CENTER
			pos 3	$ACI_SHUTTER_RIGHT	$ACI_SHUTTER_CENTER

			delta	$SHUTTER_DELTA_X	0

			name	"resource/iscreen/ldata/l7/bitmap/g01.bmp"
		}

		s_id	$ACI_QUEST_PANEL_ID		"QuestPanelBMP"
		s_id	$ACI_ANSWER_PANEL_ID		"AnswerPanelBMP"
		s_id	$ACI_TIME_PANEL_ID		"TimePanelBMP"
	}
}

/* ------------------------- END OF ISCREEN SECTION ------------------------- */

