
#define STR_SX			250
#define STR_SY			32

#define STR_DX			10
#define STR_DY			35
#define VOLUME_DX		20

#define STR_X			220

#define STR_SX_TXT		200
#define STR_SX2 		120

#define STR_SOUND_X		160
#define STR_SOUND_SX		90
#define STR_SOUND_SX2		50

#define STR_MUSIC_X		160
#define STR_MUSIC_SX		90
#define STR_MUSIC_SX2		50

#define STR_TUTORIAL_X		230
#define STR_TUTORIAL_SX 	90
#define STR_TUTORIAL_SX2	50

#define STR_AUTORUN_X		210
#define STR_AUTORUN_SX		115
#define STR_AUTORUN_SX2 	50

#define acsSTR_GAME_PAUSED	$acsSTR_GAME_PAUSED1
#define acsSTR_SOUND		$acsSTR_SOUND1
#define acsSTR_MUSIC		$acsSTR_MUSIC1
#define acsSTR_TIPS		$acsSTR_TIPS1
#define acsSTR_AUTORUN		$acsSTR_AUTORUN1
#define acsSTR_RESUME_GAME	$acsSTR_RESUME_GAME1
#define acsSTR_ABORT_GAME	$acsSTR_ABORT_GAME1
#define acsSTR_SAVE_GAME	$acsSTR_SAVE_GAME1


