
#define acsSTR_GAME_PAUSED1	"GAME PAUSED"
#define acsSTR_GAME_PAUSED2	"€“‡€"

#define acsSTR_SOUND1		"SOUND"
#define acsSTR_SOUND2		"‡‚“Š"

#define acsSTR_MUSIC1		"MUSIC"
#define acsSTR_MUSIC2		"Œ“‡›Š€"

#define acsSTR_TIPS1		"TIPS"
#define acsSTR_TIPS2		"„‘Š€‡Šˆ"

#define acsSTR_AUTORUN1 	"AUTORUN"
#define acsSTR_AUTORUN2 	"€‚’“‘Š…ˆ…"

#define acsSTR_RESUME_GAME1	"RESUME GAME"
#define acsSTR_RESUME_GAME2	"„‹†ˆ’œ ˆƒ“"

#define acsSTR_ABORT_GAME1	"ABORT GAME"
#define acsSTR_ABORT_GAME2	"…‚€’œ ˆƒ“"

#define acsSTR_SAVE_GAME1	"SAVE GAME"
#define acsSTR_SAVE_GAME2	"‘•€ˆ’œ ˆƒ“"

