
#define STR_SX			250
#define STR_SY			32

#define STR_DX			10
#define STR_DY			35
#define VOLUME_DX		0

#define STR_X			220

#define STR_SX_TXT		200
#define STR_SX2 		120

#define STR_SOUND_X		150
#define STR_SOUND_SX		100
#define STR_SOUND_SX2		80

#define STR_MUSIC_X		140
#define STR_MUSIC_SX		110
#define STR_MUSIC_SX2		80

#define STR_TUTORIAL_X		200
#define STR_TUTORIAL_SX 	155
#define STR_TUTORIAL_SX2	80

#define STR_AUTORUN_X		150
#define STR_AUTORUN_SX		215
#define STR_AUTORUN_SX2 	80

#define acsSTR_GAME_PAUSED	$acsSTR_GAME_PAUSED2
#define acsSTR_SOUND		$acsSTR_SOUND2
#define acsSTR_MUSIC		$acsSTR_MUSIC2
#define acsSTR_TIPS		$acsSTR_TIPS2
#define acsSTR_AUTORUN		$acsSTR_AUTORUN2
#define acsSTR_RESUME_GAME	$acsSTR_RESUME_GAME2
#define acsSTR_ABORT_GAME	$acsSTR_ABORT_GAME2
#define acsSTR_SAVE_GAME	$acsSTR_SAVE_GAME2

