
/* ----------------------------- NAMES SECTION ------------------------------ */

// MacHOTine Gun (light)
#define ITM01_NAME1	"MacHOTine Gun"
#define ITM01_NAME2	"Махотин"

// MacHOTine Gun (heavy)
#define ITM02_NAME1	"MacHOTine Gun"
#define ITM02_NAME2	"Махотин"

// Speetle System (light)
#define ITM03_NAME1	"Speetle System"
#define ITM03_NAME2	"Спитл Система"

// Speetle System (heavy)
#define ITM04_NAME1	"Speetle System"
#define ITM04_NAME2	"Спитл Система"

// ghOrb Gear (light)
#define ITM05_NAME1	"ghOrb Gear"
#define ITM05_NAME2	"гОрб Генератор"

// ghOrb Gear (heavy)
#define ITM06_NAME1	"ghOrb Gear"
#define ITM06_NAME2	"гОрб Генератор"

// Beebbanoza Blockade
#define ITM07_NAME1	"Beebbanoza Blockade"
#define ITM07_NAME2	"Биббанозная Блокада"

// Crustest Cannon
#define ITM08_NAME1	"Crustest Cannon"
#define ITM08_NAME2	"Крастест Мортира"

// Terminator 'Wormer'
#define ITM09_NAME1	"Terminator (Wormer)"
#define ITM09_NAME2	"Терминатор (Выползок)"

// Terminator 'Wasp'
#define ITM10_NAME1	"Terminator (Wasp)"
#define ITM10_NAME2	"Терминатор (Овод)"

// Pupok pile
#define ITM11_NAME1	"Pupok pile"
#define ITM11_NAME2	"Пупки"

// OKorOK pile
#define ITM12_NAME1	"OKorOK pile"
#define ITM12_NAME2	"ОКорОКа"

// Boltoon pack
#define ITM13_NAME1	"Boltoon pack"
#define ITM13_NAME2	"Болтуны"

// CopteRig
#define ITM14_NAME1	"CopteRig"
#define ITM14_NAME2	"КоптеРиг"

// CopteRig (empty)
#define ITM15_NAME1	"CopteRig"
#define ITM15_NAME2	"КоптеРиг"

// CutteRig
#define ITM16_NAME1	"CutteRig"
#define ITM16_NAME2	"КаттеРиг"

// CutteRig (empty)
#define ITM17_NAME1	"CutteRig"
#define ITM17_NAME2	"КаттеРиг"

// CrotRig
#define ITM18_NAME1	"CrotRig"
#define ITM18_NAME2	"КротРиг"

// CrotRig (empty)
#define ITM19_NAME1	"CrotRig"
#define ITM19_NAME2	"КротРиг"

// Lhark - does not exist :)
#define ITM20_NAME1	"Lhark"
#define ITM20_NAME2	"Lhark"

// Lhark - does not exist :)
#define ITM21_NAME1	"Lhark"
#define ITM21_NAME2	"Lhark"

// Vector
#define ITM22_NAME1	"Vector"
#define ITM22_NAME2	"Вектор"

// Cirtainer
#define ITM23_NAME1	"Cirtainer"
#define ITM23_NAME2	"Нюхонтейнер"

// Cirtainer (empty)
#define ITM24_NAME1	"Cirtainer"
#define ITM24_NAME2	"Нюхонтейнер"

// Conlarver
#define ITM25_NAME1	"Conlarver"
#define ITM25_NAME2	"Куккиш"

// Conlarver (empty)
#define ITM26_NAME1	"Conlarver"
#define ITM26_NAME2	"Куккиш"

// Nymbos
#define ITM27_NAME1	"Nymbos"
#define ITM27_NAME2	"Нимбос"

// Phlegma
#define ITM28_NAME1	"Phlegma"
#define ITM28_NAME2	"Флегма"

// Heroin
#define ITM29_NAME1	"Valorin"
#define ITM29_NAME2	"Героин"

// Shrub
#define ITM30_NAME1	"Shrub"
#define ITM30_NAME2	"Куст"

// Poponka
#define ITM31_NAME1	"Poponka"
#define ITM31_NAME2	"Попонка"

// Toxick
#define ITM32_NAME1	"Toxick"
#define ITM32_NAME2	"Токсик"

// eLeech
#define ITM33_NAME1	"eLeech"
#define ITM33_NAME2	"эЛик"

// Kernoboo
#define ITM34_NAME1	"Kernoboo"
#define ITM34_NAME2	"Ядробус"

// Pipetka
#define ITM35_NAME1	"Pipetka"
#define ITM35_NAME2	"Пипетка"

// WeeZyk
#define ITM36_NAME1	"WeeZyk"
#define ITM36_NAME2	"Маленький Цык"

// Protractor
#define ITM37_NAME1	"Protractor"
#define ITM37_NAME2	"Начертатель"

// Mechanic Messiah
#define ITM38_NAME1	"Mechanic Messiah"
#define ITM38_NAME2	"Механический Мессия"

// Function-83+
#define ITM39_NAME1	"Function-83+"
#define ITM39_NAME2	"Способ-83+"

// SpuMMy
#define ITM40_NAME1	"SpuMMy"
#define ITM40_NAME2	"Спумия"

// Leepuringa
#define ITM41_NAME1	"Leepuringa"
#define ITM41_NAME2	"Липуринга"

// Dead eLeech
#define ITM42_NAME1	"Some stinking mess"
#define ITM42_NAME2	"Нечто вонючее"

// Rubox
#define ITM43_NAME1	"Rubbox"
#define ITM43_NAME2	"Раббокс"

// Zigger-Zagger
#define ITM44_NAME1	"Zigger-Zagger"
#define ITM44_NAME2	"Погремушка"

// Cart
#define ITM45_NAME1	"Cart"
#define ITM45_NAME2	"Тележка"

// Put-Put
#define ITM46_NAME1	"Put-Put"
#define ITM46_NAME2	"Моторчик"

// Box
#define ITM47_NAME1	"Box"
#define ITM47_NAME2	"Коробка"

// Rattle
#define ITM48_NAME1	"Rattle"
#define ITM48_NAME2	"Трещётка"

// Heavy Iron
#define ITM49_NAME1	"Heavy Iron"
#define ITM49_NAME2	"Тяжёлая железка"

// Star
#define ITM50_NAME1	"Star"
#define ITM50_NAME2	"Звёздочка"

// Whizzer
#define ITM51_NAME1	"Whizzer"
#define ITM51_NAME2	"Вертушка"

// Husker
#define ITM52_NAME1	"Husker"
#define ITM52_NAME2	"Молотилка"

// Cogged Widget
#define ITM53_NAME1	"Cogged Widget"
#define ITM53_NAME2	"Ерунда с зубчиками"

// TankAcid
#define ITM54_NAME1	"Tankacid"
#define ITM54_NAME2	"Танкацид"

// Boot Sector
#define ITM56_NAME1	"Boot Sector"
#define ITM56_NAME2	"Бут Сектор"

// Peelot
#define ITM55_NAME1	"Peelot"
#define ITM55_NAME2	"Пилот"

// Mechoscope
#define ITM57_NAME1	"Incarnator"
#define ITM57_NAME2	"Инкарнатор"

// Gluek
#define ITM58_NAME1	"Gluek"
#define ITM58_NAME2	"Глюк"

// Degradator
#define ITM59_NAME1	"Degradator"
#define ITM59_NAME2	"Деградатор"

// Tabutask (active)
#define ITM60_NAME1	"Tabutask"
#define ITM60_NAME2	"Табутаск"

// Amputator
#define ITM61_NAME1	"Amputator"
#define ITM61_NAME2	"Ампутатор"

// Eleepod
#define ITM62_NAME1	"Eleepod"
#define ITM62_NAME2	"Элипод"

// Beeboorat
#define ITM63_NAME1	"Beeboorat"
#define ITM63_NAME2	"Бибурат"

// Zeex
#define ITM64_NAME1	"Zeex"
#define ITM64_NAME2	"Цикса"

// Palochka
#define ITM65_NAME1	"Paloch'ka"
#define ITM65_NAME2	"Палочка"

// Pipka
#define ITM66_NAME1	"Pipka"
#define ITM66_NAME2	"Пипка"

// Nobool
#define ITM67_NAME1	"Nobool"
#define ITM67_NAME2	"Дробус"

// Boorawchick
#define ITM68_NAME1	"Boorawchick"
#define ITM68_NAME2	"Буравчик"

// Pereponka
#define ITM69_NAME1	"Pereponka"
#define ITM69_NAME2	"Перепонка"

// Zeefick
#define ITM70_NAME1	"Zeefick"
#define ITM70_NAME2	"Цифик"

// Dead WeeZyk
#define ITM71_NAME1	"Some clay debris"
#define ITM71_NAME2	"Глиняные черепки"

// Rotten Kernoboo
#define ITM72_NAME1	"Some stinking pulp"
#define ITM72_NAME2	"Вонючая кашица"

// Tabutask (failed)
#define ITM73_NAME1	"Tabutask"
#define ITM73_NAME2	"Табутаск"

// Tabutask (completed)
#define ITM74_NAME1	"Tabutask"
#define ITM74_NAME2	"Табутаск"

// Amputator (empty)
#define ITM75_NAME1	"Amputator"
#define ITM75_NAME2	"Ампутатор"

// Degradator (empty)
#define ITM76_NAME1	"Degradator"
#define ITM76_NAME2	"Деградатор"

// Rotten Pipetka
#define ITM77_NAME1	"Some rotten stuff"
#define ITM77_NAME2	"Куча гнилья"

// Mechoscope (empty)
#define ITM78_NAME1	"Incarnator"
#define ITM78_NAME2	"Инкарнатор"

/* ---------------------------- COMMENTS SECTION ---------------------------- */

// MacHOTine Gun (light)
#define ITM01_COMMENTS1 comments 1 "Softie's weapon (light model)"
#define ITM01_COMMENTS2 comments 1 "Оружие софти (лёгкая модель)"

// MacHOTine Gun (heavy)
#define ITM02_COMMENTS1 comments 1 "Softie's weapon (heavy model)"
#define ITM02_COMMENTS2 comments 1 "Оружие софти (тяжёлая модель)"

// Speetle System (light)
#define ITM03_COMMENTS1 comments 1 "Softie's weapon (light model)"
#define ITM03_COMMENTS2 comments 1 "Оружие софти (лёгкая модель)"

// Speetle System (heavy)
#define ITM04_COMMENTS1 comments 1 "Softie's weapon (heavy model)"
#define ITM04_COMMENTS2 comments 1 "Оружие софти (тяжёлая модель)"

// ghOrb Gear (light)
#define ITM05_COMMENTS1 comments 1 "Spirits' weapon (light model)"
#define ITM05_COMMENTS2 comments 1 "Оружие спиритов (лёгкая модель)"

// ghOrb Gear (heavy)
#define ITM06_COMMENTS1 comments 1 "Spirits' weapon (heavy model)"
#define ITM06_COMMENTS2 comments 1 "Оружие спиритов (тяжёлая модель)"

// Beebbanoza Blockade
#define ITM07_COMMENTS1 comments 1 "A weapon of a Transmundane Bios"
#define ITM07_COMMENTS2 comments 1 "Оружие Ушедших Биосов"

// Crustest Cannon
#define ITM08_COMMENTS1 comments 1 "Softie's weapon"
#define ITM08_COMMENTS2 comments 1 "Оружие софти"

// Terminator 'Wormer'
#define ITM09_COMMENTS1 comments 1 "Cryspoid weapon"
#define ITM09_COMMENTS2 comments 1 "Криспоидное оружие"

// Terminator 'Wasp'
#define ITM10_COMMENTS1 comments 1 "Cryspoid weapon"
#define ITM10_COMMENTS2 comments 1 "Криспоидное оружие"

// Pupok pile
#define ITM11_COMMENTS1 comments 1 "Projectiles for Speetle System"
#define ITM11_COMMENTS2 comments 1 "Боеприпас для Спитл Системы"

// OKorOK pile
#define ITM12_COMMENTS1 comments 1 "Cruise missiles for Speettle Sys."
#define ITM12_COMMENTS2 comments 2 "Самонаводящиеся боеприпасы" \
				   "для Спитл Системы"

// Boltoon pack
#define ITM13_COMMENTS1 comments 1 "Bombs for Crustest Cannon"
#define ITM13_COMMENTS2 comments 1 "Бомбы для Крастест Мортиры"

// CopteRig
#define ITM14_COMMENTS1 comments 1 "Flight gadget for mechos"
#define ITM14_COMMENTS2 comments 1 "Устройство для полёта"

// CopteRig (empty)
#define ITM15_COMMENTS1 comments 1 "Discharged"
#define ITM15_COMMENTS2 comments 1 "Разряжен"

// CutteRig
#define ITM16_COMMENTS1 comments 1 "Amphibian gadget for mechos"
#define ITM16_COMMENTS2 comments 1 "Устройство для плавания"

// CutteRig (empty)
#define ITM17_COMMENTS1 comments 1 "Discharged"
#define ITM17_COMMENTS2 comments 1 "Разряжен"

// CrotRig
#define ITM18_COMMENTS1 comments 1 "'Mole' gadget for mechos"
#define ITM18_COMMENTS2 comments 1 "Устройство для закапывания"

// CrotRig (empty)
#define ITM19_COMMENTS1 comments 1 "Discharged"
#define ITM19_COMMENTS2 comments 1 "Разряжен"

// Lhark - does not exist :)
#define ITM20_COMMENTS1 comments 1 "Lhark"
#define ITM20_COMMENTS2 comments 1 "Lhark"

// Lhark - does not exist :)
#define ITM21_COMMENTS1 comments 2 "Lhark" \
				   "(discharged)"

#define ITM21_COMMENTS2 comments 2 "Lhark" \
				   "(discharged)"

// Vector
#define ITM22_COMMENTS1 comments 1 "Target tracking device"
#define ITM22_COMMENTS2 comments 2 "Прибор для наведения" \
				   "оружия на цель"

// Cirtainer
#define ITM23_COMMENTS1 comments 1 "Container whith cirt"
#define ITM23_COMMENTS2 comments 1 "Контейнер с нюхой"

// Cirtainer (empty)
#define ITM24_COMMENTS1 comments 2 "Empty container for cirt" \
				   "delivery"

#define ITM24_COMMENTS2 comments 2 "Контейнер для сбора" \
				   "и доставки нюхи"

// Conlarver
#define ITM25_COMMENTS1 comments 1 "Container with Larva"
#define ITM25_COMMENTS2 comments 1 "Контейнер с Куклой"

// Conlarver (empty)
#define ITM26_COMMENTS1 comments 1 "Container for Larva"
#define ITM26_COMMENTS2 comments 1 "Контейнер для Куклы"

// Nymbos
#define ITM27_COMMENTS1 comments 2 "Some eleepods' stuff" \
				   "from Podish"

#define ITM27_COMMENTS2 comments 2 "Продукт элиподов" \
				   "из Подиша"

// Phlegma
#define ITM28_COMMENTS1 comments 2 "Some eleepods' stuff" \
				   "from Incubator"

#define ITM28_COMMENTS2 comments 2 "Продукт элиподов" \
				   "из Инкубатора"

// Heroin
#define ITM29_COMMENTS1 comments 2 "Some beeboorats' stuff" \
				   "from VigBoo"

#define ITM29_COMMENTS2 comments 2 "Продукт бибуратов" \
				   "из ВигБу"

// Shrub
#define ITM30_COMMENTS1 comments 2 "Some beeboorats' stuff" \
				   "from VigBoo"

#define ITM30_COMMENTS2 comments 2 "Продукт бибуратов" \
				   "из Вигбу"

// Poponka
#define ITM31_COMMENTS1 comments 2 "Some zeexens'" \
				   "stuff from ZeePa"

#define ITM31_COMMENTS2 comments 2 "Продукт цикс" \
				   "из ЦыПы"

// Toxick
#define ITM32_COMMENTS1 comments 2 "Some zeexens' stuff" \
				   "from B-Zone"

#define ITM32_COMMENTS2 comments 2 "Продукт цикс" \
				   "из БиЗоны"

// eLeech
#define ITM33_COMMENTS1 comments 1 "Eleepods' cult doodad"
#define ITM33_COMMENTS2 comments 1 "Предмет культа элиподов"

// Kernoboo
#define ITM34_COMMENTS1 comments 1 "Beeboorats' cult doodad"
#define ITM34_COMMENTS2 comments 1 "Предмет культа бибуратов"

// Pipetka
#define ITM35_COMMENTS1 comments 1 "Beeboorats' cult doodad"
#define ITM35_COMMENTS2 comments 1 "Предмет культа бибуратов"

// WeeZyk
#define ITM36_COMMENTS1 comments 1 "Zeexens' cult doodad"
#define ITM36_COMMENTS2 comments 1 "Предмет культа цикс"

// Leepuringa
#define ITM41_COMMENTS1 comments 3 "Counselor's personal" \
				   "article" \
				   "Luck: 50"

#define ITM41_COMMENTS2 comments 2 "Личная вещь советника" \
				   "Удача: 50"

// Dead eLeech
#define ITM42_COMMENTS1 comments 0
#define ITM42_COMMENTS2 comments 0

// Protractor
#define ITM37_COMMENTS1 comments 2 "Spectors' artefact" \
				   "Luck: 20"
#define ITM37_COMMENTS2 comments 2 "Артефакт наблюдателей"      \
				   "Удача: 20"

// Mechanic Messiah
#define ITM38_COMMENTS1 comments 2 "Spirits' artefact" \
				   "Dominance: 20"
#define ITM38_COMMENTS2 comments 2 "Артефакт спиритов" \
				   "Авторитет: 20"

// Function-83+
#define ITM39_COMMENTS1 comments 1 "Spirits' artefact"
#define ITM39_COMMENTS2 comments 1 "Артефакт спиритов"

// SpuMMy
#define ITM40_COMMENTS1 comments 1 "Unknown artefact"
#define ITM40_COMMENTS2 comments 1 "Неизвестный артефакт"

// Rubox
#define ITM43_COMMENTS1 comments 1 "Beeboorats' token"
#define ITM43_COMMENTS2 comments 1 "Метка бибуратов"

// Zigger-Zagger
#define ITM44_COMMENTS1 comments 1 "A mechos part"
#define ITM44_COMMENTS2 comments 1 "Часть мехоса"

// Cart
#define ITM45_COMMENTS1 comments 1 "A mechos part"
#define ITM45_COMMENTS2 comments 1 "Часть мехоса"

// Put-Put
#define ITM46_COMMENTS1 comments 1 "A mechos part"
#define ITM46_COMMENTS2 comments 1 "Часть мехоса"

// Box
#define ITM47_COMMENTS1 comments 1 "A mechos part"
#define ITM47_COMMENTS2 comments 1 "Часть мехоса"

// Rattle
#define ITM48_COMMENTS1 comments 1 "A mechos part"
#define ITM48_COMMENTS2 comments 1 "Часть мехоса"

// Heavy Iron
#define ITM49_COMMENTS1 comments 1 "A mechos part"
#define ITM49_COMMENTS2 comments 1 "Часть мехоса"

// Star
#define ITM50_COMMENTS1 comments 1 "A mechos part"
#define ITM50_COMMENTS2 comments 1 "Часть мехоса"

// Whizzer
#define ITM51_COMMENTS1 comments 1 "A mechos part"
#define ITM51_COMMENTS2 comments 1 "Часть мехоса"

// Husker
#define ITM52_COMMENTS1 comments 1 "A mechos part"
#define ITM52_COMMENTS2 comments 1 "Часть мехоса"

// Cogged Widget
#define ITM53_COMMENTS1 comments 1 "A mechos part"
#define ITM53_COMMENTS2 comments 1 "Часть мехоса"

// TankAcid
#define ITM54_COMMENTS1 comments 1 "Unknown substance"
#define ITM54_COMMENTS2 comments 1 "Неизвестная субстанция"

// Peelot
#define ITM55_COMMENTS1 comments 1 "Vangers' artefact"
#define ITM55_COMMENTS2 comments 1 "Артефакт вангеров"

// Boot Sector
#define ITM56_COMMENTS1 comments 1 "Vangers' artefact"
#define ITM56_COMMENTS2 comments 1 "Артефакт вангеров"

// Mechoscope
#define ITM57_COMMENTS1 comments 1 "Activated"
#define ITM57_COMMENTS2 comments 1 "Активное состояние"

// Gluek
#define ITM58_COMMENTS1 comments 1 "Repair kit for the mechos"
#define ITM58_COMMENTS2 comments 1 "Пакет для ремонта мехоса"

// Degradator
#define ITM59_COMMENTS1 comments 1 "Activated"
#define ITM59_COMMENTS2 comments 1 "Активное состояние"

// Tabutask (active)
#define ITM60_COMMENTS1 comments 0
#define ITM60_COMMENTS2 comments 0

// Amputator
#define ITM61_COMMENTS1 comments 1 "Activated"
#define ITM61_COMMENTS2 comments 1 "Активное состояние"

// Eleepod
#define ITM62_COMMENTS1 comments 1 "Passenger"
#define ITM62_COMMENTS2 comments 1 "Пассажир"

// Beeboorat
#define ITM63_COMMENTS1 comments 1 "Passenger"
#define ITM63_COMMENTS2 comments 1 "Пассажир"

// Zeex
#define ITM64_COMMENTS1 comments 1 "Passenger"
#define ITM64_COMMENTS2 comments 1 "Пассажир"

// Palochka
#define ITM65_COMMENTS1 comments 2 "Counselor's personal" \
				   "article"
#define ITM65_COMMENTS2 comments 1 "Личная вещь советника"

// Pipka
#define ITM66_COMMENTS1 comments 2 "Counselor's personal" \
				   "article"
#define ITM66_COMMENTS2 comments 1 "Личная вещь советника"

// Nobool
#define ITM67_COMMENTS1 comments 2 "Counselor's personal" \
				   "article"
#define ITM67_COMMENTS2 comments 1 "Личная вещь советника"

// Boorawchick
#define ITM68_COMMENTS1 comments 2 "Counselor of VigBoo" \
				   "Dominance: 50"
#define ITM68_COMMENTS2 comments 2 "Советник ВигБу" \
				   "Авторитет: 50"

// Pereponka
#define ITM69_COMMENTS1 comments 2 "Counselor's personal" \
				   "article"
#define ITM69_COMMENTS2 comments 1 "Личная вещь советника"

// Zeefick
#define ITM70_COMMENTS1 comments 2 "Counselor's personal" \
				   "article"
#define ITM70_COMMENTS2 comments 1 "Личная вещь советника"

// Dead WeeZyk
#define ITM71_COMMENTS1 comments 0
#define ITM71_COMMENTS2 comments 0

// Rotten Kernoboo
#define ITM72_COMMENTS1 comments 0
#define ITM72_COMMENTS2 comments 0

// Tabutask (failed)
#define ITM73_COMMENTS1 comments 1 "Tabutask failed"
#define ITM73_COMMENTS2 comments 1 "Табутаск провален"

// Tabutask (completed)
#define ITM74_COMMENTS1 comments 1 "Tabutask completed"
#define ITM74_COMMENTS2 comments 1 "Табутаск выполнен"

// Amputator (empty)
#define ITM75_COMMENTS1 comments 2 "Special vanger's weapon" \
				   "Deactivated"

#define ITM75_COMMENTS2 comments 2 "Специальное оружие вангеров" \
				   "Неактивно"

// Degradator (empty)
#define ITM76_COMMENTS1 comments 2 "Special vanger's weapon" \
				   "Deactivated"

#define ITM76_COMMENTS2 comments 2 "Специальное оружие вангеров" \
				   "Неактивно"

// Rotten Pipetka
#define ITM77_COMMENTS1 comments 0
#define ITM77_COMMENTS2 comments 0

// Mechoscope (empty)
#define ITM78_COMMENTS1 comments 2 "Special vanger's weapon" \
				   "Deactivated"

#define ITM78_COMMENTS2 comments 2 "Специальное оружие вангеров" \
				   "Неактивно"

/* ------------------------- SHOP COMMENTS SECTION -------------------------- */

// MacHOTine Gun (light)
#define iITM01_COMMENTS1 comments	 0
#define iITM01_COMMENTS2 comments	 0

// MacHOTine Gun (heavy)
#define iITM02_COMMENTS1 comments	 0
#define iITM02_COMMENTS2 comments	 0

// Speetle System (light)
#define iITM03_COMMENTS1 comments	 0
#define iITM03_COMMENTS2 comments	 0

// Speetle System (heavy)
#define iITM04_COMMENTS1 comments	 0
#define iITM04_COMMENTS2 comments	 0

// ghOrb Gear (light)
#define iITM05_COMMENTS1 comments	 0
#define iITM05_COMMENTS2 comments	 0

// ghOrb Gear (heavy)
#define iITM06_COMMENTS1 comments	 0
#define iITM06_COMMENTS2 comments	 0

// Beebbanoza Blockade
#define iITM07_COMMENTS1 comments	 0
#define iITM07_COMMENTS2 comments	 0

// Crustest Cannon
#define iITM08_COMMENTS1 comments	 0
#define iITM08_COMMENTS2 comments	 0

// Terminator 'Wormer'
#define iITM09_COMMENTS1 comments	 0
#define iITM09_COMMENTS2 comments	 0

// Terminator 'Wasp'
#define iITM10_COMMENTS1 comments	 0
#define iITM10_COMMENTS2 comments	 0

// Pupok pile
#define iITM11_COMMENTS1 comments	 0
#define iITM11_COMMENTS2 comments	 0

// OKorOK pile
#define iITM12_COMMENTS1 comments	 0
#define iITM12_COMMENTS2 comments	 0

// Boltoon pack
#define iITM13_COMMENTS1 comments	 0
#define iITM13_COMMENTS2 comments	 0

// CopteRig
#define iITM14_COMMENTS1 comments	 0
#define iITM14_COMMENTS2 comments	 0

// CopteRig (empty)
#define iITM15_COMMENTS1 comments	 1 "Discharged"
#define iITM15_COMMENTS2 comments	 1 "Разряжен"

// CutteRig
#define iITM16_COMMENTS1 comments	 0
#define iITM16_COMMENTS2 comments	 0

// CutteRig (empty)
#define iITM17_COMMENTS1 comments	 1 "Discharged"
#define iITM17_COMMENTS2 comments	 1 "Разряжен"

// CrotRig
#define iITM18_COMMENTS1 comments	 0
#define iITM18_COMMENTS2 comments	 0

// CrotRig (empty)
#define iITM19_COMMENTS1 comments	 1 "Discharged"
#define iITM19_COMMENTS2 comments	 1 "Разряжен"

// Lhark - does not exist :)
#define iITM20_COMMENTS1 comments	 0
#define iITM20_COMMENTS2 comments	 0

// Lhark - does not exist :)
#define iITM21_COMMENTS1 comments	 0
#define iITM21_COMMENTS2 comments	 0

// Vector
#define iITM22_COMMENTS1 comments	 0
#define iITM22_COMMENTS2 comments	 0

// Cirtainer
#define iITM23_COMMENTS1 comments	 0
#define iITM23_COMMENTS2 comments	 0

// Cirtainer (empty)
#define iITM24_COMMENTS1 comments	 0
#define iITM24_COMMENTS2 comments	 0

// Conlarver
#define iITM25_COMMENTS1 comments	 0
#define iITM25_COMMENTS2 comments	 0

// Conlarver (empty)
#define iITM26_COMMENTS1 comments	 0
#define iITM26_COMMENTS2 comments	 0

// Nymbos
#define iITM27_COMMENTS1 comments	 1 "A ware from Podish"
#define iITM27_COMMENTS2 comments	 1 "Товар из Подиша"

// Phlegma
#define iITM28_COMMENTS1 comments	 1 "A ware from Incubator"
#define iITM28_COMMENTS2 comments	 1 "Товар из Инкубатора"

// Heroin
#define iITM29_COMMENTS1 comments	 1 "A ware from VigBoo"
#define iITM29_COMMENTS2 comments	 1 "Товар из ВигБу"

// Shrub
#define iITM30_COMMENTS1 comments	 1 "A ware from VigBoo"
#define iITM30_COMMENTS2 comments	 1 "Товар из ВигБу"

// Poponka
#define iITM31_COMMENTS1 comments	 1 "A ware from ZeePa"
#define iITM31_COMMENTS2 comments	 1 "Товар из ЦыПы"

// Toxick
#define iITM32_COMMENTS1 comments	 1 "A ware from B-Zone"
#define iITM32_COMMENTS2 comments	 1 "Товар из БиЗоны"

// eLeech
#define iITM33_COMMENTS1 comments	 0
#define iITM33_COMMENTS2 comments	 0

// Kernoboo
#define iITM34_COMMENTS1 comments	 0
#define iITM34_COMMENTS2 comments	 0

// Pipetka
#define iITM35_COMMENTS1 comments	 0
#define iITM35_COMMENTS2 comments	 0

// WeeZyk
#define iITM36_COMMENTS1 comments	 0
#define iITM36_COMMENTS2 comments	 0

// Protractor
#define iITM37_COMMENTS1 comments	 0
#define iITM37_COMMENTS2 comments	 0

// Mechanic Messiah
#define iITM38_COMMENTS1 comments	 0
#define iITM38_COMMENTS2 comments	 0

// Function-83+
#define iITM39_COMMENTS1 comments	 0
#define iITM39_COMMENTS2 comments	 0

// SpuMMy
#define iITM40_COMMENTS1 comments	 0
#define iITM40_COMMENTS2 comments	 0

// Leepuringa
#define iITM41_COMMENTS1 comments	 0
#define iITM41_COMMENTS2 comments	 0

// Dead eLeech
#define iITM42_COMMENTS1 comments	 0
#define iITM42_COMMENTS2 comments	 0

// Rubox
#define iITM43_COMMENTS1 comments	 0
#define iITM43_COMMENTS2 comments	 0

// Zigger-Zagger
#define iITM44_COMMENTS1 comments	 0
#define iITM44_COMMENTS2 comments	 0

// Cart
#define iITM45_COMMENTS1 comments	 0
#define iITM45_COMMENTS2 comments	 0

// Put-Put
#define iITM46_COMMENTS1 comments	 0
#define iITM46_COMMENTS2 comments	 0

// Box
#define iITM47_COMMENTS1 comments	 0
#define iITM47_COMMENTS2 comments	 0

// Rattle
#define iITM48_COMMENTS1 comments	 0
#define iITM48_COMMENTS2 comments	 0

// Heavy Iron
#define iITM49_COMMENTS1 comments	 0
#define iITM49_COMMENTS2 comments	 0

// Star
#define iITM50_COMMENTS1 comments	 0
#define iITM50_COMMENTS2 comments	 0

// Whizzer
#define iITM51_COMMENTS1 comments	 0
#define iITM51_COMMENTS2 comments	 0

// Husker
#define iITM52_COMMENTS1 comments	 0
#define iITM52_COMMENTS2 comments	 0

// Cogged Widget
#define iITM53_COMMENTS1 comments	 0
#define iITM53_COMMENTS2 comments	 0

// TankAcid
#define iITM54_COMMENTS1 comments	 0
#define iITM54_COMMENTS2 comments	 0

// Boot Sector
#define iITM56_COMMENTS1 comments	 0
#define iITM56_COMMENTS2 comments	 0

// Peelot
#define iITM55_COMMENTS1 comments	 0
#define iITM55_COMMENTS2 comments	 0

// Mechoscope
#define iITM57_COMMENTS1 comments	 0
#define iITM57_COMMENTS2 comments	 0

// Gluek
#define iITM58_COMMENTS1 comments	 0
#define iITM58_COMMENTS2 comments	 0

// Degradator
#define iITM59_COMMENTS1 comments	 0
#define iITM59_COMMENTS2 comments	 0

// Tabutask (active)
#define iITM60_COMMENTS1 comments	 1 "Tabutask information"
#define iITM60_COMMENTS2 comments	 1 "Информация табутаска"

// Amputator
#define iITM61_COMMENTS1 comments	 0
#define iITM61_COMMENTS2 comments	 0

// Eleepod
#define iITM62_COMMENTS1 comments	 0
#define iITM62_COMMENTS2 comments	 0

// Beeboorat
#define iITM63_COMMENTS1 comments	 0
#define iITM63_COMMENTS2 comments	 0

// Zeex
#define iITM64_COMMENTS1 comments	 0
#define iITM64_COMMENTS2 comments	 0

// Palochka
#define iITM65_COMMENTS1 comments	 0
#define iITM65_COMMENTS2 comments	 0

// Pipka
#define iITM66_COMMENTS1 comments	 0
#define iITM66_COMMENTS2 comments	 0

// Nobool
#define iITM67_COMMENTS1 comments	 0
#define iITM67_COMMENTS2 comments	 0

// Boorawchick
#define iITM68_COMMENTS1 comments	 0
#define iITM68_COMMENTS2 comments	 0

// Pereponka
#define iITM69_COMMENTS1 comments	 0
#define iITM69_COMMENTS2 comments	 0

// Zeefick
#define iITM70_COMMENTS1 comments	 0
#define iITM70_COMMENTS2 comments	 0

// Dead WeeZyk
#define iITM71_COMMENTS1 comments	 0
#define iITM71_COMMENTS2 comments	 0

// Rotten Kernoboo
#define iITM72_COMMENTS1 comments	 0
#define iITM72_COMMENTS2 comments	 0

// Tabutask (failed)
#define iITM73_COMMENTS1 comments	 1 "Tabutask failed"
#define iITM73_COMMENTS2 comments	 1 "Табутаск провален"

// Tabutask (completed)
#define iITM74_COMMENTS1 comments	 1 "Tabutask completed"
#define iITM74_COMMENTS2 comments	 1 "Табутаск выполнен"

// Amputator (empty)
#define iITM75_COMMENTS1 comments	 1 "Deactivated"
#define iITM75_COMMENTS2 comments	 1 "Неактивный"

// Degradator (empty)
#define iITM76_COMMENTS1 comments	 1 "Deactivated"
#define iITM76_COMMENTS2 comments	 1 "Неактивный"

// Rotten Pipetka
#define iITM77_COMMENTS1 comments	 0
#define iITM77_COMMENTS2 comments	 0

// Mechoscope (empty)
#define iITM78_COMMENTS1 comments	 1 "Deactivated"
#define iITM78_COMMENTS2 comments	 1 "Неактивный"

/* --------------------------- ITEMS INFO SECTION --------------------------- */

// MacHOTine Gun (light)
#define ITM01_INFO1	prompt_text "Put in an arms slot to use"
#define ITM01_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// MacHOTine Gun (heavy)
#define ITM02_INFO1	prompt_text "Put in an arms slot to use"
#define ITM02_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// Speetle System (light)
#define ITM03_INFO1	prompt_text "Put in an arms slot to use"
#define ITM03_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// Speetle System (heavy)
#define ITM04_INFO1	prompt_text "Put in an arms slot to use"
#define ITM04_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// ghOrb Gear (light)
#define ITM05_INFO1	prompt_text "Put in an arms slot to use"
#define ITM05_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// ghOrb Gear (heavy)
#define ITM06_INFO1	prompt_text "Put in an arms slot to use"
#define ITM06_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// Beebbanoza Blockade
#define ITM07_INFO1	prompt_text "Put in an arms slot to use"
#define ITM07_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// Crustest Cannon
#define ITM08_INFO1	prompt_text "Put in an arms slot to use"
#define ITM08_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// Terminator 'Wormer'
#define ITM09_INFO1	prompt_text "Put in an arms slot to use"
#define ITM09_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// Terminator 'Wasp'
#define ITM10_INFO1	prompt_text "Put in an arms slot to use"
#define ITM10_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// CopteRig
#define ITM14_INFO1	prompt_text "Autoactivates if there is a matching slot"
#define ITM14_INFO2	prompt_text "Самоактивируется при наличии
специального паза"

// CopteRig (empty)
#define ITM15_INFO1	prompt_text "Needs recharge"
#define ITM15_INFO2	prompt_text "Необходима перезарядка"

// CutteRig
#define ITM16_INFO1	prompt_text "Autoactivates if there is
a matching slot"
#define ITM16_INFO2	prompt_text "Самоактивируется при наличии
специального паза"

// CutteRig (empty)
#define ITM17_INFO1	prompt_text "Needs recharge"
#define ITM17_INFO2	prompt_text "Необходима перезарядка"

// CrotRig
#define ITM18_INFO1	prompt_text "Autoactivates if there is
a matching slot"
#define ITM18_INFO2	prompt_text "Самоактивируется при наличии
специального паза"

// CrotRig (empty)
#define ITM19_INFO1	prompt_text "Needs recharge"
#define ITM19_INFO2	prompt_text "Необходима перезарядка"

// Vector
#define ITM22_INFO1	prompt_text "Put in special slot to use"
#define ITM22_INFO2	prompt_text "Для использования поместить
в специальный паз"

// Cirtainer (empty)
#define ITM24_INFO1	prompt_text "Activate to pick up the cirt"
#define ITM24_INFO2	prompt_text "Для сбора нюхи активировать"

// Conlarver (empty)
#define ITM26_INFO1	prompt_text "Put on the surface to activate"
#define ITM26_INFO2	prompt_text "Для активации разместить
на поверхности мира"

// Tabutask
#define ITM60_INFO1	prompt_text "Carries information..."
#define ITM60_INFO2	prompt_text "Содержит информацию..."

// Poponka
#define ITM31_INFO1	prompt_text "Carries information..."
#define ITM31_INFO2	prompt_text "Содержит информацию..."

// Protractor
#define ITM37_INFO1	prompt_text "To activate select a function
on the control panel"
#define ITM37_INFO2	prompt_text "Активизируется выбором функции
в контрольной панели"

// Mechanic Messiah
#define ITM38_INFO1	prompt_text "To activate select a function
on the control panel"
#define ITM38_INFO2	prompt_text "Активизируется выбором функции
в контрольной панели"

// Function-83+
#define ITM39_INFO1	prompt_text "To activate select a function
on the control panel"
#define ITM39_INFO2	prompt_text "Активизируется
в контрольной панели"

// Boot Sector
#define ITM56_INFO1	prompt_text "To activate select a function
on the control panel"
#define ITM56_INFO2	prompt_text "Активизируется
в контрольной панели"

// Peelot
#define ITM55_INFO1	prompt_text "Before activation point the
compass at required destination"
#define ITM55_INFO2	prompt_text "Перед активацией назначить компас
на нужный пункт назначения"

// Mechoscope(empty)
#define ITM75_INFO1	prompt_text "Put in an arms slot to use"
#define ITM75_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// Gluek
#define ITM58_INFO1	prompt_text "Activate to use"
#define ITM58_INFO2	prompt_text "Для использования активировать"

// Degradator(empty)
#define ITM76_INFO1	prompt_text "Put in an arms slot to use"
#define ITM76_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// Amputator(empty)
#define ITM78_INFO1	prompt_text "Put in an arms slot to use"
#define ITM78_INFO2	prompt_text "Для использования поместить
в оружейный паз"

// Eleepod
#define ITM62_INFO1	prompt_text "More info..."
#define ITM62_INFO2	prompt_text "Содержит информацию..."

// Beeboorat
#define ITM63_INFO1	prompt_text "More info..."
#define ITM63_INFO2	prompt_text "Содержит информацию..."

// Zeex
#define ITM64_INFO1	prompt_text "More info..."
#define ITM64_INFO2	prompt_text "Содержит информацию..."

/* --------------------------- PARAMETERS SECTION --------------------------- */

// MacHOTine Gun (light)
#define ITM01_PARAMS1	prm_template	"%d shots"
#define ITM01_PARAMS2	prm_template	"%d выстрелов"

// MacHOTine Gun (heavy)
#define ITM02_PARAMS1	prm_template	"%d shots"
#define ITM02_PARAMS2	prm_template	"%d выстрелов"

// Speetle System (light)
#define ITM03_PARAMS1	prm_template	"%d shots"
#define ITM03_PARAMS2	prm_template	"%d зарядов"

// Speetle System (heavy)
#define ITM04_PARAMS1	prm_template	"%d shots"
#define ITM04_PARAMS2	prm_template	"%d зарядов"

// ghOrb Gear (light)
#define ITM05_PARAMS1	prm_template	"%d shots"
#define ITM05_PARAMS2	prm_template	"%d зарядов"

// ghOrb Gear (heavy)
#define ITM06_PARAMS1	prm_template	"%d shots"
#define ITM06_PARAMS2	prm_template	"%d зарядов"

// Beebbanoza Blockade
#define ITM07_PARAMS1	prm_template	NONE
#define ITM07_PARAMS2	prm_template	NONE

// Crustest Cannon
#define ITM08_PARAMS1	prm_template	"%d shots"
#define ITM08_PARAMS2	prm_template	"%d зарядов"

// Terminator 'Wormer'
#define ITM09_PARAMS1	prm_template	"%d shots"
#define ITM09_PARAMS2	prm_template	"%d штук"

// Terminator 'Wasp'
#define ITM10_PARAMS1	prm_template	"%d shots"
#define ITM10_PARAMS2	prm_template	"%d штук"

// Pupok pile
#define ITM11_PARAMS1	prm_template	"%d shots"
#define ITM11_PARAMS2	prm_template	"%d штук"

// OKorOK pile
#define ITM12_PARAMS1	prm_template	"%d shots"
#define ITM12_PARAMS2	prm_template	"%d штук"

// Boltoon pack
#define ITM13_PARAMS1	prm_template	"%d shots"
#define ITM13_PARAMS2	prm_template	"%d штук"

// CopteRig
#define ITM14_PARAMS1	prm_template	"Charge: %d"
#define ITM14_PARAMS2	prm_template	"Ресурс: %d"

// CopteRig (empty)
#define ITM15_PARAMS1	prm_template	NONE
#define ITM15_PARAMS2	prm_template	NONE

// CutteRig
#define ITM16_PARAMS1	prm_template	"Charge: %d"
#define ITM16_PARAMS2	prm_template	"Ресурс: %d"

// CutteRig (empty)
#define ITM17_PARAMS1	prm_template	NONE
#define ITM17_PARAMS2	prm_template	NONE

// CrotRig
#define ITM18_PARAMS1	prm_template	"Charge: %d"
#define ITM18_PARAMS2	prm_template	"Ресурс: %d"

// CrotRig (empty)
#define ITM19_PARAMS1	prm_template	NONE
#define ITM19_PARAMS2	prm_template	NONE

// Lhark - does not exist :)
#define ITM20_PARAMS1	prm_template	NONE
#define ITM20_PARAMS2	prm_template	NONE

// Lhark - does not exist :)
#define ITM21_PARAMS1	prm_template	NONE
#define ITM21_PARAMS2	prm_template	NONE

// Vector
#define ITM22_PARAMS1	prm_template	NONE
#define ITM22_PARAMS2	prm_template	NONE

// Cirtainer
#define ITM23_PARAMS1	prm_template	NONE
#define ITM23_PARAMS2	prm_template	NONE

// Cirtainer (empty)
#define ITM24_PARAMS1	prm_template	NONE
#define ITM24_PARAMS2	prm_template	NONE

// Conlarver
#define ITM25_PARAMS1	prm_template	NONE
#define ITM25_PARAMS2	prm_template	NONE

// Conlarver (empty)
#define ITM26_PARAMS1	prm_template	NONE
#define ITM26_PARAMS2	prm_template	NONE

// Nymbos
#define ITM27_PARAMS1	prm_template	NONE
#define ITM27_PARAMS2	prm_template	NONE

// Phlegma
#define ITM28_PARAMS1	prm_template	NONE
#define ITM28_PARAMS2	prm_template	NONE

// Heroin
#define ITM29_PARAMS1	prm_template	NONE
#define ITM29_PARAMS2	prm_template	NONE

// Shrub
#define ITM30_PARAMS1	prm_template	NONE
#define ITM30_PARAMS2	prm_template	NONE

// Poponka
#define ITM31_PARAMS1	prm_template	NONE
#define ITM31_PARAMS2	prm_template	NONE

// Toxick
#define ITM32_PARAMS1	prm_template	NONE
#define ITM32_PARAMS2	prm_template	NONE

// eLeech
#define ITM33_PARAMS1	prm_template	NONE
#define ITM33_PARAMS2	prm_template	NONE

// Kernoboo
#define ITM34_PARAMS1	prm_template	"%d"
#define ITM34_PARAMS2	prm_template	"%d"

// Pipetka
#define ITM35_PARAMS1	prm_template	"%d"
#define ITM35_PARAMS2	prm_template	"%d"

// WeeZyk
#define ITM36_PARAMS1	prm_template	NONE
#define ITM36_PARAMS2	prm_template	NONE

// Protractor
#define ITM37_PARAMS1	prm_template	NONE
#define ITM37_PARAMS2	prm_template	NONE

// Mechanic Messiah
#define ITM38_PARAMS1	prm_template	NONE
#define ITM38_PARAMS2	prm_template	NONE

// Function-83+
#define ITM39_PARAMS1	prm_template	NONE
#define ITM39_PARAMS2	prm_template	NONE

// SpuMMy
#define ITM40_PARAMS1	prm_template	NONE
#define ITM40_PARAMS2	prm_template	NONE

// Leepuringa
#define ITM41_PARAMS1	prm_template	NONE
#define ITM41_PARAMS2	prm_template	NONE

// Dead eLeech
#define ITM42_PARAMS1	prm_template	NONE
#define ITM42_PARAMS2	prm_template	NONE

// Rubox
#define ITM43_PARAMS1	prm_template	NONE
#define ITM43_PARAMS2	prm_template	NONE

// Zigger-Zagger
#define ITM44_PARAMS1	prm_template	NONE
#define ITM44_PARAMS2	prm_template	NONE

// Cart
#define ITM45_PARAMS1	prm_template	NONE
#define ITM45_PARAMS2	prm_template	NONE

// Put-Put
#define ITM46_PARAMS1	prm_template	NONE
#define ITM46_PARAMS2	prm_template	NONE

// Box
#define ITM47_PARAMS1	prm_template	NONE
#define ITM47_PARAMS2	prm_template	NONE

// Rattle
#define ITM48_PARAMS1	prm_template	NONE
#define ITM48_PARAMS2	prm_template	NONE

// Heavy Iron
#define ITM49_PARAMS1	prm_template	NONE
#define ITM49_PARAMS2	prm_template	NONE

// Star
#define ITM50_PARAMS1	prm_template	NONE
#define ITM50_PARAMS2	prm_template	NONE

// Whizzer
#define ITM51_PARAMS1	prm_template	NONE
#define ITM51_PARAMS2	prm_template	NONE

// Husker
#define ITM52_PARAMS1	prm_template	NONE
#define ITM52_PARAMS2	prm_template	NONE

// Cogged Widget
#define ITM53_PARAMS1	prm_template	NONE
#define ITM53_PARAMS2	prm_template	NONE

// TankAcid
#define ITM54_PARAMS1	prm_template	NONE
#define ITM54_PARAMS2	prm_template	NONE

// Boot Sector
#define ITM56_PARAMS1	prm_template	NONE
#define ITM56_PARAMS2	prm_template	NONE

// Peelot
#define ITM55_PARAMS1	prm_template	NONE
#define ITM55_PARAMS2	prm_template	NONE

// Mechoscope
#define ITM57_PARAMS1	prm_template	NONE
#define ITM57_PARAMS2	prm_template	NONE

// Gluek
#define ITM58_PARAMS1	prm_template	NONE
#define ITM58_PARAMS2	prm_template	NONE

// Degradator
#define ITM59_PARAMS1	prm_template	NONE
#define ITM59_PARAMS2	prm_template	NONE

// Tabutask (active)
#define ITM60_PARAMS1	show_escave	\
			prm_template	"from %s"

#define ITM60_PARAMS2	show_escave	\
			prm_template	"Эскейв: %s"

// Amputator
#define ITM61_PARAMS1	prm_template	NONE
#define ITM61_PARAMS2	prm_template	NONE

// Eleepod
#define ITM62_PARAMS1	prm_template	NONE
#define ITM62_PARAMS2	prm_template	NONE

// Beeboorat
#define ITM63_PARAMS1	prm_template	NONE
#define ITM63_PARAMS2	prm_template	NONE

// Zeex
#define ITM64_PARAMS1	prm_template	NONE
#define ITM64_PARAMS2	prm_template	NONE

// Palochka
#define ITM65_PARAMS1	prm_template	NONE
#define ITM65_PARAMS2	prm_template	NONE

// Pipka
#define ITM66_PARAMS1	prm_template	NONE
#define ITM66_PARAMS2	prm_template	NONE

// Nobool
#define ITM67_PARAMS1	prm_template	NONE
#define ITM67_PARAMS2	prm_template	NONE

// Boorawchick
#define ITM68_PARAMS1	prm_template	NONE
#define ITM68_PARAMS2	prm_template	NONE

// Pereponka
#define ITM69_PARAMS1	prm_template	NONE
#define ITM69_PARAMS2	prm_template	NONE

// Zeefick
#define ITM70_PARAMS1	prm_template	NONE
#define ITM70_PARAMS2	prm_template	NONE

// Dead WeeZyk
#define ITM71_PARAMS1	prm_template	NONE
#define ITM71_PARAMS2	prm_template	NONE

// Rotten Kernoboo
#define ITM72_PARAMS1	prm_template	NONE
#define ITM72_PARAMS2	prm_template	NONE

// Tabutask (failed)
#define ITM73_PARAMS1	show_escave	\
			prm_template	"from %s"

#define ITM73_PARAMS2	show_escave	\
			prm_template	"Эскейв: %s"

// Tabutask (completed)
#define ITM74_PARAMS1	show_escave	\
			prm_template	"from %s"

#define ITM74_PARAMS2	show_escave	\
			prm_template	"Эскейв: %s"

// Amputator (empty)
#define ITM75_PARAMS1	prm_template	NONE
#define ITM75_PARAMS2	prm_template	NONE

// Degradator (empty)
#define ITM76_PARAMS1	prm_template	NONE
#define ITM76_PARAMS2	prm_template	NONE

// Rotten Pipetka
#define ITM77_PARAMS1	prm_template	NONE
#define ITM77_PARAMS2	prm_template	NONE

// Mechoscope (empty)
#define ITM78_PARAMS1	prm_template	NONE
#define ITM78_PARAMS2	prm_template	NONE

