
/* -------------------------------- WEAPONS --------------------------------- */

// MacHOTine Gun (light)
item_prm	$ITM01_ID	$ACI_WEAPON_DAMAGE	"5"
item_prm	$ITM01_ID	$ACI_WEAPON_LOAD	"50"
item_prm	$ITM01_ID	$ACI_WEAPON_SHOTS_SEC	"3"
item_prm	$ITM01_ID	$ACI_WEAPON_RANGE	"30"

// MacHOTine Gun (heavy)
item_prm	$ITM02_ID	$ACI_WEAPON_DAMAGE	"10"
item_prm	$ITM02_ID	$ACI_WEAPON_LOAD	"100"
item_prm	$ITM02_ID	$ACI_WEAPON_SHOTS_SEC	"3"
item_prm	$ITM02_ID	$ACI_WEAPON_RANGE	"40"

// Speetle System (light)
item_prm	$ITM03_ID	$ACI_WEAPON_DAMAGE	"30"
item_prm	$ITM03_ID	$ACI_WEAPON_LOAD	"5"
item_prm	$ITM03_ID	$ACI_WEAPON_SHOTS_SEC	"1"
item_prm	$ITM03_ID	$ACI_WEAPON_RANGE	"25"

// Speetle System (heavy)
item_prm	$ITM04_ID	$ACI_WEAPON_DAMAGE	"60"
item_prm	$ITM04_ID	$ACI_WEAPON_LOAD	"10"
item_prm	$ITM04_ID	$ACI_WEAPON_SHOTS_SEC	"1"
item_prm	$ITM04_ID	$ACI_WEAPON_RANGE	"35"

// ghOrb Gear (light)
item_prm	$ITM05_ID	$ACI_WEAPON_DAMAGE	"13"
item_prm	$ITM05_ID	$ACI_WEAPON_LOAD	"50"
item_prm	$ITM05_ID	$ACI_WEAPON_SHOTS_SEC	"2"
item_prm	$ITM05_ID	$ACI_WEAPON_RANGE	"20"

// ghOrb Gear (heavy)
item_prm	$ITM06_ID	$ACI_WEAPON_DAMAGE	"26"
item_prm	$ITM06_ID	$ACI_WEAPON_LOAD	"100"
item_prm	$ITM06_ID	$ACI_WEAPON_SHOTS_SEC	"2"
item_prm	$ITM06_ID	$ACI_WEAPON_RANGE	"30"

// Beebbanoza Blockade
item_prm	$ITM07_ID	$ACI_WEAPON_DAMAGE	"5"
item_prm	$ITM07_ID	$ACI_WEAPON_LOAD	"N/A"
item_prm	$ITM07_ID	$ACI_WEAPON_SHOTS_SEC	"5"
item_prm	$ITM07_ID	$ACI_WEAPON_RANGE	"10"

// Crustest Cannon
item_prm	$ITM08_ID	$ACI_WEAPON_DAMAGE	"200"
item_prm	$ITM08_ID	$ACI_WEAPON_LOAD	"5"
item_prm	$ITM08_ID	$ACI_WEAPON_SHOTS_SEC	"0.25"
item_prm	$ITM08_ID	$ACI_WEAPON_RANGE	"10"

// Terminator ("Wormer")
item_prm	$ITM09_ID	$ACI_WEAPON_DAMAGE	"10"
item_prm	$ITM09_ID	$ACI_WEAPON_LOAD	"5"
item_prm	$ITM09_ID	$ACI_WEAPON_SHOTS_SEC	"1"
item_prm	$ITM09_ID	$ACI_WEAPON_RANGE	"5"

// Terminator ("Wasp")
item_prm	$ITM10_ID	$ACI_WEAPON_DAMAGE	"15"
item_prm	$ITM10_ID	$ACI_WEAPON_LOAD	"3"
item_prm	$ITM10_ID	$ACI_WEAPON_SHOTS_SEC	"1"
item_prm	$ITM10_ID	$ACI_WEAPON_RANGE	"5"

/* ---------------------------------- AMMO ---------------------------------- */

// Pupok pile
item_prm	$ITM11_ID	$ACI_AMMO_DAMAGE	"30"
item_prm	$ITM11_ID	$ACI_AMMO_IN_PACK	"5"

// OKorOK pile
item_prm	$ITM12_ID	$ACI_AMMO_DAMAGE	"30"
item_prm	$ITM12_ID	$ACI_AMMO_IN_PACK	"5"

// Boltoon pack
item_prm	$ITM13_ID	$ACI_AMMO_DAMAGE	"200"
item_prm	$ITM13_ID	$ACI_AMMO_IN_PACK	"1"                                                                                                         /* -------------------------------- DEVICES --------------------------------- */

// CopteRig
item_prm	$ITM14_ID	$ACI_DEVICE_WORKING_TIME	 "1000"

// CutteRig
item_prm	$ITM16_ID	$ACI_DEVICE_WORKING_TIME	 "3000"

// CrotRig
item_prm	$ITM18_ID	$ACI_DEVICE_WORKING_TIME	 "5000"

