
cur_ibs 	$IBS1

cell_size	34
map_name	$FOSTRAL_ID	"resource/actint/640x480/bitmap/map_f.bmp"
map_name	$GLORX_ID	"resource/actint/640x480/bitmap/map_g.bmp"
map_name	$XPLO_ID	"resource/actint/640x480/bitmap/map_x.bmp"
map_name	$NECROSS_ID	"resource/actint/640x480/bitmap/map_n.bmp"
map_name	$A_ID		"resource/actint/640x480/bitmap/map_a.bmp"
map_name	$B_ID		"resource/actint/640x480/bitmap/map_b.bmp"
map_name	$K_ID		"resource/actint/640x480/bitmap/map_k.bmp"
map_name	$T_ID		"resource/actint/640x480/bitmap/map_t.bmp"
map_name	$H_ID		"resource/actint/640x480/bitmap/map_h.bmp"
map_name	$W_ID		"resource/actint/640x480/bitmap/map_w.bmp"

/* ----------------------------- ITEMS SECTION ------------------------------ */

invItem $ITM01_NAME
	$ITM01
	$ITM01_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm01.bmp"
}
invItem $ITM02_NAME
	$ITM02
	$ITM02_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm02.bmp"
}
invItem $ITM03_NAME
	$ITM03
	$ITM03_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm03.bmp"
}
invItem $ITM04_NAME
	$ITM04
	$ITM04_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm04.bmp"
}
invItem $ITM05_NAME
	$ITM05
	$ITM05_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm05.bmp"
}
invItem $ITM06_NAME
	$ITM06
	$ITM06_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm06.bmp"
}
invItem $ITM07_NAME
	$ITM07
	$ITM07_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm07.bmp"
}
invItem $ITM08_NAME
	$ITM08
	$ITM08_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm08.bmp"
}
invItem $ITM09_NAME
	$ITM09
	$ITM09_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm09.bmp"
}
invItem $ITM10_NAME
	$ITM10
	$ITM10_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm10.bmp"
}
invItem $ITM11_NAME
	$ITM11
	$ITM11_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm11.bmp"
}
invItem $ITM12_NAME
	$ITM12
	$ITM12_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm12.bmp"
}
invItem $ITM13_NAME
	$ITM13
	$ITM13_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm13.bmp"
}
invItem $ITM14_NAME
	$ITM14
	$ITM14_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm14.bmp"
}
invItem $ITM15_NAME
	$ITM15
	$ITM15_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm15.bmp"
}
invItem $ITM16_NAME
	$ITM16
	$ITM16_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm16.bmp"
}
invItem $ITM17_NAME
	$ITM17
	$ITM17_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm17.bmp"
}
invItem $ITM18_NAME
	$ITM18
	$ITM18_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm18.bmp"
}
invItem $ITM19_NAME
	$ITM19
	$ITM19_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm19.bmp"
}
invItem $ITM20_NAME
	$ITM20
	$ITM20_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm20.bmp"
}
invItem $ITM21_NAME
	$ITM21
	$ITM21_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm21.bmp"
}
invItem $ITM22_NAME
	$ITM22
	$ITM22_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm22.bmp"
}
invItem $ITM23_NAME
	$ITM23
	$ITM23_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm23.bmp"
}
invItem $ITM24_NAME
	$ITM24
	$ITM24_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm24.bmp"
}
invItem $ITM25_NAME
	$ITM25
	$ITM25_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm25.bmp"
}
invItem $ITM26_NAME
	$ITM26
	$ITM26_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm26.bmp"
}
invItem $ITM27_NAME
	$ITM27
	$ITM27_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm27.bmp"
}
invItem $ITM28_NAME
	$ITM28
	$ITM28_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm28.bmp"
}
invItem $ITM29_NAME
	$ITM29
	$ITM29_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm29.bmp"
}
invItem $ITM30_NAME
	$ITM30
	$ITM30_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm30.bmp"
}
invItem $ITM31_NAME
	$ITM31
	$ITM31_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm31.bmp"
}
invItem $ITM32_NAME
	$ITM32
	$ITM32_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm32.bmp"
}
invItem $ITM33_NAME
	$ITM33
	$ITM33_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm33.bmp"
}
invItem $ITM34_NAME
	$ITM34
	$ITM34_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm34.bmp"
}
invItem $ITM35_NAME
	$ITM35
	$ITM35_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm35.bmp"
}
invItem $ITM36_NAME
	$ITM36
	$ITM36_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm36.bmp"
}
invItem $ITM37_NAME
	$ITM37
	$ITM37_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm37.bmp"
}
invItem $ITM38_NAME
	$ITM38
	$ITM38_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm38.bmp"
}
invItem $ITM39_NAME
	$ITM39
	$ITM39_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm39.bmp"
}
invItem $ITM40_NAME
	$ITM40
	$ITM40_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm40.bmp"
}
invItem $ITM41_NAME
	$ITM41
	$ITM41_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm41.bmp"
}
invItem $ITM42_NAME
	$ITM42
	$ITM42_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm42.bmp"
}
invItem $ITM43_NAME
	$ITM43
	$ITM43_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm43.bmp"
}
invItem $ITM44_NAME
	$ITM44
	$ITM44_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm44.bmp"
}
invItem $ITM45_NAME
	$ITM45
	$ITM45_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm45.bmp"
}
invItem $ITM46_NAME
	$ITM46
	$ITM46_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm46.bmp"
}
invItem $ITM47_NAME
	$ITM47
	$ITM47_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm47.bmp"
}
invItem $ITM48_NAME
	$ITM48
	$ITM48_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm48.bmp"
}
invItem $ITM49_NAME
	$ITM49
	$ITM49_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm49.bmp"
}
invItem $ITM50_NAME
	$ITM50
	$ITM50_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm50.bmp"
}
invItem $ITM51_NAME
	$ITM51
	$ITM51_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm51.bmp"
}
invItem $ITM52_NAME
	$ITM52
	$ITM52_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm52.bmp"
}
invItem $ITM53_NAME
	$ITM53
	$ITM53_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm53.bmp"
}
invItem $ITM54_NAME
	$ITM54
	$ITM54_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm54.bmp"
}
invItem $ITM55_NAME
	$ITM55
	$ITM55_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm55.bmp"
}
invItem $ITM56_NAME
	$ITM56
	$ITM56_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm56.bmp"
}
invItem $ITM57_NAME
	$ITM57
	$ITM57_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm57.bmp"
}
invItem $ITM58_NAME
	$ITM58
	$ITM58_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm58.bmp"
}
invItem $ITM59_NAME
	$ITM59
	$ITM59_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm59.bmp"
}
invItem $ITM60_NAME
	$ITM60
	$ITM60_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm60.bmp"
}
invItem $ITM61_NAME
	$ITM61
	$ITM61_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm61.bmp"
}
invItem $ITM62_NAME
	$ITM62
	$ITM62_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm62.bmp"
}
invItem $ITM63_NAME
	$ITM63
	$ITM63_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm63.bmp"
}
invItem $ITM64_NAME
	$ITM64
	$ITM64_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm64.bmp"
}
invItem $ITM65_NAME
	$ITM65
	$ITM65_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm65.bmp"
}
invItem $ITM66_NAME
	$ITM66
	$ITM66_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm66.bmp"
}
invItem $ITM67_NAME
	$ITM67
	$ITM67_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm67.bmp"
}
invItem $ITM68_NAME
	$ITM68
	$ITM68_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm68.bmp"
}
invItem $ITM69_NAME
	$ITM69
	$ITM69_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm69.bmp"
}
invItem $ITM70_NAME
	$ITM70
	$ITM70_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm70.bmp"
}
invItem $ITM71_NAME
	$ITM71
	$ITM71_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm71.bmp"
}
invItem $ITM72_NAME
	$ITM72
	$ITM72_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm72.bmp"
}
invItem $ITM73_NAME
	$ITM73
	$ITM73_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm74.bmp"
}
invItem $ITM74_NAME
	$ITM74
	$ITM74_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm73.bmp"
}
invItem $ITM75_NAME
	$ITM75
	$ITM75_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm75.bmp"
}
invItem $ITM76_NAME
	$ITM76
	$ITM76_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm76.bmp"
}
invItem $ITM77_NAME
	$ITM77
	$ITM77_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm77.bmp"
}
invItem $ITM78_NAME
	$ITM78
	$ITM78_COMMENTS
	bmp_file	"resource/actint/800x600/items/itm78.bmp"
}

/* -------------------------------------------------------------------------- */

ibs_obj $IBS1 { 	// Info window 600x600
	offs_x		0	13
	offs_y		0	1

	offs_x		1	-6
	offs_y		1	-3

	offs_x		2	14
	offs_y		2	-1

	offs_x		3	-6
	offs_y		3	-2

	font		7

	file	"resource/actint/800x600/screens/s600"
	bground $BG1
}

ibs_obj $IBS2 { 	// Inventory window 400x600
	offs_x		0	13
	offs_y		0	1

	offs_x		1	-1
	offs_y		1	-1

	offs_x		2	14
	offs_y		2	0

	offs_x		3	-4
	offs_y		3	-2

	font		0

	file	"resource/actint/800x600/screens/s400v"
	bground $BG3
}

ibs_obj $IBS3 { 	// Info window 400x600
	offs_x		0	13
	offs_y		0	8

	offs_x		1	-4
	offs_y		1	3

	offs_x		2	14
	offs_y		2	7

	offs_x		3	-4
	offs_y		3	5

	font		0

	file	"resource/actint/800x600/screens/s400f"
	bground $BG2
}

bml_obj $BG1 {
	file	"resource/actint/800x600/screens/b600.bmp"

	size_x	640
	size_y	480
}

bml_obj $BG2 {
	file	"resource/actint/800x600/screens/b400f.bmp"

	size_x	640
	size_y	480
}

bml_obj $BG3 {
	file	"resource/actint/800x600/screens/b400v.bmp"

	size_x	640
	size_y	480
}

Button INT_BUTTON
{
	unpress

	id	$B_INT1

	x	726
	y	533

	key	$VK_RETURN
	control_id	12	       // iKEY_INVENTORY

	event	$EV_CHANGE_MODE        0

	frame_seq	"resource/actint/800x600/buttons/int_bt0.bml"

	prompt_text	$MODE_BUTTON_TEXT
}

Button INF_BUTTON
{
	unpress

	id	$B_INF0

	x	620
	y	530

	key	$VK_SPACE
	control_id	13	       // iKEY_OPEN

	event	$EV_TRY_2_ENTER 	0

	prompt_text	$ESCAVE_BUTTON_TEXT

	frame_seq	"resource/actint/800x600/buttons/inf_bt0.bml"
}

Button INV_BUTTON
{
	id	$ACI_WPN_PICKUP_BUTTON

	x	413
	y	4

	event	$EV_SET_WPN_PICKUP	0

	prompt_text	$PICKUP_WEAPONS_BUTTON_TEXT

	frame_seq	"resource/actint/800x600/buttons/inv_bt0.bml"
}

Button INV_BUTTON
{
	id	$ACI_ITM_PICKUP_BUTTON

	x	706
	y	18

	event	$EV_SET_ITM_PICKUP	0

	prompt_text	$PICKUP_ITEMS_BUTTON_TEXT

	frame_seq	"resource/actint/800x600/buttons/inv_bt1.bml"
}

fncMenu {
	menu_type	$MENU1

	x	607
	y	64

	size_x	179
	size_y	234

	bml_name	"resource/actint/800x600/fncmenu/w01.bmo"
	ibs_name	"resource/actint/800x600/fncmenu/w01"

	cur_function	0
//	  trig_button	  $B_MENU1

	range_font
	active_time	100

	visible_items	6

	$MENU_BODY

//	  up_key	  $VK_NEXT
//	  down_key	  $VK_PRIOR
}

fncMenu {
	menu_type	$MENU2

	x	618
	y	310

	size_x	177
	size_y	222

	bml_name	"resource/actint/800x600/fncmenu/w02.bmo"
	ibs_name	"resource/actint/800x600/fncmenu/w02"

	range_font
	cur_function	1
//	  trig_button	  $B_MENU2

	$MENU_BODY

	active_time	100
	visible_items	6

//	  up_key	  $VK_NEXT
//	  down_key	  $VK_PRIOR
}

fncMenu {
	menu_type	$FMENU_TARGETS_MENU
	submenu

	visible_items	5

	x	607
	y	64

	size_x	179
	size_y	234

	range_font
	active_time	100

	cur_function	$FMENU_OFF

	$TARGETS_MENU_BODY

//	  up_key	  $VK_NEXT
//	  down_key	  $VK_PRIOR
}

ind_data $IND_LOAD {
	radius		20
	corner		$IND_DN_LEFT
	ind_type	$IND_BARREL

	prompt_text	$LOAD_IND_TEXT
}

ind_data $IND_SPIRAL {
	radius		20

	corner		$IND_DN_RIGHT
	prompt_text	$SPIRAL_IND_TEXT
}

ind_data $IND_DVC {
	radius		20
	corner		$IND_UP_RIGHT

	prompt_text	$POWERUP_IND_TEXT
}

ind_data $IND_NRG {
	radius		20
	corner		$IND_UP_LEFT

	num_values	2

	prompt_text	$ENERGY_IND_TEXT
}

info_panel {	// Inventory info panel...
	x	465
	y	464

	size_x	275
	size_y	94

	ibs_name	"resource/actint/800x600/info_pl"

	range_font
	font		1

	hspace		1
	vspace		0
}

info_panel {	// Time info panel...
	id	$ACI_TIME_PANEL

	no_align

	range_font
	font		1

	info_offs_x	14
	info_offs_y	2

	hspace		1
	vspace		8

	ibs_name	"resource/actint/800x600/time_pl"

	x	624
	y	7
	size_x	146
	size_y	45
}

counter INV_COUNTER {
	font	2
	range_font

	x	484
	y	21
	size_x	213
	size_y	38

	ibs_name	"resource/actint/800x600/credits"
}

invMatrix $MECH00_ID {
	$MATRIX_HIRES
	$MATRIX00_BODY
	back_bml	"resource/actint/800x600/matrix/matrix00.bmo"
}

invMatrix $MECH01_ID {
	$MATRIX_HIRES
	$MATRIX01_BODY
	back_bml	"resource/actint/800x600/matrix/matrix01.bmo"
}

invMatrix $MECH02_ID {
	$MATRIX_HIRES
	$MATRIX02_BODY
	back_bml	"resource/actint/800x600/matrix/matrix02.bmo"
}

invMatrix $MECH03_ID {
	$MATRIX_HIRES
	$MATRIX03_BODY
	back_bml	"resource/actint/800x600/matrix/matrix03.bmo"
}

invMatrix $MECH04_ID {
	$MATRIX_HIRES
	$MATRIX04_BODY
	back_bml	"resource/actint/800x600/matrix/matrix04.bmo"
}

invMatrix $MECH05_ID {
	$MATRIX_HIRES
	$MATRIX05_BODY
	back_bml	"resource/actint/800x600/matrix/matrix05.bmo"
}

invMatrix $MECH06_ID {
	$MATRIX_HIRES
	$MATRIX06_BODY
	back_bml	"resource/actint/800x600/matrix/matrix06.bmo"
}

invMatrix $MECH07_ID {
	$MATRIX_HIRES
	$MATRIX07_BODY
	back_bml	"resource/actint/800x600/matrix/matrix07.bmo"
}

invMatrix $MECH08_ID {
	$MATRIX_HIRES
	$MATRIX08_BODY
	back_bml	"resource/actint/800x600/matrix/matrix08.bmo"
}

invMatrix $MECH09_ID {
	$MATRIX_HIRES
	$MATRIX09_BODY
	back_bml	"resource/actint/800x600/matrix/matrix09.bmo"
}

invMatrix $MECH10_ID {
	$MATRIX_HIRES
	$MATRIX10_BODY
	back_bml	"resource/actint/800x600/matrix/matrix10.bmo"
}

invMatrix $MECH11_ID {
	$MATRIX_HIRES
	$MATRIX11_BODY
	back_bml	"resource/actint/800x600/matrix/matrix11.bmo"
}

invMatrix $MECH12_ID {
	$MATRIX_HIRES
	$MATRIX12_BODY
	back_bml	"resource/actint/800x600/matrix/matrix12.bmo"
}

invMatrix $MECH13_ID {
	$MATRIX_HIRES
	$MATRIX13_BODY
	back_bml	"resource/actint/800x600/matrix/matrix13.bmo"
}

invMatrix $MECH14_ID {
	$MATRIX_HIRES
	$MATRIX14_BODY
	back_bml	"resource/actint/800x600/matrix/matrix14.bmo"
}

invMatrix $MECH15_ID {
	$MATRIX_HIRES
	$MATRIX15_BODY
	back_bml	"resource/actint/800x600/matrix/matrix15.bmo"
}

invMatrix $MECH16_ID {
	$MATRIX_HIRES
	$MATRIX16_BODY
	back_bml	"resource/actint/800x600/matrix/matrix16.bmo"
}

invMatrix $MECH17_ID {
	$MATRIX_HIRES
	$MATRIX17_BODY
	back_bml	"resource/actint/800x600/matrix/matrix17.bmo"
}

invMatrix $MECH18_ID {
	$MATRIX_HIRES
	$MATRIX18_BODY
	back_bml	"resource/actint/800x600/matrix/matrix18.bmo"
}

invMatrix $MECH19_ID {
	$MATRIX_HIRES
	$MATRIX19_BODY
	back_bml	"resource/actint/800x600/matrix/matrix18.bmo"
}

invMatrix $MECH20_ID {
	$MATRIX_HIRES
	$MATRIX20_BODY
	back_bml	"resource/actint/800x600/matrix/matrix18.bmo"
}

invMatrix $MECH21_ID {
	$MATRIX_HIRES
	$MATRIX21_BODY
	back_bml	"resource/actint/800x600/matrix/matrix18.bmo"
}

invMatrix $MECH22_ID {
	$MATRIX_HIRES
	$MATRIX22_BODY
	back_bml	"resource/actint/800x600/matrix/matrix18.bmo"
}

invMatrix $MECH35_ID {
	$MATRIX_HIRES
	$MATRIX35_BODY
	back_bml	"resource/actint/800x600/matrix/matrix35.bmo"
}

world_map {
	size_x		148
	size_y		180

	shape	$AS_CIRCLE	"resource/actint/640x480/shapes/shp_cr.bmp"
	shape	$AS_SQUARE	"resource/actint/640x480/shapes/shp_sq.bmp"
	shape	$AS_TRIANGLE	"resource/actint/640x480/shapes/shp_tr.bmp"

	offs_x	$AS_TRIANGLE	1
	offs_y	$AS_TRIANGLE	3

	offs_x	$AS_CIRCLE	1
	offs_y	$AS_CIRCLE	1

	offs_x	$AS_SQUARE	0
	offs_y	$AS_SQUARE	1

	world_data $GLORX_ID $GLORX_LETTER $AS_CIRCLE {
		font	2

		flag	$AS_VISIBLE_WORLD
//		  flag	  $AS_ACCESSIBLE_WORLD

//		  link	  $FOSTRAL_ID
//		  link	  $XPLO_ID
//		  link	  $NECROSS_ID

//		  link	  $K_ID

		x	500
		y	500

		name	"Glorx"
	}

	world_data $FOSTRAL_ID $FOSTRAL_LETTER $AS_CIRCLE {
		font	2

		flag	$AS_CURRENT_WORLD
		flag	$AS_VISIBLE_WORLD

//		  link	  $W_ID

		x	500
		y	700

		name	"Fostral"
	}

	world_data $XPLO_ID $XPLO_LETTER $AS_CIRCLE {
		font	2

		flag	$AS_VISIBLE_WORLD

//		  link	  $T_ID

		x	350
		y	500

		name	"Xplo"
	}

	world_data $NECROSS_ID $NECROSS_LETTER $AS_CIRCLE {
		font	2

		flag	$AS_VISIBLE_WORLD

//		  link	  $A_ID
//		  link	  $B_ID

		x	500
		y	300

		name	"Necross"
	}

	world_data $B_ID $B_LETTER $AS_TRIANGLE {
		font	2

		flag	$AS_SECRET_WORLD
		flag	$AS_VISIBLE_WORLD

		x	650
		y	300

		name	"Boozeena"
	}

	world_data $T_ID $T_LETTER $AS_TRIANGLE {
		font	2

		flag	$AS_SECRET_WORLD
		flag	$AS_VISIBLE_WORLD

		x	200
		y	500

		name "Threall"
	}

	world_data $K_ID $K_LETTER $AS_TRIANGLE {
		font	2

		flag	$AS_SECRET_WORLD
		flag	$AS_VISIBLE_WORLD

		x	650
		y	500

		name	"Khox"
	}
/*
	world_data $C_ID $C_LETTER $AS_SQUARE {
		font	2

		flag	$AS_SPECIAL_WORLD
		flag	$AS_VISIBLE_WORLD

		x	650
		y	280
	}

	world_data $E_ID $E_LETTER $AS_SQUARE {
		font	2

		flag	$AS_SPECIAL_WORLD
		flag	$AS_ACCESSIBLE_WORLD
		flag	$AS_VISIBLE_WORLD

		x	350
		y	780
	}
*/
	world_data $W_ID $W_LETTER $AS_TRIANGLE {
		font	2

		flag	$AS_SECRET_WORLD
//		  flag	  $AS_ACCESSIBLE_WORLD
		flag	$AS_VISIBLE_WORLD

		x	650
		y	700

		name	"Weexow"
	}

	world_data $H_ID $H_LETTER $AS_TRIANGLE {
		font	2

		flag	$AS_SECRET_WORLD
		flag	$AS_VISIBLE_WORLD

		x	800
		y	500

		name	"hMok"
	}
	world_data $A_ID $A_LETTER $AS_TRIANGLE {
		font	2

		flag	$AS_SECRET_WORLD
		flag	$AS_VISIBLE_WORLD

		x	350
		y	300

		name	"Ark-a-Znoy"
	}
}

#include "actint/aci_iscr.inc"

// MLs...
#include "actint/aci_ml.scr"

bitmap_menu {
	id	$BMENU_CAMERAS_MENU

	size_x	170
	size_y	220

	active_time	100

	bitmap_menu_item {
		id		$BMENU_ITEM_ROT

		x		500
		y		650

		bml_name	"resource/actint/640x480/bitmap/cam_r.bml"
	}
	bitmap_menu_item {
		id		$BMENU_ITEM_ZOOM

		x		350
		y		350

		bml_name	"resource/actint/640x480/bitmap/cam_z.bml"
	}
	bitmap_menu_item {
		id		$BMENU_ITEM_PERSP

		x		650
		y		350

		bml_name	"resource/actint/640x480/bitmap/cam_p.bml"
	}
}


