
/*
	actInt string defines

	English Version:
	#define <SOMEWORD>1	"..."

	Local Version:
	#define <SOMEWORD>2	"..."
*/

// actInt tutorial texts...

#define MODE_BUTTON_TEXT1		"Inventory ON/OFF"
#define MODE_BUTTON_TEXT2		"Показывать трюм: ДА/НЕТ"

#define PICKUP_ITEMS_BUTTON_TEXT1	"Pick-up items ON"
#define PICKUP_ITEMS_BUTTON_TEXT2	"Подбирать предметы"

#define PICKUP_WEAPONS_BUTTON_TEXT1	"Pick-up weapons ON"
#define PICKUP_WEAPONS_BUTTON_TEXT2	"Подбирать оружие"

#define ESCAVE_BUTTON_TEXT1		"Open..."
#define ESCAVE_BUTTON_TEXT2		"Открыть..."

#define ENERGY_IND_TEXT1		"Energy Shield/Armor"
#define ENERGY_IND_TEXT2		"Энергия/Броня"

#define LOAD_IND_TEXT1			"Inventory Charge"
#define LOAD_IND_TEXT2			"Загрузка трюма"

#define POWERUP_IND_TEXT1		"Device Energy"
#define POWERUP_IND_TEXT2		"Ресурс прибора"

#define SPIRAL_IND_TEXT1		"Spiral Energy"
#define SPIRAL_IND_TEXT2		"Заряд Спирали"
