
	Object "QuestPanel"{

		no_fon

		$PANELQ_COORDS

		Element BITMAP {
			id	"QuestPanelBMP"
			null_level	300

			$PANELQ_SIZE

			hidden_fon

			picture
			bmp_file	NONE
		}
	}

	Object "TimePanel"{

		no_fon

		$PANELTM_COORDS

		Element BITMAP {
			id	"TimePanelBMP"
			null_level	300

			$PANELTM_SIZE

			hidden_fon

			picture
			bmp_file	NONE
		}
	}

	Object "AnswerPanel"{

		no_fon

		$PANELANSW_COORDS

		Element BITMAP {
			id		"AnswerPanelBMP"
			null_level	300

			$PANELANSW_SIZE

			hidden_fon

			picture
			bmp_file	NONE
		}
	}
}

