IF(MINGW)
    SET(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
ENDIF()

FIND_LIBRARY(RUSTVANGERS_LIBRARY
	NAMES
	    vangers_ffi
	PATHS
	    ${RUSTVANGERS_ROOT}
		/usr/lib
		/usr/local/lib
		/opt/local/lib
		/sw/lib
		/local/lib
		/mingw/lib
		/local/bin
		/mingw/bin
		/usr/local/lib
)
IF(RUSTVANGERS_LIBRARY)
    SET(RUSTVANGERS_FOUND TRUE)
ENDIF(RUSTVANGERS_LIBRARY)

IF(RUSTVANGERS_FOUND)
    IF(NOT RUSTVANGERS_FIND_QUIETLY)
	    MESSAGE(STATUS "Found vange-rs ffi library: ${RUSTVANGERS_LIBRARY}")
	ENDIF(NOT RUSTVANGERS_FIND_QUIETLY)
ELSE(RUSTVANGERS_FOUND)
    IF(RUSTVANGERS_FIND_REQUIRED)
	    MESSAGE(FATAL_ERROR "Could not find vange-rs ffi library")
	ENDIF(RUSTVANGERS_FIND_REQUIRED)
ENDIF(RUSTVANGERS_FOUND)
