FIND_PATH(CLUNK_INCLUDE_DIR
  NAMES
    clunk/clunk.h
  HINTS
    ${CLUNK_ROOT}
    /usr/local
    /opt/local
    /mingw
  PATH_SUFFIXES include
)

FIND_LIBRARY(CLUNK_LIBRARY
  NAMES
    clunk
  HINTS
    ${CLUNK_ROOT}/lib
    ${CLUNK_ROOT}/bin
    /usr/local/lib
    /opt/local/lib
    /mingw/lib
    /mingw/bin
)
IF(CLUNK_INCLUDE_DIR AND CLUNK_LIBRARY)
   SET(CLUNK_FOUND TRUE)
ENDIF(CLUNK_INCLUDE_DIR AND CLUNK_LIBRARY)

IF(CLUNK_FOUND)
  IF(NOT TARGET Clunk::Clunk)
    ADD_LIBRARY(Clunk::Clunk INTERFACE IMPORTED)
    SET_TARGET_PROPERTIES(Clunk::Clunk PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${CLUNK_INCLUDE_DIR}"
      INTERFACE_LINK_LIBRARIES "${CLUNK_LIBRARY};SDL3::SDL3"
    )
  ENDIF()
  IF(NOT CLUNK_FIND_QUIETLY)
    MESSAGE(STATUS "Found clunk: ${CLUNK_LIBRARY} ${CLUNK_INCLUDE_DIR}")
  ENDIF(NOT CLUNK_FIND_QUIETLY)
ELSE(CLUNK_FOUND)
  IF(CLUNK_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find clunk")
  ENDIF(CLUNK_FIND_REQUIRED)
ENDIF(CLUNK_FOUND)
